using PlatinumOvertime_API.Models.Common;

namespace PlatinumOvertime_API.Models.Domain;

/// <summary>
/// Header table for an overtime request. The capture/workflow logic that
/// populates and transitions this is delivered in a follow-up task.
/// </summary>
public class OvertimeTransaction
{
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Auto-increment integer surrogate key generated by the database on
    /// insert.  Stored in <c>Payroll_EmployeeOvertime.LinkId</c> when the
    /// payroll capturer posts approved transactions.
    /// </summary>
    public int TransactionNo { get; set; }

    public string EmployeeId { get; set; } = string.Empty;
    public string EmployeeName { get; set; } = string.Empty;

    public string DepartmentId { get; set; } = string.Empty;
    public string DepartmentName { get; set; } = string.Empty;

    public string PositionId { get; set; } = string.Empty;

    // ---------- Legacy payroll classification (Const_*/Payroll_CyclePeriodDetails) ----------
    // Optional pointers into the read-only payroll master data the capture
    // form's dropdowns are bound to. Stored alongside the existing string
    // DepartmentId/Name (which is the integration boundary's ID — e.g.
    // "DPT-001") so both surfaces remain available without breaking
    // historical rows that pre-date these dropdowns. Names are snapshotted
    // at create/update time so the approval view can render labels without
    // re-querying the lookup tables.
    public int? LegacyDepartmentId { get; set; }
    public string? LegacyDepartmentName { get; set; }
    public int? LegacyDivisionId { get; set; }
    public string? LegacyDivisionName { get; set; }

    public DateTime OvertimeDate { get; set; }
    public TimeSpan? StartTime { get; set; }
    public TimeSpan? EndTime { get; set; }
    public decimal Hours { get; set; }

    public string? Reason { get; set; }

    // ---------- Salary head + amount snapshot ----------
    // Captured at create time so a later change to the underlying MOC formula
    // or salary-head metadata doesn't retroactively rewrite history.
    public int SalaryHeadId { get; set; }
    public string SalaryHeadName { get; set; } = string.Empty;
    public string FormulaSnapshot { get; set; } = string.Empty;
    public decimal Amount { get; set; }

    /// <summary>Hours already captured for this employee in the same counting
    /// period at the moment this row was created. Used to determine whether
    /// the transaction must take the excess-overtime branch.</summary>
    public decimal HoursAlreadyCapturedThisMonth { get; set; }

    /// <summary>True when this transaction's hours pushed the employee over
    /// the configured monthly maximum, requiring the additional excess
    /// approval step.</summary>
    public bool IsExcess { get; set; }

    /// <summary>True once the excess approver has signed off; only meaningful
    /// when IsExcess is true. Used to keep the row in ApprovedForPayment for a
    /// second hop (excess approval) before advancing to payroll capture.</summary>
    public bool IsExcessApproved { get; set; }

    /// <summary>True once the payroll capturer has released the row; the row
    /// stays in AwaitingPayrollApproval for a second hop (payroll approval)
    /// before being marked Processed.</summary>
    public bool IsPayrollCaptured { get; set; }

    public WorkflowStatus Status { get; set; } = WorkflowStatus.Requested;

    // ---------- Workflow assignee snapshot ----------
    // Names captured at create time so the dashboard can render "Who must
    // act next" without re-querying the position-approval graph.
    public string? RecommenderEmployeeId { get; set; }
    public string? RecommenderEmployeeName { get; set; }
    public string? ApproverEmployeeId { get; set; }
    public string? ApproverEmployeeName { get; set; }
    public string? ExcessApproverEmployeeId { get; set; }
    public string? ExcessApproverEmployeeName { get; set; }
    public string? PayrollCapturerEmployeeId { get; set; }
    public string? PayrollCapturerEmployeeName { get; set; }
    public string? PayrollApproverEmployeeId { get; set; }
    public string? PayrollApproverEmployeeName { get; set; }

    /// <summary>The current outstanding assignee (UserId of the dev directory
    /// in dev; an Employee_ID in prod). Null when the transaction has reached
    /// a terminal state (Processed / Rejected).</summary>
    public string? CurrentAssigneeUserId { get; set; }

    public string? CapturedBy { get; set; }

    /// <summary>
    /// Display name of the user who captured this transaction, persisted at
    /// creation time so the Capturer card renders correctly in production
    /// (where the dev user directory is not present).
    /// </summary>
    public string? CapturedByName { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    public ICollection<OvertimeTransactionDocument> Documents { get; set; } =
        new List<OvertimeTransactionDocument>();

    public ICollection<OvertimeWorkflowState> WorkflowHistory { get; set; } =
        new List<OvertimeWorkflowState>();
}
