import { Routes } from '@angular/router';
import { authGuard } from './core/guards/auth.guard';

export const routes: Routes = [
  {
    path: 'login',
    loadComponent: () => import('./features/auth/login/login.component').then(m => m.LoginComponent),
  },
  {
    path: '',
    canActivate: [authGuard],
    loadComponent: () => import('./shared/layout/pos-layout.component').then(m => m.PosLayoutComponent),
    children: [
      { path: '', loadComponent: () => import('./features/home/home.component').then(m => m.HomeComponent) },
      { path: 'pos', loadComponent: () => import('./features/pos/pos-workflow.component').then(m => m.PosWorkflowComponent) },
      { path: 'cashier-setup', redirectTo: 'pos', pathMatch: 'full' },
      { path: 'cashier-day-end', redirectTo: 'pos', pathMatch: 'full' },
      { path: 'direct-deposits/manual', loadComponent: () => import('./features/direct-deposits/manual/unmatched-queue.component').then(m => m.UnmatchedQueueComponent) },
      { path: 'direct-deposits/manual/allocate/:id', loadComponent: () => import('./features/direct-deposits/manual/allocate-transaction.component').then(m => m.AllocateTransactionComponent) },
      { path: 'direct-deposits/manual/history', loadComponent: () => import('./features/direct-deposits/manual/allocation-history.component').then(m => m.AllocationHistoryComponent) },
      { path: 'direct-deposits/auto', loadComponent: () => import('./features/direct-deposits/auto/auto-allocation.component').then(m => m.AutoAllocationComponent) },
      { path: 'bulk-allocation', loadComponent: () => import('./features/bulk-allocation/bulk-allocation-progress.component').then(m => m.BulkAllocationProgressComponent) },
      { path: 'third-party/processing', loadComponent: () => import('./features/third-party/payment-processing.component').then(m => m.PaymentProcessingComponent) },
      { path: 'third-party', redirectTo: 'third-party/processing', pathMatch: 'full' },
      { path: 'view-receipts', loadComponent: () => import('./features/receipts/view-receipts.component').then(m => m.ViewReceiptsComponent) },
      { path: 'billing-dashboard', loadComponent: () => import('./features/billing/billing-dashboard.component').then(m => m.BillingDashboardComponent) },
      { path: 'enquiries/general', loadComponent: () => import('./features/enquiries/enquiries-general.component').then(m => m.EnquiriesGeneralComponent) },
      { path: 'enquiries', redirectTo: 'enquiries/general', pathMatch: 'full' },
      { path: 'communications', loadComponent: () => import('./features/communications/client-communications.component').then(m => m.ClientCommunicationsComponent) },
      { path: 'supervisor', loadComponent: () => import('./features/supervisor/supervisor-dashboard.component').then(m => m.SupervisorDashboardComponent) },
      { path: 'settings', loadComponent: () => import('./features/settings/settings.component').then(m => m.SettingsComponent) },
      { path: 'debt/section129', loadComponent: () => import('./features/debt/section129/section129-notices.component').then(m => m.Section129NoticesComponent) },
      { path: 'debt/section129/review/:runId', loadComponent: () => import('./features/debt/section129/section129-trial-review.component').then(m => m.Section129TrialReviewComponent) },
      { path: 'debt/section129/authorize', loadComponent: () => import('./features/debt/section129/section129-authorization.component').then(m => m.Section129AuthorizationComponent) },
      { path: 'debt/section129/config', loadComponent: () => import('./features/debt/section129/section129-config.component').then(m => m.Section129ConfigComponent) },
      { path: 'debt/section129-report', loadComponent: () => import('./features/debt/section129/section129-report.component').then(m => m.Section129ReportComponent) },
      { path: 'debt/handover', loadComponent: () => import('./features/debt/handover/handover-management.component').then(m => m.HandoverManagementComponent) },
      { path: 'debt/handover/terminate', loadComponent: () => import('./features/debt/handover/handover-termination.component').then(m => m.HandoverTerminationComponent) },
      { path: 'debt/handover-report', loadComponent: () => import('./features/debt/handover/handover-report.component').then(m => m.HandoverReportComponent) },
      { path: 'debt/sms-log-report', loadComponent: () => import('./features/debt/communication/sms-log-report.component').then(m => m.SmsLogReportComponent) },
      { path: 'debt/risk-scoring', loadComponent: () => import('./features/debt/risk-scoring/risk-scoring.component').then(m => m.RiskScoringComponent) },
      { path: 'debt/qualification-rules', loadComponent: () => import('./features/debt/qualification/qualification-rules.component').then(m => m.QualificationRulesComponent) },
      { path: 'debt/communication-timelines', loadComponent: () => import('./features/debt/communication/communication-timeline.component').then(m => m.CommunicationTimelineComponent) },
      { path: 'debt/communication-dashboard', loadComponent: () => import('./features/debt/communication/communication-dashboard.component').then(m => m.CommunicationDashboardComponent) },
      { path: 'debt/batch-processing', loadComponent: () => import('./features/debt/batch/batch-processing.component').then(m => m.BatchProcessingComponent) },
      { path: 'debt/process-monitoring', loadComponent: () => import('./features/debt/monitoring/process-monitoring.component').then(m => m.ProcessMonitoringComponent) },
      { path: 'debt/document-templates', loadComponent: () => import('./features/debt/documents/document-templates.component').then(m => m.DocumentTemplatesComponent) },
      { path: 'debt/digital-signatures', loadComponent: () => import('./features/debt/signatures/digital-signatures.component').then(m => m.DigitalSignaturesComponent) },
      { path: 'debt/process-engine', loadComponent: () => import('./features/debt/engine/process-engine.component').then(m => m.ProcessEngineComponent) },
      { path: 'legal/rules', loadComponent: () => import('./features/legal/legal-rules.component').then(m => m.LegalRulesComponent) },
      { path: 'legal/audit-trail', loadComponent: () => import('./features/legal/audit-trail.component').then(m => m.AuditTrailComponent) },
      { path: 'legal/evidence-bundle', loadComponent: () => import('./features/legal/evidence-bundle.component').then(m => m.EvidenceBundleComponent) },
      { path: 'analytics/executive-dashboard', loadComponent: () => import('./features/analytics/executive-dashboard.component').then(m => m.ExecutiveDashboardComponent) },
      { path: 'analytics/predictive-forecasting', loadComponent: () => import('./features/analytics/predictive-forecasting.component').then(m => m.PredictiveForecastingComponent) },
      { path: 'analytics/geographic-mapping', loadComponent: () => import('./features/analytics/geographic-mapping.component').then(m => m.GeographicMappingComponent) },
      { path: '**', loadComponent: () => import('./features/home/not-found.component').then(m => m.NotFoundComponent) },
    ]
  }
];
