namespace MssqlApi.Models;

public class ConsVendor
{
    public int Vendor_ID { get; set; }
    public string? VendorName { get; set; }
    public string? CompanyDirector { get; set; }
    public string? RegistrationNumber { get; set; }
    public int? VendorCategoryID { get; set; }
    public int? VendorTypeID { get; set; }
    public string? MyReferenceNumber { get; set; }
    public bool? VatRegistered { get; set; }
    public string? VatRegistrationNumber { get; set; }
    public string? TaxCertificateNumber { get; set; }
    public DateTime? TaxCertificateDate { get; set; }
    public string? PostalAddress1 { get; set; }
    public string? PostalAddress2 { get; set; }
    public int? Postal_TownID { get; set; }
    public string? PostalCode { get; set; }
    public string? PhysicalAddress1 { get; set; }
    public string? PhysicalAddress2 { get; set; }
    public int? Physical_TownID { get; set; }
    public string? Country { get; set; }
    public string? Tel_Home { get; set; }
    public string? Tel_Work { get; set; }
    public string? Tel_Mobile { get; set; }
    public string? Fax { get; set; }
    public string? email { get; set; }
    public string? Website { get; set; }
    public int? BankID { get; set; }
    public int? BankAccountTypeID { get; set; }
    public string? BankAccountNumber { get; set; }
    public int? StatusID { get; set; }
    public bool? SupplyChainVendor { get; set; }
    public DateTime? CreditorListDate { get; set; }
    public DateTime? ListingExpiryDate { get; set; }
    public decimal? CreditLimit { get; set; }
    public decimal? PercentageDiscount { get; set; }
    public int? TermsDays { get; set; }
    public DateTime? LastPurchaseDate { get; set; }
    public decimal? BalanceAtMonthEnd { get; set; }
    public decimal? YearEndBalance { get; set; }
    public int? TotalOrdersAwardedForYear { get; set; }
    public int? VendorLocationID { get; set; }
    public decimal? BEEPercentage { get; set; }
    public bool? PreviouslyDisadvantaged { get; set; }
    public DateTime? PDIExpiryDate { get; set; }
    public string? Certificate { get; set; }
    public decimal? PDIPercentage { get; set; }
    public decimal? Woman { get; set; }
    public decimal? Disabled { get; set; }
    public decimal? HDI { get; set; }
    public int? UnitID { get; set; }
    public int? AccountID { get; set; }
    public string? Notes { get; set; }
    public string? ConstructionIndustryRegistration { get; set; }
    public DateTime? DateCaptured { get; set; }
    public int? CapturerID { get; set; }
    public DateTime? DateModified { get; set; }
    public int? ModifierID { get; set; }
    public int? BankBranchCodeID { get; set; }
    public string? VendorCreditor { get; set; }
    public string? TradingName { get; set; }
    public int? VendorRegistrationTypeID { get; set; }
    public string? CompensationCommRegNumber { get; set; }
    public string? PAYENumber { get; set; }
    public bool? PreviousBusiness { get; set; }
    public string? PreviousBusinessName { get; set; }
    public int? VendorBBBEEContributorLevelID { get; set; }
    public string? RegionalOfficesPhysicalLocation { get; set; }
    public string? NationalOfficesPhysicalLocation { get; set; }
    public int? CommunicationMethodID { get; set; }
    public bool? TaxClearanceCertVerified { get; set; }
    public bool? VATCertVerified { get; set; }
    public bool? IncomeTaxCertVerified { get; set; }
    public DateTime? TaxClearanceCertVerifiedDate { get; set; }
    public bool? AwaitingApproval { get; set; }
    public int? VendorBBBEEContributorExemptionLevelID { get; set; }
    public string? NameofBusinessforTradingPurpose { get; set; }
    public string? CIPROCompanyNo { get; set; }
    public string? EasternCapeOffice { get; set; }
    public bool? IsNTBackList { get; set; }
    public string? FirstName { get; set; }
    public string? LastName { get; set; }
    public string? UserName { get; set; }
    public string? Password { get; set; }
    public string? Reason { get; set; }
    public string? PhysicalPostalCode { get; set; }
    public int? VendorRegistrationID { get; set; }
    public int? CompanyTypeID { get; set; }
    public string? EmailAddress { get; set; }
    public string? ContactName { get; set; }
    public string? VendorNumber { get; set; }
    public string? CompanyName { get; set; }
    public bool? Approved { get; set; }
    public bool? Status { get; set; }
    public string? ServiceProviderNumber { get; set; }
    public string? IncomeTaxRefNumber { get; set; }
    public int? BBBEEContributorID { get; set; }
    public int? ProvinceID { get; set; }
    public string? NationalOffices { get; set; }
    public int? PrefferedMethodID { get; set; }
    public bool? NTBackList { get; set; }
    public int? RegistrationTypeID { get; set; }
    public string? FinancialYear { get; set; }
    public DateTime? RegisterDate { get; set; }
    public DateTime? ApprovalDate { get; set; }
    public DateTime? StatusUpdateDate { get; set; }
    public bool? Declaration { get; set; }
    public int? VoteID { get; set; }
    public int? PaymentMethodID { get; set; }
    public DateTime? BlackListedFromDate { get; set; }
    public DateTime? BlackListedToDate { get; set; }
    public int? BlackListedBy { get; set; }
    public string? BlackListReason { get; set; }
    public string? PreviousBusinessRegistration { get; set; }
    public string? StatusChangeReason { get; set; }
    public string? PaymentName { get; set; }
    public bool? bActivatedForPayroll { get; set; }
    public bool? bActivatedForBilling { get; set; }
    public bool? bActivatedForLedger { get; set; }
    public bool? bActivatedForAssets { get; set; }
    public bool? bActivatedForSCM { get; set; }
    public bool? bActivatedForPlanning { get; set; }
    public bool? bPayrollCommission { get; set; }
    public decimal? CommissionPercentage { get; set; }
    public int? Directive_ID { get; set; }
    public int? Contract_ID { get; set; }
    public int? Order_ID { get; set; }
    public Guid? UniqueRegistrationReferenceNumber { get; set; }
    public DateTime? LastCsdSupplierIdentificationUpdateDate { get; set; }
    public string? CSDSupplierNumber { get; set; }
    public DateTime? LastCsdSupplierTaxDetailsUpdateDate { get; set; }
    public DateTime? TaxCertificateExpiryDate { get; set; }
    public DateTime? LastVerificationDate { get; set; }
    public decimal? DiscountRate { get; set; }
    public int? QualifyingDays { get; set; }
    public Guid? VendorRef_seb { get; set; }
    public bool? IsCSDImport { get; set; }
    public string? TotalAnnualTurnover { get; set; }
    public string? TotalAnnualTurnoverName { get; set; }
}
