namespace MssqlApi.Models;

public class ScmContractDetails
{
    public int Contract_ID { get; set; }
    public string? ContractNumber { get; set; }
    public string? ContractDescription { get; set; }
    public bool? TenderQuotation { get; set; }
    public int? TenderQuotationID { get; set; }
    public int? ContractManagerID { get; set; }
    public int? ServiceTypeID { get; set; }
    public int? VoteID { get; set; }
    public string? OrderNumber { get; set; }
    public decimal? Contractvalue { get; set; }
    public DateTime? PlannedStartDate { get; set; }
    public DateTime? PlannedEndDate { get; set; }
    public DateTime? RevisedStartDate { get; set; }
    public DateTime? RevisedEndDate { get; set; }
    public DateTime? ActualStartDate { get; set; }
    public DateTime? ActualEndDate { get; set; }
    public bool Enabled { get; set; }
    public DateTime DateCaptured { get; set; }
    public int CapturerID { get; set; }
    public DateTime? DateModified { get; set; }
    public int? ModifierID { get; set; }
    public string? FinancialYear { get; set; }
    public int? ContractStatusId { get; set; }
    public string? Comments { get; set; }
    public bool? QuantityDriven { get; set; }
    public int? VendorID { get; set; }
    public int? ProcurementID { get; set; }
    public bool? RetentionIndicator { get; set; }
    public decimal? RetentionRate { get; set; }
    public int? ContractTypeID { get; set; }
    public string? CurrentPeriodCommitment { get; set; }
    public decimal? InvoicedAmount { get; set; }
    public decimal? RevisedContractValue { get; set; }
    public int? ContractType_ID { get; set; }
    public int? Status_ID { get; set; }
    public int? Milestone_ID { get; set; }
    public int? VariationLimitID { get; set; }
    public string? DebitOrderRef { get; set; }
    public DateTime? DebitOrderExpiryDate { get; set; }
    public bool? IsVoid { get; set; }
    public DateTime? VoidedDate { get; set; }
    public string? VoidedReason { get; set; }
    public int? VoidedBy { get; set; }
    public int? ReferenceToID { get; set; }
    public DateTime? RetentionStartDate { get; set; }
    public DateTime? RetentionEndDate { get; set; }
    public bool? PayCertificateRequired { get; set; }
    public int? LoanRegisterID { get; set; }
    public bool? LoanContract { get; set; }
    public decimal? GuaranteeRate { get; set; }
    public DateTime? GuaranteeRateStartDate { get; set; }
    public DateTime? GuaranteeRateEndDate { get; set; }
    public bool? GuaranteeQuantityDriven { get; set; }
    public bool? GuaranteeIndicator { get; set; }
    public bool? SocialResponsibilityIndicator { get; set; }
    public decimal? SocialResponsibilityRate { get; set; }
    public decimal? TotalRetentionReleased { get; set; }
    public decimal? TotalRetentionRetained { get; set; }
    public decimal? TotalGuaranteeReleased { get; set; }
    public decimal? TotalGuaranteeRetained { get; set; }
    public int? PreviousContractID { get; set; }
    public int? FinalApprovedBy { get; set; }
    public DateTime? FinalApprovedDate { get; set; }
    public string? PanelOfVendors { get; set; }
    public decimal? TotalRetentionWithholding { get; set; }
    public decimal? TotalGuaranteeWithholding { get; set; }
    public bool? isContractTakeOn { get; set; }
}
