import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import cyclesRouter from "./cycles";
import kpiConfigRouter from "./kpi-config";
import weightingsRouter from "./weightings";
import deadlinesRouter from "./deadlines";
import auditRouter from "./audit";
import notificationsRouter from "./notifications";
import scorecardsRouter from "./scorecards";
import monthActivitiesRouter from "./month-activities";
import sdbipRouter from "./sdbip";
import actualsRouter from "./actuals";
import deptScorecardsRouter from "./dept-scorecards";
import reviewsRouter from "./reviews";
import moderationRouter from "./moderation";
import periodLocksRouter from "./period-locks";
import dashboardsRouter from "./dashboards";
import reportsRouter from "./reports";
import agreementsRouter from "./agreements";
import individualReviewsRouter from "./individual-reviews";
import competencyTemplatesRouter from "./competency-templates";
import aiInsightsRouter from "./ai-insights";
import integrationsRouter from "./integrations";
import workflowConfigRouter from "./workflow-config";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(cyclesRouter);
router.use(kpiConfigRouter);
router.use(weightingsRouter);
router.use(deadlinesRouter);
router.use(auditRouter);
router.use(notificationsRouter);
router.use(scorecardsRouter);
router.use(monthActivitiesRouter);
router.use(sdbipRouter);
router.use(actualsRouter);
router.use(deptScorecardsRouter);
router.use(reviewsRouter);
router.use(moderationRouter);
router.use(periodLocksRouter);
router.use(dashboardsRouter);
router.use(reportsRouter);
router.use(agreementsRouter);
router.use(individualReviewsRouter);
router.use(competencyTemplatesRouter);
router.use(aiInsightsRouter);
router.use(integrationsRouter);
router.use(workflowConfigRouter);

export default router;
