import { Component, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { ApiService } from '../../../core/services/api.service';
import { UiService } from '../../../core/services/ui.service';
import { IconComponent } from '../../../shared/components/icon/icon.component';
import { CurrencyZarPipe } from '../../../shared/pipes/currency-zar.pipe';

@Component({
  selector: 'app-employee-detail',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule, IconComponent, CurrencyZarPipe],
  templateUrl: './employee-detail.component.html',
  styleUrl: './employee-detail.component.css'
})
export class EmployeeDetailComponent {
  mode: 'create' | 'view' | 'edit' = 'view';
  activeGroup: 'employee' | 'employment' | 'payroll' | 'benefits' = 'employee';
  activeSubTab: 'employment' | 'personal' | 'contact' | 'address' | 'hours-rates' | 'salary-transactions' | 'medical-aid' | 'retirement-funds' | 'unions' = 'personal';
  emp: any = this.newEmployee();
  lookups: any = {};
  vacantPositions: any[] = [];
  filteredDivisions: any[] = [];
  filteredPositions: any[] = [];
  filteredProvinces: any[] = [];
  filteredTowns: any[] = [];
  filteredSuburbs: any[] = [];
  loading = true;
  saving = false;
  error = '';

  payrollCycles: any[] = [];
  salaryTxnsLoading = false;
  inheritedGroup: any = { group_name: null, group_code: null, items: [] };
  employeeTxns: any[] = [];
  mergedTxns: any[] = [];
  allSalaryHeads: any[] = [];
  showSalaryTxnModal = false;
  editSalaryTxn: any = {};
  availableSalaryHeads: any[] = [];
  filteredModalHeads: any[] = [];
  selectedTxnType: string = '';

  medAidLoading = false;
  medAidSchemes: any[] = [];
  medAidMemberships: any[] = [];
  currentMembership: any = null;
  medAidInnerTab: 'scheme' | 'extra-transactions' | 'dependants' = 'scheme';

  showMedAidSchemeModal = false;
  editMedAidScheme: any = {};
  medAidSchemeMode: 'create' | 'edit' = 'create';
  medAidFunds: string[] = [];
  selectedFund: string = '';
  filteredPlans: any[] = [];

  showDependantModal = false;
  editDependant: any = {};
  dependantMode: 'create' | 'edit' = 'create';

  showExtraTxnModal = false;
  editExtraTxn: any = {};
  extraTxnMode: 'create' | 'edit' = 'create';

  gradeNotches: any[] = [];
  selectedNotch: any = null;

  taxMethods = [
    { id: 1, name: 'Tax Tables' },
    { id: 2, name: 'Tax Directive' },
    { id: 3, name: 'Councilor full time, tax by tables' },
    { id: 4, name: 'Councilor part time, tax by %' }
  ];
  bonusTaxPreferences = [
    { id: 1, name: 'No Bonus' },
    { id: 2, name: 'Month of Bonus' },
    { id: 3, name: 'Tax Spread' }
  ];
  municipalityBonusConfig: any = {};

  retFundsLoading = false;
  retFundTypes: any[] = [];
  retPensionFunds: any[] = [];
  retProvidentFunds: any[] = [];
  retAnnuityFunds: any[] = [];
  emsVendors: any[] = [];
  retInnerTab: 'pension' | 'provident' | 'retirement' = 'pension';
  showRetFundModal = false;
  editRetFund: any = {};
  retFundMode: 'create' | 'edit' = 'create';

  constructor(
    public api: ApiService,
    private ui: UiService,
    private route: ActivatedRoute,
    private router: Router,
    public cdr: ChangeDetectorRef
  ) {}

  ngOnInit() {
    const id = this.route.snapshot.paramMap.get('id');
    if (id === 'new') {
      this.mode = 'create';
      this.activeGroup = 'employee';
      this.activeSubTab = 'personal';
      this.emp = this.newEmployee();
      this.loadLookups();
    } else {
      this.mode = 'view';
      this.activeGroup = 'employee';
      this.activeSubTab = 'personal';
      this.loadEmployee(Number(id));
    }
  }

  autoGeneratedCode = '';
  todayStr = new Date().toISOString().split('T')[0];

  get isEditable(): boolean { return this.mode === 'create' || this.mode === 'edit'; }

  newEmployee(): any {
    return {
      employee_code: '', employee_create_type: 'New Employee',
      department_id: null, division_id: null, position_id: null,
      job_profile_id: null, employee_type_id: null, employee_subtype_id: null,
      condition_of_service_id: null, task_grade_id: null,
      payroll_cycle_id: null, tax_method: 1,
      working_hours_per_month: null, working_days_per_month: null,
      working_hours_per_day: 8, working_days_per_week: 5,
      salary_based_on: 'CAPTURED_VALUE', wage_rate: 0,
      allow_overtime: false, exclude_sdl: false, exclude_uif: false, upper_limit_value_type: null,
      annual_salary: null, monthly_salary: null, enable_bonus: false, bonus_tax_preference: 1,
      bonus_period: null, bonus_month: null, bonus_amount: null,
      joining_date: new Date().toISOString().split('T')[0], end_date: '9999-12-31',
      id_number: '', passport_number: '', passport_country: '',
      title: '', surname: '', full_name: '', first_name: '', nickname: '', initials: '',
      date_of_birth: '', gender: '', nature_of_person_code: 'A',
      marital_status: 'Single', marital_date: '',
      home_language: '', ethnic_group: '', race: '',
      is_youth: false, is_foreigner: false, has_disability: false,
      cell_number: '', home_number: '', email_address: '',
      pay_point_id: null,
      payslip_pref_email: false, payslip_pref_sms: false, payslip_pref_print: true,
      physical_address_1: '', physical_address_2: '', physical_address_3: '', physical_address_4: '', physical_address_5: '',
      postal_same_as_physical: false,
      postal_address_1: '', postal_address_2: '', postal_address_3: '', postal_address_4: '', postal_address_5: '',
      job_title: '', employee_type_name: '', employee_subtype_name: '',
      condition_of_service_name: '', grade_code: '', grade_name: '',
    };
  }

  loadPayrollCycles() {
    this.api.get<any[]>('/payroll/cycles').subscribe({
      next: (data) => { this.payrollCycles = data || []; this.cdr.detectChanges(); },
      error: () => { this.payrollCycles = []; }
    });
  }

  loadMunicipalityBonusConfig() {
    this.api.get<any>('/settings/municipality').subscribe({
      next: (data) => {
        const settings: any = {};
        if (Array.isArray(data)) {
          data.forEach((s: any) => { settings[s.key] = s.value; });
        } else if (data && typeof data === 'object') {
          Object.assign(settings, data);
        }
        this.municipalityBonusConfig = settings;
        this.applyBonusDefaults();
        this.cdr.detectChanges();
      },
      error: () => {}
    });
  }

  applyBonusDefaults() {
    if (!this.emp || !this.municipalityBonusConfig) return;
    if (!this.emp.bonus_period && this.municipalityBonusConfig.bonus_payment_timing) {
      this.emp.bonus_period = this.municipalityBonusConfig.bonus_payment_timing;
    }
    if (!this.emp.bonus_month && this.municipalityBonusConfig.bonus_payment_month) {
      this.emp.bonus_month = Number(this.municipalityBonusConfig.bonus_payment_month);
    }
    if (this.emp.enable_bonus && !this.emp.bonus_amount && this.emp.monthly_salary) {
      this.emp.bonus_amount = Number(this.emp.monthly_salary);
    }
  }

  onEnableBonusChange() {
    if (this.emp.enable_bonus) {
      this.applyBonusDefaults();
      if (!this.emp.bonus_amount && this.emp.monthly_salary) {
        this.emp.bonus_amount = Number(this.emp.monthly_salary);
      }
    }
    this.cdr.detectChanges();
  }

  loadLookups() {
    this.loadPayrollCycles();
    this.loadMunicipalityBonusConfig();
    this.api.get<any>('/employees/lookups/employee-all').subscribe({
      next: (data) => {
        this.lookups = data || {};
        if (this.mode === 'create') {
          this.api.get<any>('/employees/next-employee-number').subscribe({
            next: (numData) => {
              if (numData?.employee_number) {
                this.autoGeneratedCode = numData.employee_number;
                this.emp.employee_code = numData.employee_number;
              }
              this.loading = false;
              this.cdr.detectChanges();
            },
            error: () => { this.loading = false; this.cdr.detectChanges(); }
          });
        } else {
          this.loading = false;
          this.cdr.detectChanges();
        }
      },
      error: () => {
        this.error = 'Failed to load lookups';
        this.loading = false;
        this.cdr.detectChanges();
      }
    });
  }

  loadEmployee(id: number) {
    this.loadPayrollCycles();
    this.loadMunicipalityBonusConfig();
    this.api.get<any>('/employees/lookups/employee-all').subscribe({
      next: (lookupData) => {
        this.lookups = lookupData || {};
        this.api.get<any>(`/employees/${id}`).subscribe({
          next: (data) => {
            this.emp = { ...this.newEmployee(), ...data };
            if (!this.emp.working_hours_per_month && this.emp.et_working_hours_per_month) {
              this.emp.working_hours_per_month = this.emp.et_working_hours_per_month;
            }
            if (!this.emp.working_days_per_month && this.emp.et_working_days_per_month) {
              this.emp.working_days_per_month = this.emp.et_working_days_per_month;
            }
            if (this.emp.resolved_task_grade_id && !this.emp.task_grade_id) {
              this.emp.task_grade_id = this.emp.resolved_task_grade_id;
            }
            const tmMap: any = { 'TAX_TABLES': 1, 'DIRECTIVE': 2, 'FIXED_PERCENTAGE': 3 };
            if (typeof this.emp.tax_method === 'string' && tmMap[this.emp.tax_method]) {
              this.emp.tax_method = tmMap[this.emp.tax_method];
            }
            if (this.emp.tax_method) this.emp.tax_method = Number(this.emp.tax_method);
            if (this.emp.bonus_tax_preference) this.emp.bonus_tax_preference = Number(this.emp.bonus_tax_preference);
            if (this.emp.enable_bonus === null || this.emp.enable_bonus === undefined) {
              this.emp.enable_bonus = !!this.emp.subtype_enable_bonus;
            }
            if (this.emp.exclude_uif === null || this.emp.exclude_uif === undefined) {
              this.emp.exclude_uif = !!this.emp.subtype_exclude_uif;
            }
            if (this.emp.exclude_sdl === null || this.emp.exclude_sdl === undefined) {
              this.emp.exclude_sdl = !!this.emp.subtype_exclude_sdl;
            }
            if (this.emp.department_id) this.onDepartmentChange(false);
            if (this.emp.division_id) this.onDivisionChange(false);
            if (this.emp.task_grade_id) {
              this.loadNotchesForGrade(this.emp.task_grade_id);
            }
            this.loading = false;
            this.cdr.detectChanges();
          },
          error: () => {
            this.error = 'Failed to load employee';
            this.loading = false;
            this.cdr.detectChanges();
          }
        });
      },
      error: () => {
        this.error = 'Failed to load lookups';
        this.loading = false;
        this.cdr.detectChanges();
      }
    });
  }

  onDepartmentChange(resetChildren = true) {
    this.filteredDivisions = (this.lookups.divisions || []).filter(
      (d: any) => d.department_id === this.emp.department_id
    );
    if (resetChildren) {
      this.emp.division_id = null;
      this.emp.position_id = null;
      this.clearPositionDerived();
    }
    this.filteredPositions = [];
    this.cdr.detectChanges();
  }

  onDivisionChange(resetChildren = true) {
    if (resetChildren) {
      this.emp.position_id = null;
      this.clearPositionDerived();
    }
    if (this.emp.department_id && this.emp.division_id) {
      this.api.get<any[]>('/employees/vacant-positions', {
        department_id: this.emp.department_id,
        division_id: this.emp.division_id
      }).subscribe({
        next: (data) => {
          this.vacantPositions = data || [];
          this.filteredPositions = this.vacantPositions;
          this.cdr.detectChanges();
        },
        error: () => { this.filteredPositions = []; this.cdr.detectChanges(); }
      });
    } else {
      this.filteredPositions = [];
      this.cdr.detectChanges();
    }
  }

  onCreateTypeChange() {
    if (this.emp.employee_create_type === 'Take-On Employee') {
      this.emp.employee_code = '';
    } else {
      this.emp.employee_code = this.autoGeneratedCode;
    }
    this.cdr.detectChanges();
  }

  onPositionChange() {
    const pos = this.vacantPositions.find((p: any) => p.id === this.emp.position_id);
    if (pos) {
      this.emp.job_profile_id = pos.job_profile_id;
      this.emp.employee_type_id = pos.employee_type_id;
      this.emp.employee_subtype_id = pos.employee_subtype_id;
      this.emp.condition_of_service_id = pos.condition_of_service_id;
      this.emp.job_title = pos.job_title || '';
      this.emp.employee_type_name = pos.employee_type_name || '';
      this.emp.employee_subtype_name = pos.employee_subtype_name || '';
      this.emp.condition_of_service_name = pos.condition_of_service_name || '';
      if (pos.non_employee) this.emp.employee_create_type = 'Non-Employee';
      if (pos.upper_limit_id) {
        this.emp.task_grade_id = null;
        this.emp.grade_code = '';
        this.emp.grade_name = '';
        this.emp.upper_limit_id = pos.upper_limit_id;
        
        this.emp.upper_limit_minimum = pos.upper_limit_minimum;
        this.emp.upper_limit_midpoint = pos.upper_limit_midpoint;
        this.emp.upper_limit_maximum = pos.upper_limit_maximum;
        this.emp.upper_limit_value_type = pos.upper_limit_value_type || null;
        this.emp.annual_salary = null;
      } else {
        this.emp.task_grade_id = pos.task_grade_id;
        this.emp.grade_code = pos.grade_code || '';
        this.emp.grade_name = pos.grade_name || '';
        this.emp.upper_limit_id = null;
        
        this.emp.upper_limit_minimum = null;
        this.emp.upper_limit_midpoint = null;
        this.emp.upper_limit_maximum = null;
        this.emp.upper_limit_value_type = null;
        this.emp.monthly_salary = pos.task_grade_min_salary || null;
        this.emp.annual_salary = this.emp.monthly_salary ? Number(this.emp.monthly_salary) * 12 : null;
        if (pos.task_grade_id) {
          this.loadNotchesForGrade(pos.task_grade_id, 1);
        }
      }
      this.emp.working_hours_per_month = pos.et_working_hours_per_month || 166.00;
      this.emp.working_days_per_month = pos.et_working_days_per_month || 20.75;
      this.emp.exclude_sdl = pos.subtype_exclude_sdl || false;
    } else {
      this.clearPositionDerived();
    }
    this.cdr.detectChanges();
  }

  clearPositionDerived() {
    this.emp.job_profile_id = null;
    this.emp.employee_type_id = null;
    this.emp.employee_subtype_id = null;
    this.emp.condition_of_service_id = null;
    this.emp.task_grade_id = null;
    this.emp.job_title = '';
    this.emp.employee_type_name = '';
    this.emp.employee_subtype_name = '';
    this.emp.condition_of_service_name = '';
    this.emp.grade_code = '';
    this.emp.grade_name = '';
    this.emp.upper_limit_id = null;
    
    this.emp.upper_limit_minimum = null;
    this.emp.upper_limit_midpoint = null;
    this.emp.upper_limit_maximum = null;
    this.emp.upper_limit_value_type = null;
    this.emp.working_hours_per_month = null;
    this.emp.working_days_per_month = null;
    this.gradeNotches = [];
    this.selectedNotch = null;
    this.emp.current_notch = null;
    this.emp.monthly_salary = null;
    this.emp.annual_salary = null;
  }

  loadNotchesForGrade(gradeId: number, selectNotchNumber?: number): void {
    this.selectedNotch = null;
    this.api.get<any[]>(`/settings/task-grades/${gradeId}/notches`).subscribe({
      next: (notches) => {
        this.gradeNotches = (notches || []).sort((a: any, b: any) => a.notch_number - b.notch_number);
        if (this.gradeNotches.length === 0) {
          this.selectedNotch = null;
          this.emp.current_notch = null;
          this.cdr.detectChanges();
          return;
        }
        if (selectNotchNumber) {
          const match = this.gradeNotches.find((n: any) => n.notch_number === selectNotchNumber);
          this.selectedNotch = match || this.gradeNotches[0];
          this.emp.current_notch = this.selectedNotch.id;
          this.emp.monthly_salary = Number(this.selectedNotch.min_salary);
          this.emp.annual_salary = this.emp.monthly_salary * 12;
        } else if (this.emp.current_notch) {
          const match = this.gradeNotches.find((n: any) => n.id === this.emp.current_notch);
          if (match) {
            this.selectedNotch = match;
          } else {
            this.selectedNotch = this.gradeNotches[0];
            this.emp.current_notch = this.selectedNotch.id;
          }
        }
        this.cdr.detectChanges();
      },
      error: () => {
        this.gradeNotches = [];
        this.selectedNotch = null;
        this.cdr.detectChanges();
      }
    });
  }

  onNotchChange(): void {
    if (!this.emp.current_notch) {
      this.selectedNotch = null;
      this.emp.monthly_salary = null;
      this.emp.annual_salary = null;
      this.cdr.detectChanges();
      return;
    }
    const notch = this.gradeNotches.find((n: any) => n.id === this.emp.current_notch);
    if (notch) {
      this.selectedNotch = notch;
      this.emp.monthly_salary = Number(notch.min_salary);
      this.emp.annual_salary = this.emp.monthly_salary * 12;
    }
    this.cdr.detectChanges();
  }

  onMonthlySalaryChange(): void {
    const monthly = Number(this.emp.monthly_salary) || 0;
    this.emp.annual_salary = parseFloat((monthly * 12).toFixed(2));
    this.cdr.detectChanges();
  }

  get notchSalaryValid(): boolean {
    if (!this.selectedNotch || this.emp.monthly_salary === null || this.emp.monthly_salary === undefined || this.emp.monthly_salary === '') return true;
    const salary = Number(this.emp.monthly_salary);
    if (isNaN(salary)) return false;
    const min = Number(this.selectedNotch.min_salary);
    const max = Number(this.selectedNotch.max_salary);
    return salary >= min && salary <= max;
  }

  getTaxMethodName(id: any): string {
    const m = this.taxMethods.find(t => t.id === Number(id));
    return m ? m.name : (id || '-');
  }

  getBonusTaxPrefName(id: any): string {
    const m = this.bonusTaxPreferences.find(t => t.id === Number(id));
    return m ? m.name : (id || '-');
  }

  getBonusPeriodName(val: string): string {
    const map: any = { 'SPECIFIC_MONTH': 'Specific Calendar Month', 'ANNIVERSARY': 'Employee Anniversary', 'SAME_MONTH': 'All Employees on same month' };
    return map[val] || val || '-';
  }

  getMonthName(month: any): string {
    const months = ['', 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
    return months[Number(month)] || '-';
  }

  get isTaskGradeEmployee(): boolean {
    return !!this.emp.task_grade_id && !this.isUpperLimitEmployee;
  }

  get isUpperLimitEmployee(): boolean {
    return !!this.emp.upper_limit_id;
  }

  get payStructureType(): string {
    if (this.isUpperLimitEmployee) return 'Upper Limit';
    if (this.isTaskGradeEmployee) return 'Task Grade';
    return 'Rate Based';
  }

  get salarySourceLabel(): string {
    if (this.isUpperLimitEmployee) {
      return 'Upper Limit' + (this.emp.upper_limit_id ? ' #' + this.emp.upper_limit_id : '');
    }
    if (this.emp.grade_code || this.emp.grade_name) {
      return 'Task Grade — ' + (this.emp.grade_code ? this.emp.grade_code + ' ' : '') + (this.emp.grade_name || '');
    }
    return '-';
  }

  get upperLimitBasicSalary(): number {
    return Number(this.emp.monthly_salary) || 0;
  }

  get upperLimitMonthlyBasicSalary(): number {
    return this.upperLimitBasicSalary;
  }

  get monthlyFixedSalary(): number {
    if (this.isUpperLimitEmployee) {
      const vt = this.emp.upper_limit_value_type;
      if (vt === 'MINIMUM') return (Number(this.emp.upper_limit_minimum) || 0) / 12;
      if (vt === 'MIDPOINT') return (Number(this.emp.upper_limit_midpoint) || 0) / 12;
      if (vt === 'MAXIMUM') return (Number(this.emp.upper_limit_maximum) || 0) / 12;
      return 0;
    }
    return Number(this.emp.monthly_salary) || (Number(this.emp.annual_salary) || 0) / 12;
  }

  get monthlyRateBasis(): number {
    if (this.isUpperLimitEmployee && this.upperLimitMonthlyBasicSalary > 0) {
      return this.upperLimitMonthlyBasicSalary;
    }
    if (this.payStructureType === 'Rate Based') {
      const sbo = this.emp.salary_based_on;
      const wageRate = Number(this.emp.wage_rate) || 0;
      if (sbo === 'RATE_PER_DAY' && wageRate > 0) {
        const dpm = Number(this.emp.working_days_per_month) || 0;
        return dpm > 0 ? Math.round(wageRate * dpm * 100) / 100 : 0;
      }
      if (sbo === 'RATE_PER_HOUR' && wageRate > 0) {
        const hpm = Number(this.emp.working_hours_per_month) || 0;
        return hpm > 0 ? Math.round(wageRate * hpm * 100) / 100 : 0;
      }
    }
    return this.monthlyFixedSalary;
  }

  get annualSalary(): number {
    if (this.isUpperLimitEmployee) {
      const vt = this.emp.upper_limit_value_type;
      if (vt === 'MINIMUM') return Number(this.emp.upper_limit_minimum) || 0;
      if (vt === 'MIDPOINT') return Number(this.emp.upper_limit_midpoint) || 0;
      if (vt === 'MAXIMUM') return Number(this.emp.upper_limit_maximum) || 0;
      return 0;
    }
    if (this.payStructureType === 'Rate Based') {
      const sbo = this.emp.salary_based_on;
      if (sbo === 'RATE_PER_DAY' || sbo === 'RATE_PER_HOUR') {
        return Math.round(this.monthlyRateBasis * 12 * 100) / 100;
      }
    }
    return Number(this.emp.annual_salary) || 0;
  }

  recalcRateBasedSalaries(): void {
    if (this.payStructureType !== 'Rate Based') return;
    const sbo = this.emp.salary_based_on;
    if (sbo !== 'RATE_PER_DAY' && sbo !== 'RATE_PER_HOUR') return;
    const monthly = this.monthlyRateBasis;
    this.emp.monthly_salary = monthly;
    this.emp.annual_salary = Math.round(monthly * 12 * 100) / 100;
    this.cdr.detectChanges();
  }

  get workingHoursPerDay(): number {
    const hrs = Number(this.emp.working_hours_per_month) || 0;
    const days = Number(this.emp.working_days_per_month) || 0;
    return days > 0 ? Math.round((hrs / days) * 100) / 100 : 0;
  }

  get ratePerDay(): number {
    const days = Number(this.emp.working_days_per_month) || 0;
    return days > 0 ? Math.round((this.monthlyRateBasis / days) * 100) / 100 : 0;
  }

  get ratePerHour(): number {
    const hrs = Number(this.emp.working_hours_per_month) || 0;
    return hrs > 0 ? Math.round((this.monthlyRateBasis / hrs) * 100) / 100 : 0;
  }

  get ratePerWeek(): number {
    return this.ratePerDay * (Number(this.emp.working_days_per_week) || 0);
  }

  getSalaryBasedOnLabel(val: string): string {
    const map: Record<string, string> = {
      'RATE_PER_HOUR': 'Rate Per Hour',
      'RATE_PER_DAY': 'Rate Per Day',
      'CAPTURED_VALUE': 'Captured Value',
      'FIXED_RATE': 'Fixed Rate'
    };
    return map[val] || val || 'Captured Value';
  }

  onIdNumberChange() {
    const id = this.emp.id_number?.trim();
    if (!id || id.length !== 13 || !/^\d{13}$/.test(id)) return;
    const yy = parseInt(id.substring(0, 2), 10);
    const mm = parseInt(id.substring(2, 4), 10);
    const dd = parseInt(id.substring(4, 6), 10);
    const year = yy >= 0 && yy <= 30 ? 2000 + yy : 1900 + yy;
    if (mm >= 1 && mm <= 12 && dd >= 1 && dd <= 31) {
      this.emp.date_of_birth = `${year}-${String(mm).padStart(2, '0')}-${String(dd).padStart(2, '0')}`;
    }
    const genderDigits = parseInt(id.substring(6, 10), 10);
    this.emp.gender = genderDigits >= 5000 ? 'Male' : 'Female';
    this.cdr.detectChanges();
  }

  get idValid(): boolean { return this.emp.id_number && /^\d{13}$/.test(this.emp.id_number.trim()); }
  get dobLocked(): boolean { return this.idValid; }

  get calculatedAge(): number | null {
    if (!this.emp.date_of_birth) return null;
    const dob = new Date(this.emp.date_of_birth);
    const today = new Date();
    let age = today.getFullYear() - dob.getFullYear();
    const m = today.getMonth() - dob.getMonth();
    if (m < 0 || (m === 0 && today.getDate() < dob.getDate())) age--;
    return age;
  }

  onNameChange() {
    const parts: string[] = [];
    if (this.emp.first_name) parts.push(...this.emp.first_name.trim().split(/\s+/));
    if (this.emp.second_name) parts.push(...this.emp.second_name.trim().split(/\s+/));
    if (parts.length) {
      this.emp.initials = parts.map((p: string) => p.charAt(0).toUpperCase()).join('');
      this.emp.full_name = [this.emp.first_name, this.emp.second_name, this.emp.surname].filter(Boolean).join(' ');
    }
    this.cdr.detectChanges();
  }

  filterPhysicalProvinces() {
    this.filteredProvinces = (this.lookups.provinces || []).filter((p: any) => p.country_id === this.emp.physical_country_id);
  }
  filterPhysicalTowns() {
    this.filteredTowns = (this.lookups.towns || []).filter((t: any) => t.province_id === this.emp.physical_province_id);
  }
  filterPhysicalSuburbs() {
    this.filteredSuburbs = (this.lookups.suburbs || []).filter((s: any) => s.town_id === this.emp.physical_town_id);
  }
  onPhysicalCountryChange() { this.emp.physical_province_id = null; this.emp.physical_town_id = null; this.emp.physical_suburb_id = null; this.filterPhysicalProvinces(); this.cdr.detectChanges(); }
  onPhysicalProvinceChange() { this.emp.physical_town_id = null; this.emp.physical_suburb_id = null; this.filterPhysicalTowns(); this.cdr.detectChanges(); }
  onPhysicalTownChange() { this.emp.physical_suburb_id = null; this.filterPhysicalSuburbs(); this.cdr.detectChanges(); }
  onPhysicalSuburbChange() {
    const sub = this.filteredSuburbs.find((s: any) => s.id === this.emp.physical_suburb_id);
    if (sub?.postal_code) this.emp.physical_postal_code = sub.postal_code;
    this.cdr.detectChanges();
  }


  onPostalSameAsPhysical() {
    if (this.emp.postal_same_as_physical) {
      this.emp.postal_address_1 = this.emp.physical_address_1;
      this.emp.postal_address_2 = this.emp.physical_address_2;
      this.emp.postal_address_3 = this.emp.physical_address_3;
      this.emp.postal_address_4 = this.emp.physical_address_4;
      this.emp.postal_address_5 = this.emp.physical_address_5;
    }
    this.cdr.detectChanges();
  }

  onPostalCodeInput(event: Event, type: 'physical' | 'postal') {
    const input = event.target as HTMLInputElement;
    input.value = input.value.replace(/[^0-9]/g, '');
    if (type === 'physical') {
      this.emp.physical_address_5 = input.value;
    } else {
      this.emp.postal_address_5 = input.value;
    }
  }

  startEdit() { this.mode = 'edit'; this.cdr.detectChanges(); }
  cancelEdit() {
    if (this.mode === 'create') { this.router.navigate(['/employees']); }
    else { this.mode = 'view'; this.loadEmployee(this.emp.id); }
  }

  validate(): string | null {
    if (!this.emp.department_id) return 'Department is required';
    if (!this.emp.division_id) return 'Division is required';
    if (!this.emp.position_id) return 'Position is required';
    if (!this.emp.joining_date) return 'Start Date is required';
    if (!this.emp.employee_create_type) return 'Employee Create Type is required';
    if (!this.emp.id_number && !this.emp.passport_number) return 'ID Number or Passport Number is required';
    if (this.emp.passport_number && !this.emp.id_number && !this.emp.passport_country) return 'Passport Country is required';
    if (!this.emp.title) return 'Title is required';
    if (!this.emp.surname) return 'Surname is required';
    if (!this.emp.full_name) return 'Full Name is required';
    if (!this.emp.date_of_birth) return 'Date of Birth is required';
    if (!this.emp.gender) return 'Gender is required';
    if (!this.emp.cell_number) return 'Cell Number is required';
    if (this.emp.payslip_pref_email && !this.emp.email_address) return 'Email is required when Email payslip preference is selected';
    if (this.emp.end_date && this.emp.joining_date && this.emp.end_date < this.emp.joining_date) return 'End Date cannot be before Start Date';
    if (this.isTaskGradeEmployee && this.gradeNotches.length > 0) {
      if (!this.emp.current_notch) return 'Notch selection is required for task grade employees';
      if (!this.emp.monthly_salary && this.emp.monthly_salary !== 0) return 'Monthly salary is required for task grade employees';
      if (this.selectedNotch) {
        const sal = Number(this.emp.monthly_salary);
        const min = Number(this.selectedNotch.min_salary);
        const max = Number(this.selectedNotch.max_salary);
        if (isNaN(sal) || sal < min || sal > max) return `Monthly salary must be between R${min.toFixed(2)} and R${max.toFixed(2)} for Notch ${this.selectedNotch.notch_number}`;
      }
    }
    return null;
  }

  save() {
    const err = this.validate();
    if (err) { this.error = err; this.cdr.detectChanges(); return; }
    this.error = '';
    this.saving = true;
    this.cdr.detectChanges();

    const payload = { ...this.emp };
    payload.first_name = payload.full_name || payload.first_name;

    if (this.mode === 'create') {
      this.api.post<any>('/employees', payload).subscribe({
        next: (result) => {
          this.saving = false;
          this.router.navigate(['/employees', result.id]);
        },
        error: (e) => {
          this.error = e?.error?.message || 'Failed to save';
          this.saving = false;
          this.cdr.detectChanges();
        }
      });
    } else {
      this.api.put<any>(`/employees/${this.emp.id}`, payload).subscribe({
        next: () => {
          this.saving = false;
          this.mode = 'view';
          this.loadEmployee(this.emp.id);
        },
        error: (e) => {
          this.error = e?.error?.message || 'Failed to save';
          this.saving = false;
          this.cdr.detectChanges();
        }
      });
    }
  }

  uploadPhoto(event: any) {
    const file = event.target?.files?.[0];
    if (!file || !this.emp.id) return;
    const formData = new FormData();
    formData.append('photo', file);
    this.api.post<any>(`/employees/${this.emp.id}/photo`, formData).subscribe({
      next: (result) => {
        if (result?.photo_url) this.emp.photo_url = result.photo_url;
        this.cdr.detectChanges();
      },
      error: () => { this.error = 'Photo upload failed'; this.cdr.detectChanges(); }
    });
  }

  lookupName(arr: any[], id: any, nameField = 'name'): string {
    if (!id || !arr) return '-';
    const item = arr.find((i: any) => i.id === id);
    return item ? item[nameField] : '-';
  }

  getNopDescription(code: string): string {
    const nop = this.lookups.nature_of_person_codes?.find((n: any) => n.code === code);
    return nop ? `${nop.code} - ${nop.description}` : code || '-';
  }

  switchGroup(group: 'employee' | 'employment' | 'payroll' | 'benefits'): void {
    this.activeGroup = group;
    const firstTabs: Record<string, string> = {
      employee: 'personal',
      employment: 'employment',
      payroll: 'salary-transactions',
      benefits: 'medical-aid'
    };
    const tab = firstTabs[group];
    if (tab === 'salary-transactions') {
      this.switchToSalaryTransactions();
    } else if (tab === 'medical-aid') {
      this.switchToMedicalAid();
    } else {
      this.activeSubTab = tab as any;
      this.cdr.detectChanges();
    }
  }

  switchToSalaryTransactions(): void {
    this.activeGroup = 'payroll';
    this.activeSubTab = 'salary-transactions';
    this.loadSalaryTransactions();
    this.cdr.detectChanges();
  }

  loadSalaryTransactions(): void {
    if (!this.emp.id) return;
    this.salaryTxnsLoading = true;
    this.cdr.detectChanges();
    Promise.all([
      new Promise<any>((resolve) => {
        this.api.get<any>(`/employees/${this.emp.id}/inherited-salary-transactions`).subscribe({
          next: (d) => resolve(d || {}), error: () => resolve({})
        });
      }),
      new Promise<any[]>((resolve) => {
        this.api.get<any[]>(`/employees/${this.emp.id}/salary-transactions`).subscribe({
          next: (d) => resolve(d || []), error: () => resolve([])
        });
      }),
      new Promise<any[]>((resolve) => {
        this.api.get<any[]>('/settings/salary-heads').subscribe({
          next: (d) => resolve(d || []), error: () => resolve([])
        });
      })
    ]).then(([inherited, empTxns, allHeads]) => {
      this.inheritedGroup = inherited;
      this.employeeTxns = empTxns;
      this.allSalaryHeads = allHeads;
      this.buildMergedList();
      this.salaryTxnsLoading = false;
      this.cdr.detectChanges();
    });
  }

  buildMergedList(): void {
    const empHeadIds = new Set(this.employeeTxns.map((t: any) => t.salary_head_id));
    const inherited = (this.inheritedGroup?.items || [])
      .filter((item: any) => !empHeadIds.has(item.salary_head_id))
      .map((item: any) => ({
        ...item,
        source: 'inherited',
        amount: null,
        percentage: null,
        included_in_package: item.included_in_package !== false,
        taxable_pct: item.taxable ? 100 : 0
      }));
    const employee = this.employeeTxns.map((t: any) => ({
      id: t.id,
      salary_head_id: t.salary_head_id,
      code: t.salary_head_code,
      name: t.salary_head_name,
      transaction_type: t.transaction_type,
      calculation_method: t.calculation_method,
      irp5_code: t.irp5_code,
      taxable: t.taxable,
      employer_contribution: t.employer_contribution,
      employee_contribution: t.employee_contribution,
      amount: t.amount,
      percentage: t.percentage,
      included_in_package: t.included_in_package !== false,
      start_date: t.start_date,
      end_date: t.end_date,
      source: 'employee',
      taxable_pct: t.taxable ? 100 : 0
    }));
    const typeOrder: Record<string, number> = { EARNING: 0, DEDUCTION: 1, COMPANY_CONTRIBUTION: 2 };
    this.mergedTxns = [...inherited, ...employee].sort((a, b) => {
      const ta = typeOrder[a.transaction_type] ?? 3;
      const tb = typeOrder[b.transaction_type] ?? 3;
      if (ta !== tb) return ta - tb;
      return (a.salary_head_id || 0) - (b.salary_head_id || 0);
    });
  }

  getTypeLabel(t: string): string {
    const m: Record<string, string> = { EARNING: 'Earnings', DEDUCTION: 'Deductions', COMPANY_CONTRIBUTION: 'Company Contributions' };
    return m[t] || t;
  }

  getTypeColor(t: string): string {
    const m: Record<string, string> = { EARNING: '#22c55e', DEDUCTION: '#ef4444', COMPANY_CONTRIBUTION: '#3b82f6' };
    return m[t] || '#6b7280';
  }

  get groupedTxns(): { type: string, label: string, color: string, items: any[] }[] {
    const groups: { type: string, label: string, color: string, items: any[] }[] = [];
    const typeOrder = ['EARNING', 'DEDUCTION', 'COMPANY_CONTRIBUTION'];
    for (const type of typeOrder) {
      const items = this.mergedTxns.filter(t => t.transaction_type === type);
      if (items.length > 0) {
        groups.push({ type, label: this.getTypeLabel(type), color: this.getTypeColor(type), items });
      }
    }
    return groups;
  }

  openSalaryTxnModal(): void {
    this.editSalaryTxn = { salary_head_id: null };
    this.selectedTxnType = '';
    const empUsedIds = new Set(this.employeeTxns.map((t: any) => t.salary_head_id));
    this.availableSalaryHeads = this.allSalaryHeads.filter(h =>
      !empUsedIds.has(h.id) && h.calculation_method !== 'SYSTEM_CALCULATE'
    );
    this.filteredModalHeads = [];
    this.showSalaryTxnModal = true;
    this.cdr.detectChanges();
  }

  onTxnTypeChange(): void {
    this.editSalaryTxn.salary_head_id = null;
    if (this.selectedTxnType) {
      this.filteredModalHeads = this.availableSalaryHeads.filter(h => h.transaction_type === this.selectedTxnType);
    } else {
      this.filteredModalHeads = [];
    }
    this.cdr.detectChanges();
  }

  onSalaryHeadSelect(): void {
    this.cdr.detectChanges();
  }

  saveSalaryTxn(): void {
    if (!this.editSalaryTxn.salary_head_id) {
      this.ui.toast('error', 'Validation', 'Select a salary transaction');
      return;
    }
    const payload = {
      salary_head_id: this.editSalaryTxn.salary_head_id,
      amount: 0,
      percentage: 0,
      start_date: '1900-01-01',
      end_date: '9999-12-31'
    };
    this.api.post(`/employees/${this.emp.id}/salary-transactions`, payload).subscribe({
      next: () => {
        this.ui.toast('success', 'Added', 'Salary transaction linked');
        this.showSalaryTxnModal = false;
        this.loadSalaryTransactions();
        this.cdr.detectChanges();
      },
      error: (err: any) => {
        const msg = err?.error?.error?.message || err?.error?.error || 'Failed to save';
        this.ui.toast('error', 'Error', msg);
        this.cdr.detectChanges();
      }
    });
  }

  deleteSalaryTxn(item: any): void {
    this.ui.confirm({ title: 'Remove Salary Transaction', message: `Remove "${item.name}" (${item.code}) from this employee?`, danger: true }).then(confirmed => {
      if (confirmed) {
        this.api.delete(`/employees/${this.emp.id}/salary-transactions/${item.id}`).subscribe({
          next: () => {
            this.ui.toast('success', 'Removed', 'Salary transaction removed');
            this.loadSalaryTransactions();
            this.cdr.detectChanges();
          },
          error: () => {
            this.ui.toast('error', 'Error', 'Failed to remove');
            this.cdr.detectChanges();
          }
        });
      }
    });
  }

  getIrp5Label(code: string): string {
    return code || '-';
  }

  switchToMedicalAid(): void {
    if (this.mode === 'create') return;
    this.activeGroup = 'benefits';
    this.activeSubTab = 'medical-aid';
    this.medAidInnerTab = 'scheme';
    this.loadMedicalAid();
    this.cdr.detectChanges();
  }

  loadMedicalAid(): void {
    this.medAidLoading = true;
    this.cdr.detectChanges();
    this.api.get<any[]>('/benefits/medical-aid-schemes').subscribe({
      next: (schemes) => {
        this.medAidSchemes = schemes || [];
        const fundSet = new Set<string>();
        this.medAidSchemes.forEach((s: any) => { if (s.name) fundSet.add(s.name); });
        this.medAidFunds = Array.from(fundSet).sort();
        this.api.get<any[]>(`/benefits/employee/${this.emp.id}/medical-aid`).subscribe({
          next: (data) => {
            this.medAidMemberships = data || [];
            this.currentMembership = this.medAidMemberships.find((m: any) => m.is_current) || this.medAidMemberships[0] || null;
            this.medAidLoading = false;
            this.cdr.detectChanges();
          },
          error: () => { this.medAidLoading = false; this.cdr.detectChanges(); }
        });
      },
      error: () => { this.medAidLoading = false; this.cdr.detectChanges(); }
    });
  }

  openMedAidSchemeModal(mode: 'create' | 'edit', membership?: any): void {
    this.medAidSchemeMode = mode;
    if (mode === 'edit' && membership) {
      const scheme = this.medAidSchemes.find((s: any) => s.id === membership.scheme_id);
      this.selectedFund = scheme ? scheme.name : '';
      this.filteredPlans = this.medAidSchemes.filter((s: any) => s.name === this.selectedFund);
      this.editMedAidScheme = {
        id: membership.id,
        scheme_id: membership.scheme_id,
        membership_number: membership.membership_number || '',
        join_date: membership.join_date ? membership.join_date.split('T')[0] : '',
        termination_date: membership.termination_date ? membership.termination_date.split('T')[0] : '9999-12-31'
      };
    } else {
      this.selectedFund = '';
      this.filteredPlans = [];
      this.editMedAidScheme = {
        scheme_id: null,
        membership_number: '',
        join_date: new Date().toISOString().split('T')[0],
        termination_date: '9999-12-31'
      };
    }
    this.showMedAidSchemeModal = true;
    this.cdr.detectChanges();
  }

  onFundChange(): void {
    this.filteredPlans = this.medAidSchemes.filter((s: any) => s.name === this.selectedFund);
    if (this.filteredPlans.length === 1) {
      this.editMedAidScheme.scheme_id = this.filteredPlans[0].id;
    } else {
      this.editMedAidScheme.scheme_id = null;
    }
    this.cdr.detectChanges();
  }

  saveMedAidScheme(): void {
    if (!this.editMedAidScheme.scheme_id) {
      this.ui.toast('error', 'Validation', 'Please select a medical aid fund and contribution plan');
      return;
    }
    if (!this.editMedAidScheme.join_date) {
      this.ui.toast('error', 'Validation', 'Join date is required');
      return;
    }
    const payload = {
      scheme_id: this.editMedAidScheme.scheme_id,
      membership_number: this.editMedAidScheme.membership_number,
      join_date: this.editMedAidScheme.join_date,
      termination_date: this.editMedAidScheme.termination_date || null
    };
    const obs = this.medAidSchemeMode === 'edit'
      ? this.api.put(`/benefits/employee/${this.emp.id}/medical-aid/${this.editMedAidScheme.id}`, payload)
      : this.api.post(`/benefits/employee/${this.emp.id}/medical-aid`, payload);
    obs.subscribe({
      next: () => {
        this.ui.toast('success', 'Saved', this.medAidSchemeMode === 'edit' ? 'Membership updated' : 'Membership created');
        this.showMedAidSchemeModal = false;
        this.loadMedicalAid();
        this.cdr.detectChanges();
      },
      error: (err: any) => {
        this.ui.toast('error', 'Error', err?.error?.error?.message || 'Failed to save');
        this.cdr.detectChanges();
      }
    });
  }

  deleteMembership(m: any): void {
    this.ui.confirm({ title: 'Delete Membership', message: `Delete membership for "${m.scheme_name}"? This will also remove all dependants and extra transactions linked to it.`, danger: true }).then(ok => {
      if (ok) {
        this.api.delete(`/benefits/employee/${this.emp.id}/medical-aid/${m.id}`).subscribe({
          next: () => { this.ui.toast('success', 'Deleted', 'Membership deleted'); this.loadMedicalAid(); this.cdr.detectChanges(); },
          error: () => { this.ui.toast('error', 'Error', 'Failed to delete'); this.cdr.detectChanges(); }
        });
      }
    });
  }

  selectMembership(m: any): void {
    this.currentMembership = m;
    this.cdr.detectChanges();
  }

  getSchemeNameById(id: number): string {
    const s = this.medAidSchemes.find((x: any) => x.id === id);
    return s ? s.name : '';
  }

  openDependantModal(mode: 'create' | 'edit', dep?: any): void {
    this.dependantMode = mode;
    if (mode === 'edit' && dep) {
      this.editDependant = {
        id: dep.id,
        first_name: dep.first_name,
        surname: dep.surname,
        id_number: dep.id_number || '',
        date_of_birth: dep.date_of_birth ? dep.date_of_birth.split('T')[0] : '',
        gender: dep.gender || '',
        dependant_type: dep.dependant_type,
        employer_contributes: dep.employer_contributes || false,
        start_date: dep.start_date ? dep.start_date.split('T')[0] : '',
        end_date: dep.end_date ? dep.end_date.split('T')[0] : '9999-12-31',
        student_dependant: dep.student_dependant || false,
        disabled_dependant: dep.disabled_dependant || false
      };
    } else {
      this.editDependant = {
        first_name: '', surname: '', id_number: '', date_of_birth: '',
        gender: '', dependant_type: '', employer_contributes: false,
        start_date: new Date().toISOString().split('T')[0], end_date: '9999-12-31',
        student_dependant: false, disabled_dependant: false
      };
    }
    this.showDependantModal = true;
    this.cdr.detectChanges();
  }

  saveDependant(): void {
    if (!this.editDependant.first_name || !this.editDependant.surname) {
      this.ui.toast('error', 'Validation', 'Name and surname are required');
      return;
    }
    if (!this.editDependant.dependant_type) {
      this.ui.toast('error', 'Validation', 'Dependant type is required');
      return;
    }
    if (!this.editDependant.start_date) {
      this.ui.toast('error', 'Validation', 'Start date is required');
      return;
    }
    const mid = this.currentMembership.id;
    const obs = this.dependantMode === 'edit'
      ? this.api.put(`/benefits/employee/${this.emp.id}/medical-aid/${mid}/dependants/${this.editDependant.id}`, this.editDependant)
      : this.api.post(`/benefits/employee/${this.emp.id}/medical-aid/${mid}/dependants`, this.editDependant);
    obs.subscribe({
      next: () => {
        this.ui.toast('success', 'Saved', this.dependantMode === 'edit' ? 'Dependant updated' : 'Dependant added');
        this.showDependantModal = false;
        this.loadMedicalAid();
        this.cdr.detectChanges();
      },
      error: (err: any) => {
        this.ui.toast('error', 'Error', err?.error?.error?.message || 'Failed to save');
        this.cdr.detectChanges();
      }
    });
  }

  deleteDependant(dep: any): void {
    this.ui.confirm({ title: 'Delete Dependant', message: `Delete dependant "${dep.first_name} ${dep.surname}"?`, danger: true }).then(ok => {
      if (ok) {
        this.api.delete(`/benefits/employee/${this.emp.id}/medical-aid/${this.currentMembership.id}/dependants/${dep.id}`).subscribe({
          next: () => { this.ui.toast('success', 'Deleted', 'Dependant removed'); this.loadMedicalAid(); this.cdr.detectChanges(); },
          error: () => { this.ui.toast('error', 'Error', 'Failed to delete'); this.cdr.detectChanges(); }
        });
      }
    });
  }

  openExtraTxnModal(mode: 'create' | 'edit', txn?: any): void {
    this.extraTxnMode = mode;
    if (mode === 'edit' && txn) {
      this.editExtraTxn = {
        id: txn.id,
        contribution_type: txn.contribution_type,
        amount: txn.amount,
        start_date: txn.start_date ? txn.start_date.split('T')[0] : '',
        end_date: txn.end_date ? txn.end_date.split('T')[0] : '9999-12-31',
        employer_contributes: txn.employer_contributes || false
      };
    } else {
      this.editExtraTxn = {
        contribution_type: '', amount: 0,
        start_date: new Date().toISOString().split('T')[0], end_date: '9999-12-31',
        employer_contributes: false
      };
    }
    this.showExtraTxnModal = true;
    this.cdr.detectChanges();
  }

  saveExtraTxn(): void {
    if (!this.editExtraTxn.contribution_type) {
      this.ui.toast('error', 'Validation', 'Contribution type is required');
      return;
    }
    if (!this.editExtraTxn.start_date) {
      this.ui.toast('error', 'Validation', 'Start date is required');
      return;
    }
    const mid = this.currentMembership.id;
    const obs = this.extraTxnMode === 'edit'
      ? this.api.put(`/benefits/employee/${this.emp.id}/medical-aid/${mid}/extra-transactions/${this.editExtraTxn.id}`, this.editExtraTxn)
      : this.api.post(`/benefits/employee/${this.emp.id}/medical-aid/${mid}/extra-transactions`, this.editExtraTxn);
    obs.subscribe({
      next: () => {
        this.ui.toast('success', 'Saved', this.extraTxnMode === 'edit' ? 'Transaction updated' : 'Transaction added');
        this.showExtraTxnModal = false;
        this.loadMedicalAid();
        this.cdr.detectChanges();
      },
      error: (err: any) => {
        this.ui.toast('error', 'Error', err?.error?.error?.message || 'Failed to save');
        this.cdr.detectChanges();
      }
    });
  }

  deleteExtraTxn(txn: any): void {
    const typeLabels: Record<string, string> = { LATE_JOINER_FEE: 'Late Joiner Fee', ARREAR_CONTRIBUTION: 'Arrear Contribution', OTHER: 'Other' };
    this.ui.confirm({ title: 'Delete Transaction', message: `Delete "${typeLabels[txn.contribution_type] || txn.contribution_type}" transaction?`, danger: true }).then(ok => {
      if (ok) {
        this.api.delete(`/benefits/employee/${this.emp.id}/medical-aid/${this.currentMembership.id}/extra-transactions/${txn.id}`).subscribe({
          next: () => { this.ui.toast('success', 'Deleted', 'Transaction removed'); this.loadMedicalAid(); this.cdr.detectChanges(); },
          error: () => { this.ui.toast('error', 'Error', 'Failed to delete'); this.cdr.detectChanges(); }
        });
      }
    });
  }

  formatContributionType(type: string): string {
    const labels: Record<string, string> = { LATE_JOINER_FEE: 'Late Joiner Fee', ARREAR_CONTRIBUTION: 'Arrear Contribution', OTHER: 'Other' };
    return labels[type] || type;
  }

  formatDependantType(type: string): string {
    const labels: Record<string, string> = { ADULT: 'Adult Dependant', CHILD: 'Child Dependant', SPOUSE: 'Spouse', STUDENT: 'Student', DISABLED: 'Disabled' };
    return labels[type] || type;
  }

  switchToRetirementFunds(): void {
    this.activeGroup = 'benefits';
    this.activeSubTab = 'retirement-funds';
    this.retInnerTab = 'pension';
    this.editRetFund = {
      fund_type_id: '', vendor_id: '', fund_number: '', plan_name: '',
      join_date: this.todayStr, termination_date: '9999-12-31',
      is_private: false, is_current: false,
      employee_amount: 0, employer_amount: 0
    };
    this.retPlansForSelectedAdmin = [];
    this.loadRetirementFunds();
  }

  loadRetirementFunds(): void {
    this.retFundsLoading = true;
    this.api.get<any>('/benefits/ems-vendors').subscribe({
      next: (d) => { this.emsVendors = d || []; this.cdr.detectChanges(); },
      error: () => { this.emsVendors = []; }
    });
    this.api.get<any>('/benefits/retirement-funds').subscribe({
      next: (funds) => {
        this.retFundTypes = funds || [];
        this.cdr.detectChanges();
        this.api.get<any>(`/benefits/employee/${this.emp.id}/retirement-funds`).subscribe({
          next: (data) => {
            const all = data || [];
            this.retPensionFunds = all.filter((f: any) => f.fund_type === 'PENSION');
            this.retProvidentFunds = all.filter((f: any) => f.fund_type === 'PROVIDENT');
            this.retAnnuityFunds = all.filter((f: any) => f.fund_type === 'RETIREMENT_ANNUITY');
            this.retFundsLoading = false;
            this.cdr.detectChanges();
          },
          error: () => { this.retFundsLoading = false; this.cdr.detectChanges(); }
        });
      },
      error: () => { this.retFundsLoading = false; this.cdr.detectChanges(); }
    });
  }

  get retFundsForCurrentTab(): any[] {
    if (this.retInnerTab === 'pension') return this.retPensionFunds;
    if (this.retInnerTab === 'provident') return this.retProvidentFunds;
    return this.retAnnuityFunds;
  }

  get retFundTypesForCurrentTab(): any[] {
    const typeMap: Record<string, string> = { pension: 'PENSION', provident: 'PROVIDENT', retirement: 'RETIREMENT_ANNUITY' };
    const ft = typeMap[this.retInnerTab];
    return this.retFundTypes.filter((f: any) => f.fund_type === ft);
  }

  emsVendorName(vendorId: any): string {
    if (!vendorId) return '-';
    const v = this.emsVendors.find(v => v.id === vendorId || v.id === parseInt(vendorId));
    return v ? v.name : `Vendor #${vendorId}`;
  }

  get retAdminsForCurrentTab(): any[] {
    const funds = this.retFundTypesForCurrentTab;
    const seen = new Map<number, string>();
    for (const f of funds) {
      if (f.vendor_id && !seen.has(f.vendor_id)) {
        seen.set(f.vendor_id, this.emsVendorName(f.vendor_id));
      }
    }
    return Array.from(seen.entries()).map(([vendor_id, vendor_name]) => ({ vendor_id, vendor_name }));
  }

  retPlansForSelectedAdmin: any[] = [];

  unionLoading = false;
  availableUnions: any[] = [];
  employeeUnions: any[] = [];
  editUnion: any = { trade_union_id: '', join_date: '', termination_date: '9999-12-31' };
  editingUnionId: number | null = null;

  onRetFundAdminChange(): void {
    const vid = this.editRetFund.vendor_id ? parseInt(this.editRetFund.vendor_id) : null;
    this.retPlansForSelectedAdmin = vid
      ? this.retFundTypesForCurrentTab.filter((f: any) => f.vendor_id === vid)
      : [];
    this.editRetFund.fund_type_id = '';
    this.editRetFund.plan_name = '';
    this.cdr.detectChanges();
  }

  onRetFundPlanChange(): void {
    const fid = this.editRetFund.fund_type_id ? parseInt(this.editRetFund.fund_type_id) : null;
    if (fid) {
      const fund = this.retFundTypes.find((f: any) => f.id === fid);
      if (fund) {
        this.editRetFund.plan_name = fund.plan_name || fund.name;
      }
    }
    this.cdr.detectChanges();
  }

  openRetFundModal(mode: 'create' | 'edit', fund?: any): void {
    this.retFundMode = mode;
    if (mode === 'edit' && fund) {
      this.editRetFund = { ...fund, fund_type_id: String(fund.fund_type_id), vendor_id: fund.vendor_id ? String(fund.vendor_id) : '' };
      this.onRetFundAdminChange();
      this.editRetFund.fund_type_id = String(fund.fund_type_id);
    } else {
      this.editRetFund = {
        fund_type_id: '', vendor_id: '', fund_number: '', plan_name: '',
        join_date: this.todayStr, termination_date: '9999-12-31',
        is_private: false, is_current: false,
        employee_amount: 0, employer_amount: 0
      };
      this.retPlansForSelectedAdmin = [];
    }
    this.showRetFundModal = true;
    this.cdr.detectChanges();
  }

  saveRetFund(): void {
    if (!this.editRetFund.fund_type_id) { this.ui.toast('error', 'Validation', 'Please select a fund'); return; }
    const payload = {
      fund_type_id: parseInt(this.editRetFund.fund_type_id),
      fund_number: this.editRetFund.fund_number || null,
      plan_name: this.editRetFund.plan_name || null,
      join_date: this.editRetFund.join_date,
      termination_date: this.editRetFund.termination_date || '9999-12-31',
      is_private: this.editRetFund.is_private || false,
      is_current: this.editRetFund.is_current || false,
      employee_amount: parseFloat(this.editRetFund.employee_amount) || 0,
      employer_amount: parseFloat(this.editRetFund.employer_amount) || 0,
    };
    const obs = this.retFundMode === 'edit'
      ? this.api.put(`/benefits/employee/${this.emp.id}/retirement-funds/${this.editRetFund.id}`, payload)
      : this.api.post(`/benefits/employee/${this.emp.id}/retirement-funds`, payload);
    obs.subscribe({
      next: () => {
        this.ui.toast('success', 'Saved', this.retFundMode === 'edit' ? 'Fund updated' : 'Fund linked');
        this.showRetFundModal = false;
        this.loadRetirementFunds();
      },
      error: (err: any) => this.ui.toast('error', 'Error', err?.error?.error?.message || 'Failed to save')
    });
  }

  deleteRetFund(fund: any): void {
    if (!confirm('Delete this fund membership?')) return;
    this.api.delete(`/benefits/employee/${this.emp.id}/retirement-funds/${fund.id}`).subscribe({
      next: () => {
        this.ui.toast('success', 'Deleted', 'Fund membership removed');
        this.loadRetirementFunds();
      },
      error: () => this.ui.toast('error', 'Error', 'Failed to delete')
    });
  }

  retFundStatus(fund: any): string {
    if (!fund.termination_date) return 'Active';
    const term = String(fund.termination_date).split('T')[0];
    if (term >= '9999-01-01') return 'Active';
    if (term < this.todayStr) return 'Terminated';
    return 'Active';
  }

  switchToUnions(): void {
    this.activeGroup = 'benefits';
    this.activeSubTab = 'unions';
    this.editUnion = { trade_union_id: '', join_date: this.todayStr, termination_date: '9999-12-31' };
    this.loadUnions();
  }

  loadUnions(): void {
    if (!this.emp.id) return;
    this.unionLoading = true;
    this.cdr.detectChanges();
    this.api.get<any[]>('/trade-unions').subscribe({
      next: (unions) => {
        this.availableUnions = (unions || []).filter((u: any) => u.enabled !== false);
        this.api.get<any[]>(`/benefits/employee/${this.emp.id}/unions`).subscribe({
          next: (data) => {
            this.employeeUnions = data || [];
            this.unionLoading = false;
            this.cdr.detectChanges();
          },
          error: () => { this.unionLoading = false; this.cdr.detectChanges(); }
        });
      },
      error: () => { this.unionLoading = false; this.cdr.detectChanges(); }
    });
  }

  saveUnion(): void {
    if (!this.editUnion.trade_union_id) { this.ui.toast('error', 'Validation', 'Please select a union'); return; }
    if (!this.editUnion.join_date) { this.ui.toast('error', 'Validation', 'Join date is required'); return; }
    const payload = {
      trade_union_id: parseInt(this.editUnion.trade_union_id),
      join_date: this.editUnion.join_date,
      termination_date: this.editUnion.termination_date || '9999-12-31',
    };
    if (this.editingUnionId) {
      this.api.put(`/benefits/employee/${this.emp.id}/unions/${this.editingUnionId}`, payload).subscribe({
        next: () => {
          this.ui.toast('success', 'Updated', 'Union membership updated');
          this.cancelUnionEdit();
          this.loadUnions();
        },
        error: (err: any) => this.ui.toast('error', 'Error', err?.error?.error?.message || 'Failed to update')
      });
    } else {
      this.api.post(`/benefits/employee/${this.emp.id}/unions`, payload).subscribe({
        next: () => {
          this.ui.toast('success', 'Saved', 'Union membership added');
          this.cancelUnionEdit();
          this.loadUnions();
        },
        error: (err: any) => this.ui.toast('error', 'Error', err?.error?.error?.message || 'Failed to save')
      });
    }
  }

  startEditUnion(um: any): void {
    this.editingUnionId = um.id;
    this.editUnion = {
      trade_union_id: String(um.trade_union_id),
      join_date: String(um.join_date).split('T')[0],
      termination_date: String(um.termination_date || '9999-12-31').split('T')[0],
    };
    this.cdr.detectChanges();
  }

  cancelUnionEdit(): void {
    this.editingUnionId = null;
    this.editUnion = { trade_union_id: '', join_date: this.todayStr, termination_date: '9999-12-31' };
    this.cdr.detectChanges();
  }

  deleteUnion(membership: any): void {
    if (!confirm('Delete this union membership?')) return;
    this.api.delete(`/benefits/employee/${this.emp.id}/unions/${membership.id}`).subscribe({
      next: () => {
        this.ui.toast('success', 'Deleted', 'Union membership removed');
        this.loadUnions();
      },
      error: () => this.ui.toast('error', 'Error', 'Failed to delete')
    });
  }

  unionStatus(membership: any): string {
    if (!membership.termination_date) return 'Active';
    const term = String(membership.termination_date).split('T')[0];
    if (term >= '9999-01-01') return 'Active';
    if (term < this.todayStr) return 'Terminated';
    return 'Active';
  }

  formatDate(d: string): string {
    if (!d) return '-';
    const s = d.split('T')[0];
    const parts = s.split('-');
    if (parts.length === 3) return `${parts[2]}/${parts[1]}/${parts[0]}`;
    return s;
  }
}
