import { Routes } from '@angular/router';
import { UnsavedChangesGuard } from './core/unsaved-changes.guard';
import { authGuard } from './core/auth.guard';

export const routes: Routes = [
  {
    path: 'login',
    loadComponent: () => import('./features/auth/login.component').then(m => m.LoginComponent)
  },
  {
    path: '',
    loadComponent: () => import('./layout/shell.component').then(m => m.ShellComponent),
    canActivate: [authGuard],
    children: [
      { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'dashboard', loadComponent: () => import('./features/dashboard/dashboard.component').then(m => m.DashboardComponent) },
      { path: 'assets', loadComponent: () => import('./features/assets/asset-list/asset-list.component').then(m => m.AssetListComponent) },
      { path: 'acquisitions', loadComponent: () => import('./features/acquisitions/acquisitions.component').then(m => m.AcquisitionsComponent) },
      { path: 'assets/:id', loadComponent: () => import('./features/assets/asset-detail/asset-detail.component').then(m => m.AssetDetailComponent) },
      { path: 'wip', loadComponent: () => import('./features/wip/wip-list.component').then(m => m.WipListComponent) },
      { path: 'wip/unbundling', loadComponent: () => import('./features/wip/wip-unbundling/wip-unbundling.component').then(m => m.WipUnbundlingComponent) },
      { path: 'wip/unbundling/:id', loadComponent: () => import('./features/wip/wip-unbundling/wip-unbundling-detail.component').then(m => m.WipUnbundlingDetailComponent) },
      { path: 'wip/:id', loadComponent: () => import('./features/wip/wip-detail/wip-detail.component').then(m => m.WipDetailComponent) },
      { path: 'maintenance', redirectTo: 'maintenance/requests', pathMatch: 'full' },
      { path: 'maintenance/requests', loadComponent: () => import('./features/maintenance/maintenance-request-list/maintenance-request-list.component').then(m => m.MaintenanceRequestListComponent) },
      { path: 'maintenance/requests/:id', loadComponent: () => import('./features/maintenance/maintenance-request-detail/maintenance-request-detail.component').then(m => m.MaintenanceRequestDetailComponent) },
      { path: 'fleet', loadComponent: () => import('./features/fleet/fleet/fleet.component').then(m => m.FleetComponent) },
      { path: 'verification', loadComponent: () => import('./features/verification/verification-landing.component').then(m => m.VerificationLandingComponent) },
      { path: 'verification/register', loadComponent: () => import('./features/verification/register-list/register-list.component').then(m => m.RegisterListComponent) },
      { path: 'verification/register/create', loadComponent: () => import('./features/verification/register-create/register-create.component').then(m => m.RegisterCreateComponent) },
      { path: 'verification/register/:id', loadComponent: () => import('./features/verification/register-detail/register-detail.component').then(m => m.RegisterDetailComponent) },
      { path: 'verification/planning', loadComponent: () => import('./features/verification/plan-list/plan-list.component').then(m => m.PlanListComponent) },
      { path: 'verification/planning/create', loadComponent: () => import('./features/verification/plan-create/plan-create.component').then(m => m.PlanCreateComponent) },
      { path: 'verification/planning/:id', loadComponent: () => import('./features/verification/plan-detail/plan-detail.component').then(m => m.PlanDetailComponent), canDeactivate: [UnsavedChangesGuard] },
      { path: 'verification/reports', loadComponent: () => import('./features/verification/verification-reports/verification-reports.component').then(m => m.VerificationReportsComponent) },
      { path: 'transactions', loadComponent: () => import('./features/transactions/transactions/transactions.component').then(m => m.TransactionsComponent) },
      { path: 'prior-year-adjustments', loadComponent: () => import('./features/prior-year-adjustments/prior-year-adjustments.component').then(m => m.PriorYearAdjustmentsComponent) },
      { path: 'workflows', loadComponent: () => import('./features/workflows/workflow-inbox/workflow-inbox.component').then(m => m.WorkflowInboxComponent) },
      { path: 'reports', loadComponent: () => import('./features/reports/reports/reports.component').then(m => m.ReportsComponent) },
      { path: 'reconciliation', loadComponent: () => import('./features/reconciliation/reconciliation.component').then(m => m.ReconciliationComponent) },
      { path: 'config', loadComponent: () => import('./features/config-landing/config-landing.component').then(m => m.ConfigLandingComponent) },
      { path: 'bulk-upload', loadComponent: () => import('./features/bulk-upload/bulk-upload.component').then(m => m.BulkUploadComponent), children: [
        { path: '', redirectTo: 'jobs', pathMatch: 'full' },
        { path: 'jobs', loadComponent: () => import('./features/admin/upload-jobs/upload-jobs.component').then(m => m.UploadJobsComponent) },
        { path: 'jobs/:id/errors', loadComponent: () => import('./features/admin/upload-errors/upload-errors.component').then(m => m.UploadErrorsComponent) },
        { path: 'wip-transfers', loadComponent: () => import('./features/bulk-upload/wip-transfers/wip-transfers.component').then(m => m.WipTransfersComponent) },
        { path: 'items', loadComponent: () => import('./features/admin/uploaded-items/uploaded-items.component').then(m => m.UploadedItemsComponent) },
        { path: 'wip-approvals', loadComponent: () => import('./features/bulk-upload/wip-transfer-approvals/wip-transfer-approvals.component').then(m => m.WipTransferApprovalsComponent) },
        { path: 'bulk-transactions', loadComponent: () => import('./features/bulk-upload/bulk-transactions/bulk-transactions.component').then(m => m.BulkTransactionsComponent) },
        { path: 'bulk-transaction-approvals', loadComponent: () => import('./features/bulk-upload/bulk-transaction-approvals/bulk-transaction-approvals.component').then(m => m.BulkTransactionApprovalsComponent) },
      ]},
      { path: 'admin', loadComponent: () => import('./features/admin/admin/admin.component').then(m => m.AdminComponent) },
      { path: 'config/asset-types', loadComponent: () => import('./features/admin/config/asset-types/asset-types.component').then(m => m.AssetTypesComponent) },
      { path: 'config/asset-statuses', loadComponent: () => import('./features/admin/config/asset-statuses/asset-statuses.component').then(m => m.AssetStatusesComponent) },
      { path: 'config/asset-categories', loadComponent: () => import('./features/admin/config/asset-categories/asset-categories.component').then(m => m.AssetCategoriesComponent) },
      { path: 'config/asset-sub-categories', loadComponent: () => import('./features/admin/config/asset-sub-categories/asset-sub-categories.component').then(m => m.AssetSubCategoriesComponent) },
      { path: 'config/asset-classes', loadComponent: () => import('./features/admin/config/asset-classes/asset-classes.component').then(m => m.AssetClassesComponent) },
      { path: 'config/measurement-types', loadComponent: () => import('./features/admin/config/measurement-types/measurement-types.component').then(m => m.MeasurementTypesComponent) },
      { path: 'config/criticality-grades', loadComponent: () => import('./features/admin/config/criticality-grades/criticality-grades.component').then(m => m.CriticalityGradesComponent) },
      { path: 'config/health-grades', loadComponent: () => import('./features/admin/config/health-grades/health-grades.component').then(m => m.HealthGradesComponent) },
      { path: 'config/performance-grades', loadComponent: () => import('./features/admin/config/performance-grades/performance-grades.component').then(m => m.PerformanceGradesComponent) },
      { path: 'config/utilisation-grades', loadComponent: () => import('./features/admin/config/utilisation-grades/utilisation-grades.component').then(m => m.UtilisationGradesComponent) },
      { path: 'config/cidms-hierarchy', loadComponent: () => import('./features/admin/config/cidms-hierarchy/cidms-hierarchy.component').then(m => m.CidmsHierarchyComponent) },
      { path: 'config/cidms-accounting-groups', loadComponent: () => import('./features/admin/config/cidms-accounting-groups/cidms-accounting-groups.component').then(m => m.CidmsAccountingGroupsComponent) },
      { path: 'config/cidms-accounting-sub-groups', loadComponent: () => import('./features/admin/config/cidms-accounting-sub-groups/cidms-accounting-sub-groups.component').then(m => m.CidmsAccountingSubGroupsComponent) },
      { path: 'config/cidms-municipal-services', loadComponent: () => import('./features/admin/config/cidms-municipal-services/cidms-municipal-services.component').then(m => m.CidmsMunicipalServicesComponent) },
      { path: 'config/cidms-classes', loadComponent: () => import('./features/admin/config/cidms-classes/cidms-classes.component').then(m => m.CidmsClassesComponent) },
      { path: 'config/cidms-group-types', loadComponent: () => import('./features/admin/config/cidms-group-types/cidms-group-types.component').then(m => m.CidmsGroupTypesComponent) },
      { path: 'config/cidms-asset-types', loadComponent: () => import('./features/admin/config/cidms-asset-types/cidms-asset-types.component').then(m => m.CidmsAssetTypesComponent) },
      { path: 'config/cidms-component-types', loadComponent: () => import('./features/admin/config/cidms-component-types/cidms-component-types.component').then(m => m.CidmsComponentTypesComponent) },
      { path: 'config/cidms-sub-component-types', loadComponent: () => import('./features/admin/config/cidms-sub-component-types/cidms-sub-component-types.component').then(m => m.CidmsSubComponentTypesComponent) },
      { path: 'config/asset-project-statuses', loadComponent: () => import('./features/admin/config/asset-project-statuses/asset-project-statuses.component').then(m => m.AssetProjectStatusesComponent) },
      { path: 'config/asset-conditions', loadComponent: () => import('./features/admin/config/asset-conditions/asset-conditions.component').then(m => m.AssetConditionsComponent) },
      { path: 'config/component-types', loadComponent: () => import('./features/admin/config/component-types/component-types.component').then(m => m.ComponentTypesComponent) },
      { path: 'config/transaction-types', loadComponent: () => import('./features/admin/config/transaction-types/transaction-types.component').then(m => m.TransactionTypesComponent) },
      { path: 'config/mscoa', loadComponent: () => import('./features/admin/config/mscoa/mscoa-config.component').then(m => m.MscoaConfigComponent) },
      { path: 'config/service-groups', loadComponent: () => import('./features/admin/config/service-groups/service-groups.component').then(m => m.ServiceGroupsComponent) },
      { path: 'config/lead-times', loadComponent: () => import('./features/admin/config/lead-times/lead-times.component').then(m => m.LeadTimesComponent) },
      { path: 'admin/upload-jobs', redirectTo: 'bulk-upload/jobs', pathMatch: 'full' },
      { path: 'admin/uploaded-items', redirectTo: 'bulk-upload/items', pathMatch: 'full' },
      { path: 'scm', loadComponent: () => import('./features/scm/dashboard/scm-dashboard.component').then(m => m.ScmDashboardComponent) },
      { path: 'scm/**', loadComponent: () => import('./features/scm/dashboard/scm-dashboard.component').then(m => m.ScmDashboardComponent) },
      { path: 'pos-view', loadComponent: () => import('./features/pos/pos-view.component').then(m => m.PosViewComponent) },
      { path: 'pos-view/**', loadComponent: () => import('./features/pos/pos-view.component').then(m => m.PosViewComponent) },
      { path: 'payroll-view', loadComponent: () => import('./features/payroll/payroll-view.component').then(m => m.PayrollViewComponent) },
      { path: 'payroll-view/**', loadComponent: () => import('./features/payroll/payroll-view.component').then(m => m.PayrollViewComponent) },
      { path: 'idp-view', loadComponent: () => import('./features/idp/idp-view.component').then(m => m.IdpViewComponent) },
      { path: 'idp-view/**', loadComponent: () => import('./features/idp/idp-view.component').then(m => m.IdpViewComponent) },
      { path: 'insights-view', loadComponent: () => import('./features/insights/insights-view.component').then(m => m.InsightsViewComponent) },
      { path: 'insights-view/**', loadComponent: () => import('./features/insights/insights-view.component').then(m => m.InsightsViewComponent) },
      { path: 'budget-view', loadComponent: () => import('./features/budget/budget-view.component').then(m => m.BudgetViewComponent) },
      { path: 'budget-view/**', loadComponent: () => import('./features/budget/budget-view.component').then(m => m.BudgetViewComponent) },
      { path: 'afs-view', loadComponent: () => import('./features/afs/afs-view.component').then(m => m.AfsViewComponent) },
      { path: 'afs-view/**', loadComponent: () => import('./features/afs/afs-view.component').then(m => m.AfsViewComponent) },
    ]
  },
  { path: '**', redirectTo: 'login' }
];
