namespace PlatinumAFS.Api.Models;

public class GeneralLedgerEntry
{
    public int GenLedgerId { get; set; }
    public DateTime PostingDate { get; set; }
    public int ProcessingMonth { get; set; }
    public string FinYear { get; set; } = string.Empty;
    public int? TransactionTypeID { get; set; }
    public string? TransactionType { get; set; }
    public string? TransactionDetails { get; set; }
    public string? DocumentNumber { get; set; }
    public string? DocumentType { get; set; }
    public decimal? Debit { get; set; }
    public decimal? Credit { get; set; }
    public decimal? Balance { get; set; }
    public DateTime? DateCaptured { get; set; }
    public int? CapturerID { get; set; }
    public string? CapturedBy { get; set; }
    public int? DivisionID { get; set; }
    public string? Department { get; set; }
    public string? Division { get; set; }
    public int? ProjectID { get; set; }
    public string? ProjectCode { get; set; }
    public string? ProjectDescription { get; set; }
    public int? PlanProjectItemID { get; set; }
    public string? UKey { get; set; }
    public string? ItemType { get; set; }
    public string? OrderDescription { get; set; }
    public decimal? VATRate { get; set; }
    public string? VATIndicator { get; set; }
    public Guid? MatchTranGuid { get; set; }
    public string? ReferenceNumber { get; set; }
    public string? SupplierNo { get; set; }
    public string? SupplierName { get; set; }
    public string? OrderNumber { get; set; }
    public string? OrderLine { get; set; }
    public string? VendorInvoiceNumber { get; set; }
    public string? PaymentDocumentNumber { get; set; }
    public int? VoteID { get; set; }
    public string? VoteNumber { get; set; }
    public string? VoteDescription { get; set; }
    public string? AccountNo { get; set; }
    public int? SCOAItemID { get; set; }
    public string? ScoaItemCode { get; set; }
    public string? ScoaItemShortDesc { get; set; }
    public string? ScoaItemDescription { get; set; }
    public string? ReportingLevel1 { get; set; }
    public string? ReportingLevel2 { get; set; }
    public string? ReportingLevel3 { get; set; }
    public string? ReportingLevel4 { get; set; }
    public string? ReportingLevel5 { get; set; }
    public string? ReportingLevel6 { get; set; }
    public string? ReportingLevel7 { get; set; }
    public string? ReportingLevel8 { get; set; }
    public string? ReportingLevel9 { get; set; }
    public string? ReportingLevel10 { get; set; }
    public string? ReportingLevel11 { get; set; }
    public string? ReportingLevel12 { get; set; }
    public int? SCOAFundsID { get; set; }
    public string? ScoaFundsCode { get; set; }
    public string? ScoaFundsShortDesc { get; set; }
    public string? ScoaFundsDescription { get; set; }
    public int? SCOAFunctionID { get; set; }
    public string? ScoaFunctionCode { get; set; }
    public string? ScoaFunctionShortDesc { get; set; }
    public string? ScoaFunctionDescription { get; set; }
    public int? SCOAProjectID { get; set; }
    public string? ScoaProjectCode { get; set; }
    public string? ScoaProjectShortDesc { get; set; }
    public string? ScoaProjectDescription { get; set; }
    public int? SCOACostingID { get; set; }
    public string? ScoaCostingCode { get; set; }
    public string? ScoaCostingShortDesc { get; set; }
    public string? ScoaCostingDescription { get; set; }
    public int? SCOARegionID { get; set; }
    public string? ScoaRegionCode { get; set; }
    public string? ScoaRegionShortDesc { get; set; }
    public string? ScoaRegionDescription { get; set; }
}
