// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatinumOvertime_API.Data;

#nullable disable

namespace PlatinumOvertime_API.Data.Migrations.SqlServer
{
    [DbContext(typeof(OvertimeDbContextSqlServer))]
    [Migration("20260421134358_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.OvertimeAuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("OvertimeAuditTrail", (string)null);
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.OvertimeConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowOvertimeMultipleApproval")
                        .HasColumnType("bit");

                    b.Property<int>("CountingPeriodEndDay")
                        .HasColumnType("int");

                    b.Property<int>("CountingPeriodStartDay")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExceptionalMaximumOvertimeHours")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("MaximumMonthlyOvertimeHours")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("SingletonLock")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasDefaultValue("X");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SingletonLock")
                        .IsUnique();

                    b.ToTable("OvertimeConfig", (string)null);
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.OvertimeTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapturedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("OvertimeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("EmployeeId", "OvertimeDate");

                    b.ToTable("OvertimeTransaction", (string)null);
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.OvertimeTransactionDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OvertimeTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OvertimeTransactionId");

                    b.ToTable("OvertimeTransactionDocument", (string)null);
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.OvertimeWorkflowState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActionedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("OvertimeTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OvertimeTransactionId");

                    b.ToTable("OvertimeWorkflowState", (string)null);
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.PositionApprovalConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDepartmentExcessOvertimeApprover")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOvertimeApprover")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOvertimeRecommender")
                        .HasColumnType("bit");

                    b.Property<string>("PositionDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PositionId")
                        .IsUnique();

                    b.ToTable("PositionApprovalConfig", (string)null);
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.PositionReportingRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PositionApprovalConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReportsToPositionDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReportsToPositionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PositionApprovalConfigId");

                    b.ToTable("PositionReportingRelationship", (string)null);
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.TemporaryActingAppointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActingEmployeeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ActingEmployeeName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ActingInPositionDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ActingInPositionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PositionApprovalConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PositionApprovalConfigId");

                    b.ToTable("TemporaryActingAppointment", (string)null);
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.OvertimeTransactionDocument", b =>
                {
                    b.HasOne("PlatinumOvertime_API.Models.Domain.OvertimeTransaction", "OvertimeTransaction")
                        .WithMany("Documents")
                        .HasForeignKey("OvertimeTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OvertimeTransaction");
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.OvertimeWorkflowState", b =>
                {
                    b.HasOne("PlatinumOvertime_API.Models.Domain.OvertimeTransaction", "OvertimeTransaction")
                        .WithMany("WorkflowHistory")
                        .HasForeignKey("OvertimeTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OvertimeTransaction");
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.PositionReportingRelationship", b =>
                {
                    b.HasOne("PlatinumOvertime_API.Models.Domain.PositionApprovalConfig", "PositionApprovalConfig")
                        .WithMany("ReportingRelationships")
                        .HasForeignKey("PositionApprovalConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PositionApprovalConfig");
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.TemporaryActingAppointment", b =>
                {
                    b.HasOne("PlatinumOvertime_API.Models.Domain.PositionApprovalConfig", "PositionApprovalConfig")
                        .WithMany("ActingAppointments")
                        .HasForeignKey("PositionApprovalConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PositionApprovalConfig");
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.OvertimeTransaction", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("WorkflowHistory");
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.PositionApprovalConfig", b =>
                {
                    b.Navigation("ActingAppointments");

                    b.Navigation("ReportingRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
