// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatinumOvertime_API.Data;

#nullable disable

namespace PlatinumOvertime_API.Data.Migrations.SqlServer
{
    [DbContext(typeof(OvertimeDbContextSqlServer))]
    [Migration("20260423201808_AddOvertimeCaptureFields")]
    partial class AddOvertimeCaptureFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.ConstMOC", b =>
                {
                    b.Property<int>("MOCId")
                        .HasColumnType("int")
                        .HasColumnName("MOC_ID");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("Enabled");

                    b.Property<decimal?>("EndDate")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("EndDate");

                    b.Property<int>("SalaryHeadId")
                        .HasColumnType("int")
                        .HasColumnName("SalaryHeadID");

                    b.Property<decimal?>("StartDate")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("StartDate");

                    b.HasKey("MOCId");

                    b.ToTable("Const_MOC", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.ConstMOCDetail", b =>
                {
                    b.Property<int>("MOCDetailId")
                        .HasColumnType("int")
                        .HasColumnName("MOCDetail_ID");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("Enabled");

                    b.Property<decimal?>("EndDate")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("EndDate");

                    b.Property<string>("Formula")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Formula");

                    b.Property<int>("MOCId")
                        .HasColumnType("int")
                        .HasColumnName("MOCID");

                    b.Property<decimal?>("StartDate")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("StartDate");

                    b.HasKey("MOCDetailId");

                    b.ToTable("Const_MOCDetail", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.OvertimeAuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("OvertimeAuditTrail", (string)null);
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.OvertimeConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowOvertimeMultipleApproval")
                        .HasColumnType("bit");

                    b.Property<int>("CountingPeriodEndDay")
                        .HasColumnType("int");

                    b.Property<int>("CountingPeriodStartDay")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExceptionalMaximumOvertimeHours")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("MaximumMonthlyOvertimeHours")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("SingletonLock")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasDefaultValue("X");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SingletonLock")
                        .IsUnique();

                    b.ToTable("OvertimeConfig", (string)null);
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.OvertimeTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApproverEmployeeId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ApproverEmployeeName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CapturedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentAssigneeUserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("ExcessApproverEmployeeId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ExcessApproverEmployeeName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FormulaSnapshot")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("HoursAlreadyCapturedThisMonth")
                        .HasColumnType("decimal(8,2)");

                    b.Property<bool>("IsExcess")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OvertimeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayrollApproverEmployeeId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PayrollApproverEmployeeName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PayrollCapturerEmployeeId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PayrollCapturerEmployeeName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RecommenderEmployeeId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RecommenderEmployeeName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("SalaryHeadId")
                        .HasColumnType("int");

                    b.Property<string>("SalaryHeadName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAssigneeUserId");

                    b.HasIndex("Status");

                    b.HasIndex("EmployeeId", "OvertimeDate");

                    b.ToTable("OvertimeTransaction", (string)null);
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.OvertimeTransactionDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OvertimeTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OvertimeTransactionId");

                    b.ToTable("OvertimeTransactionDocument", (string)null);
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.OvertimeWorkflowState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActionedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("OvertimeTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OvertimeTransactionId");

                    b.ToTable("OvertimeWorkflowState", (string)null);
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.PayrollEmployee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("Employee_ID");

                    b.Property<bool?>("AllowOverTime")
                        .HasColumnType("bit")
                        .HasColumnName("AllowOverTime");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("EmpCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("EmpCode");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("Enabled");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FirstName");

                    b.Property<string>("IdNo")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("IdNo");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("JoiningDate");

                    b.Property<string>("KnownAsName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("KnownAsName");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("PassportNumber");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("PositionID");

                    b.Property<decimal?>("PrevSalary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrevSalary");

                    b.Property<decimal?>("RpdOther")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("RPD_Other");

                    b.Property<string>("SecondName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SecondName");

                    b.Property<string>("Surname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Surname");

                    b.Property<decimal?>("WhpdOther")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("WHPD_Other");

                    b.Property<decimal?>("WhpmMonthly")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("WHPM_Monthly");

                    b.HasKey("EmployeeId");

                    b.ToTable("Payroll_Employee", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.PayrollEmployeePayrollDefinition", b =>
                {
                    b.Property<int>("EmployeePayrollDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeePayrollDefinition_ID");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("Enabled");

                    b.Property<int>("PayrollSalaryHeadId")
                        .HasColumnType("int")
                        .HasColumnName("PayrollSalaryHeadID");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("Percentage");

                    b.HasKey("EmployeePayrollDefinitionId");

                    b.HasIndex("EmployeeId", "PayrollSalaryHeadId");

                    b.ToTable("Payroll_EmployeePayrollDefinition", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.PayrollIRP5Code", b =>
                {
                    b.Property<int>("IRP5CodeId")
                        .HasColumnType("int")
                        .HasColumnName("IRP5Code_ID");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("Enabled");

                    b.Property<int?>("IRP5Code")
                        .HasColumnType("int")
                        .HasColumnName("IRP5Code");

                    b.Property<string>("IRP5CodeDesc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("IRP5CodeDesc");

                    b.Property<int?>("TransactionTypeId")
                        .HasColumnType("int")
                        .HasColumnName("TransactionTypeID");

                    b.HasKey("IRP5CodeId");

                    b.ToTable("Payroll_IRP5Code", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.PayrollPosition", b =>
                {
                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("Position_ID");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("int")
                        .HasColumnName("DivisionID");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("EmployeeID");

                    b.Property<int?>("Enabled")
                        .HasColumnType("int")
                        .HasColumnName("Enabled");

                    b.Property<int?>("HOD")
                        .HasColumnType("int")
                        .HasColumnName("HOD");

                    b.Property<int?>("HierarchyNo")
                        .HasColumnType("int")
                        .HasColumnName("HierarchyNo");

                    b.Property<int?>("JobProfileId")
                        .HasColumnType("int")
                        .HasColumnName("JobProfileID");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentID");

                    b.Property<string>("PositionCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("PositionCode");

                    b.Property<string>("PositionDesc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PositionDesc");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("UniqueId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("UniqueId");

                    b.HasKey("PositionId");

                    b.ToTable("Payroll_Position", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.PayrollSalaryHead", b =>
                {
                    b.Property<int>("SalaryHeadId")
                        .HasColumnType("int")
                        .HasColumnName("SalaryHead_ID");

                    b.Property<int?>("CalculationFlag")
                        .HasColumnType("int")
                        .HasColumnName("CalculationFlag");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("Enabled");

                    b.Property<int?>("IRP5CodeId")
                        .HasColumnType("int")
                        .HasColumnName("IRP5CodeId");

                    b.Property<string>("SalaryHeadName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SalaryHeadName");

                    b.Property<string>("SalaryHeadTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SalaryHeadTitle");

                    b.HasKey("SalaryHeadId");

                    b.ToTable("Payroll_SalaryHead", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.PositionApprovalConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDepartmentExcessOvertimeApprover")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOvertimeApprover")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOvertimeRecommender")
                        .HasColumnType("bit");

                    b.Property<string>("PositionDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PositionId")
                        .IsUnique();

                    b.ToTable("PositionApprovalConfig", (string)null);
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.PositionReportingRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PositionApprovalConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReportsToPositionDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReportsToPositionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PositionApprovalConfigId");

                    b.ToTable("PositionReportingRelationship", (string)null);
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.TemporaryActingAppointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActingEmployeeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ActingEmployeeName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ActingInPositionDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ActingInPositionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PositionApprovalConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PositionApprovalConfigId");

                    b.ToTable("TemporaryActingAppointment", (string)null);
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.OvertimeTransactionDocument", b =>
                {
                    b.HasOne("PlatinumOvertime_API.Models.Domain.OvertimeTransaction", "OvertimeTransaction")
                        .WithMany("Documents")
                        .HasForeignKey("OvertimeTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OvertimeTransaction");
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.OvertimeWorkflowState", b =>
                {
                    b.HasOne("PlatinumOvertime_API.Models.Domain.OvertimeTransaction", "OvertimeTransaction")
                        .WithMany("WorkflowHistory")
                        .HasForeignKey("OvertimeTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OvertimeTransaction");
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.PositionReportingRelationship", b =>
                {
                    b.HasOne("PlatinumOvertime_API.Models.Domain.PositionApprovalConfig", "PositionApprovalConfig")
                        .WithMany("ReportingRelationships")
                        .HasForeignKey("PositionApprovalConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PositionApprovalConfig");
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.TemporaryActingAppointment", b =>
                {
                    b.HasOne("PlatinumOvertime_API.Models.Domain.PositionApprovalConfig", "PositionApprovalConfig")
                        .WithMany("ActingAppointments")
                        .HasForeignKey("PositionApprovalConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PositionApprovalConfig");
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.OvertimeTransaction", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("WorkflowHistory");
                });

            modelBuilder.Entity("PlatinumOvertime_API.Models.Domain.PositionApprovalConfig", b =>
                {
                    b.Navigation("ActingAppointments");

                    b.Navigation("ReportingRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
