CREATE TABLE [dbo].[Asset_Register_Items](
	[AssetRegisterItem_ID] [int] IDENTITY(1,1) NOT NULL,
	[AssetClass_ID] [int] NULL,
	[AssetCategory_ID] [int] NULL,
	[ProjectItem_ID] [int] NULL,
	[Custodian_ID] [int] NULL,
	[CustodianIdNumber] [nvarchar](50) NULL,
	[Department] [int] NULL,
	[Description] [nvarchar](4000) NOT NULL,
	[ParentAssetRegisterItem_ID] [varchar](100) NULL,
	[Quantity] [decimal](18, 8) NULL,
	[ScoaVote] [nvarchar](50) NULL,
	[Donated_ID] [int] NULL,
	[MarketValue] [money] NULL,
	[ReadyForUse] [datetime] NULL,
	[DateCaptured] [datetime] NULL,
	[Capturer_ID] [int] NULL,
	[DateModified]  AS (getdate()),
	[Modifier_ID] [int] NULL,
	[CurrentAmount] [decimal](18, 8) NULL,
	[AssetStatus_ID] [int] NULL,
	[AssetCondition_ID] [int] NULL,
	[AssetType_ID] [int] NULL,
	[GRN_ID] [int] NULL,
	[CarryingAmountClosingBalance] [decimal](18, 8) NULL,
	[Barcode] [nvarchar](100) NULL,
	[AssetOwnership_ID] [int] NULL,
	[GIS_ID] [nvarchar](50) NULL,
	[GisFeature] [nvarchar](50) NULL,
	[GIS_URL] [nvarchar](500) NULL,
	[GPSCoordinates] [nvarchar](50) NULL,
	[Town_ID] [int] NULL,
	[SiteNumber] [nvarchar](50) NULL,
	[Street_ID] [int] NULL,
	[StreetAddress] [nvarchar](100) NULL,
	[Building_ID] [int] NULL,
	[Ward_ID] [int] NULL,
	[Room_ID] [int] NULL,
	[SGNumberChange_ID] [varchar](200) NULL,
	[Zoning_ID] [int] NULL,
	[Prod_Key_ID] [bigint] NULL,
	[ErfNumber] [nvarchar](50) NULL,
	[Make] [nvarchar](50) NULL,
	[Model] [nvarchar](50) NULL,
	[Year] [int] NULL,
	[RoomNumber] [nvarchar](50) NULL,
	[ErfSizeM2] [decimal](18, 8) NULL,
	[DeedNumber] [nvarchar](50) NULL,
	[RegistrationNumber] [nvarchar](50) NULL,
	[SerialNumber] [nvarchar](50) NULL,
	[QuantityCaption] [nvarchar](50) NULL,
	[MunicipalDepartment_ID] [int] NULL,
	[ScoaFunction_ID] [int] NULL,
	[ScoaProject_ID] [int] NULL,
	[ScoaFunds_ID] [int] NULL,
	[ScoaRegion_ID] [int] NULL,
	[Image] [varbinary](max) NULL,
	[OriginalCostClosingBalance] [decimal](18, 8) NULL,
	[IsAwaitingApproval] [bit] NULL,
	[CommodityType_ID] [int] NULL,
	[CostFormula_ID] [int] NULL,
	[TakeOnType_ID] [int] NULL,
	[SubIdentification] [int] NULL,
	[DateOfTakeOnBalancesImported] [datetime] NULL,
	[SCOARepairsAndMaintenance] [int] NULL,
	[Decommissioning] [bit] NULL,
	[RestorationAndSimilarLiabilitiesAmount] [decimal](18, 8) NULL,
	[AccumulatedDepreciationClosingBalance] [decimal](18, 8) NULL,
	[AccumulatedDepreciationOtherChanges] [decimal](18, 8) NULL,
	[AccumulatedDepreciationCurrentYear] [decimal](18, 8) NULL,
	[AccumulatedDepreciationDisposal] [decimal](18, 8) NULL,
	[AccumulatedDepreciationTransfer] [decimal](18, 8) NULL,
	[AccumulatedImpairmentClosingBalance] [decimal](18, 8) NULL,
	[OrderNumber] [nvarchar](max) NULL,
	[InvoiceDate] [datetime] NULL,
	[SupplierName] [nvarchar](100) NULL,
	[SupplierCode] [nvarchar](100) NULL,
	[InvoiceNumber] [nvarchar](100) NULL,
	[EFTReferenceNumber] [nvarchar](100) NULL,
	[ContributedAssets] [decimal](18, 8) NULL,
	[ReplacementOrNew] [nvarchar](50) NULL,
	[ConditionCheckDate] [datetime] NULL,
	[ConditionAssessmentDoneBy] [nvarchar](100) NULL,
	[UsefulLifeYearComponent] [decimal](18, 8) NULL,
	[UsefulLifeMonthComponent] [decimal](18, 8) NULL,
	[CorrectionOfErrorAmount] [decimal](18, 8) NULL,
	[ChangeInAccountingPolicyAmount] [decimal](18, 8) NULL,
	[ResidualValueAmountChangeInAccountingEstimate] [decimal](18, 8) NULL,
	[ReversalImpairmentInFull] [bit] NULL,
	[ReversalImpairmentIfNotInFullAmountToBeReversed] [decimal](18, 8) NULL,
	[ReasonForImpairment] [nvarchar](200) NULL,
	[ImpairmentAmountCurrentYear] [decimal](18, 8) NULL,
	[ReversalOfImpairmentAmount] [decimal](18, 8) NULL,
	[ImpairmentsReferenceToCouncilResolution] [nvarchar](100) NULL,
	[RevaluationDoneBy] [int] NULL,
	[LastRevaluationDate] [datetime] NULL,
	[RevaluationValue] [decimal](18, 8) NULL,
	[RevaluationReserveClosingBalance] [decimal](18, 8) NULL,
	[NetGainsLossesFromFairAmountAdjustments] [decimal](18, 8) NULL,
	[PerformedBy] [nvarchar](100) NULL,
	[MultiOrSingleYear] [int] NULL,
	[WorkInProgressAmount] [decimal](18, 8) NULL,
	[CrossReferenceOfUnbundledProject] [nvarchar](100) NULL,
	[ProjectUnbundledAmount] [decimal](18, 8) NULL,
	[MethodOfTransferTo] [nvarchar](100) NULL,
	[TransferToAssetType] [nvarchar](100) NULL,
	[TransferToGRAPAndAFSCLASS] [nvarchar](100) NULL,
	[TransferToCostCentre] [nvarchar](100) NULL,
	[DateOfTransfer] [datetime] NULL,
	[ReplacedAssetsReferenceNumber] [int] NULL,
	[TransferTo] [nvarchar](100) NULL,
	[TransferFrom] [nvarchar](100) NULL,
	[DateOfDisposal] [datetime] NULL,
	[MethodOfDisposal] [nvarchar](100) NULL,
	[DisposalProceeds] [decimal](18, 8) NULL,
	[DisposalAmountCost] [decimal](18, 8) NULL,
	[DisposalImpairmentAmount] [decimal](18, 8) NULL,
	[ProfitOrLossOnDisposal] [decimal](18, 8) NULL,
	[InsuredAmountInsuredBy] [decimal](18, 8) NULL,
	[InsuranceNumberReference] [nvarchar](100) NULL,
	[WarrenteesReference] [nvarchar](100) NULL,
	[Verified] [bit] NULL,
	[VerificationDate] [datetime] NULL,
	[VerificationDoneBy] [nvarchar](100) NULL,
	[NERSA_ID] [int] NULL,
	[PurchaseAmount] [decimal](18, 8) NULL,
	[Suburb] [nvarchar](100) NULL,
	[MeasurementModel_ID] [int] NULL,
	[AssetCalculationType_ID] [int] NULL,
	[Scoa_ID] [int] NULL,
	[RevaluationDate] [datetime] NULL,
	[RevaluationModel_ID] [int] NULL,
	[Asset_SubCategory_ID] [int] NULL,
	[Asset_SubCategory_Group_ID] [int] NULL,
	[Asset_SubCategory_Group_Type_ID] [int] NULL,
	[Asset_Component_Type_ID] [int] NULL,
	[UoM] [int] NULL,
	[Dim1] [decimal](18, 8) NULL,
	[Dim2] [decimal](18, 8) NULL,
	[Dim3] [decimal](18, 8) NULL,
	[WIP_Opening_Balance] [decimal](18, 8) NULL,
	[WIP_Closing_Balance] [decimal](18, 8) NULL,
	[WIP_Current_Year] [decimal](18, 8) NULL,
	[Cash_Generating_Asset_Indicator] [int] NULL,
	[Recoverable_Amount] [decimal](18, 8) NULL,
	[Replacement_Value] [decimal](18, 8) NULL,
	[Donor_ID] [varchar](100) NULL,
	[Donor_Name] [nvarchar](100) NULL,
	[Date_Donated] [datetime] NULL,
	[Scoa_Cost_ID] [int] NULL,
	[DimensionQuantity] [decimal](18, 8) NULL,
	[Comments] [nvarchar](500) NULL,
	[Scoa_Acquistion_ID] [int] NULL,
	[Scoa_Contributing_ID] [int] NULL,
	[AssetFlags_ID] [int] NULL,
	[ResidualValue] [decimal](18, 8) NULL,
	[RevisedResidualValue] [decimal](18, 8) NULL,
	[AdditionalCost] [decimal](18, 8) NULL,
	[RevisedUsefulLife] [int] NULL,
	[RemainingUsefulLife] [decimal](18, 8) NULL,
	[AccumulatedDepreciationOpeningBalance] [decimal](18, 8) NULL,
	[AccumulatedImpairmentOpeningBalance] [decimal](18, 8) NULL,
	[ExpectedDepreciationRate] [decimal](18, 8) NULL,
	[AmortisationValue] [decimal](18, 8) NULL,
	[ExpectedAmortisationRate] [decimal](18, 8) NULL,
	[EvidenceDocument] [varbinary](max) NULL,
	[ActualUnitProducedThisYear] [int] NULL,
	[ExpectedUnitsOfProduction] [int] NULL,
	[Supplier_ID] [int] NULL,
	[DisposalReason] [nvarchar](250) NULL,
	[OldBarCode] [nvarchar](50) NULL,
	[RemainingPeriod] [bit] NULL,
	[Leased] [bit] NULL,
	[Cost_Centre] [nvarchar](max) NULL,
	[Cost_Centre_Code] [nvarchar](max) NULL,
	[Run_ID] [int] NULL,
	[Upload_Type] [int] NULL,
	[Approval_ID] [int] NULL,
	[AssetLevel] [int] NULL,
	[RejectReason] [int] NULL,
	[InventoryID] [int] NULL,
	[TempStatusID] [int] NULL,
	[longitude] [nvarchar](75) NULL,
	[latitude] [nvarchar](75) NULL,
	[MunicipalDepartment] [nvarchar](max) NULL,
	[FundingSource] [int] NULL,
	[PreviousCondition] [int] NULL,
	[ConditionChangeLevel] [int] NULL,
	[OldScoaProject_ID] [int] NULL,
	[OldScoa_Cost_ID] [int] NULL,
	[OldScoaFunction_ID] [int] NULL,
	[OldScoaFunds_ID] [int] NULL,
	[OldScoaRegion_ID] [int] NULL,
	[OldScoa_Acquistion_ID] [int] NULL,
	[OldScoa_Contributing_ID] [int] NULL,
	[Takon_ItemID] [int] NULL,
	[TransactionProjectDR] [int] NULL,
	[TransactionProjectItemDR] [int] NULL,
	[TransactionProjectCR] [int] NULL,
	[TransactionProjectItemCR] [int] NULL,
	[InsuredBy] [varchar](200) NULL,
	[Validated] [bit] NULL,
	[AccumulatedDepreciationVoteAcc] [int] NULL,
	[AccumulatedImpairmentVoteAcc] [int] NULL,
	[FairvalueVoteAcc] [int] NULL,
	[RevaluationVoteAcc] [int] NULL,
	[DecommissioningVoteAcc] [int] NULL,
	[MeasurementType_ID] [int] NULL,
	[DivisionID] [int] NULL,
	[FloorID] [int] NULL,
	[InsureanceDocument] [varchar](255) NULL,
	[SuburbID] [int] NULL,
	[ReasonForChange] [varchar](500) NULL,
	[TypeID] [int] NULL,
	[Financial_Status_ID] [int] NULL,
	[Sub_Component_Type_ID] [int] NULL,
	[Impairment_Date] [datetime] NULL,
	[Remaining_Useful_Life_Year] [decimal](18, 8) NULL,
	[Floor_Area] [decimal](18, 8) NULL,
	[Custom_1] [varchar](200) NULL,
	[Custom_2] [varchar](200) NULL,
	[Custom_3] [varchar](200) NULL,
	[Custom_4] [varchar](200) NULL,
	[Custom_5] [varchar](200) NULL,
	[Custom_6] [varchar](200) NULL,
	[Custom_7] [varchar](200) NULL,
	[Custom_8] [varchar](200) NULL,
	[Custom_9] [varchar](200) NULL,
	[Custom_10] [varchar](200) NULL,
	[Custom_11] [varchar](200) NULL,
	[Custom_12] [varchar](200) NULL,
	[Custom_13] [varchar](200) NULL,
	[Custom_14] [varchar](200) NULL,
	[Custom_15] [varchar](200) NULL,
	[Custom_16] [varchar](200) NULL,
	[Custom_17] [varchar](200) NULL,
	[Custom_18] [varchar](200) NULL,
	[Custom_19] [varchar](200) NULL,
	[Custom_20] [varchar](50) NULL,
	[Custom_21] [varchar](50) NULL,
	[Custom_22] [varchar](50) NULL,
	[Custom_23] [varchar](50) NULL,
	[Custom_24] [varchar](50) NULL,
	[Custom_25] [varchar](50) NULL,
	[Custom_26] [varchar](50) NULL,
	[ImageRef] [varchar](255) NULL,
	[Component_ID] [varchar](255) NULL,
	[AssetOwnershipName] [varchar](100) NULL,
	[DonorRegNumber] [varchar](50) NULL,
	[DonationDocument] [varchar](255) NULL,
	[UnitNumber] [varchar](20) NULL,
	[PortionNumber] [varchar](20) NULL,
	[MainAssetID] [nvarchar](100) NULL,
	[MainAssetDescription] [nvarchar](100) NULL,
	[CIDMSSubComponentTypeID] [int] NULL,
	[CIDMSComponentType] [int] NULL,
	[CIDMSAccountingGroup] [int] NULL,
	[CIDMSSubAccountingGroup] [int] NULL,
	[CIDMSAssetClass] [int] NULL,
	[CIDMSAssetGroupType] [int] NULL,
	[CIDMSAssetType] [int] NULL,
	[CashOrNoncashgeneratingunit] [nvarchar](100) NULL,
	[CommisioningDate] [date] NULL,
	[InfrastructurOrNonInfrastructure] [nvarchar](100) NULL,
	[NatureOfAddition] [nvarchar](100) NULL,
	[CostOfAddition] [decimal](18, 8) NULL,
	[YearConstructed] [date] NULL,
	[ForecastReplacementYear] [int] NULL,
	[PreviousForecastReplacementYear] [date] NULL,
	[InsuranceCover] [nvarchar](100) NULL,
	[InsurancePolicyNo] [nvarchar](100) NULL,
	[Warranty] [nvarchar](100) NULL,
	[CurrentReplacementCostCRC] [decimal](18, 8) NULL,
	[DepreciatedReplacementCostDRC] [decimal](18, 8) NULL,
	[AnnualisedMaintenanceCRC] [decimal](18, 8) NULL,
	[AnnualMaintenanceBudgetNeed] [decimal](18, 8) NULL,
	[RemainingUsefulLifeAtTakeOn] [nvarchar](100) NULL,
	[ConstructionMaterial] [nvarchar](100) NULL,
	[BasicMunicipalityService] [int] NULL,
	[CriticalityGrade] [int] NULL,
	[PerformanceGrade] [int] NULL,
	[UtilisationGrade] [int] NULL,
	[InfrastructureHealthGrade] [int] NULL,
	[ConsequenceOfFailure] [nvarchar](100) NULL,
	[Risk] [nvarchar](100) NULL,
	[WellKnownTextWKT] [nvarchar](100) NULL,
	[MunicipalAssetID] [nvarchar](100) NULL,
	[AcquisitionDate] [datetime] NULL,
	[VerifyID] [int] NULL,
	[InserviceDate] [datetime] NULL,
	[Insured] [int] NULL,
	[InsuranceAmount] [decimal](18, 8) NULL,
	[ContractHeader_Id] [int] NULL,
	[SundryPaymentId] [int] NULL,
	[ManagedFlag] [bit] NOT NULL,
	[FundType] [nvarchar](100) NULL,
	[FundingSourceNumber] [nvarchar](100) NULL,
	[FundingSourceAmount] [decimal](18, 8) NULL,
	[IssueID] [int] NULL,
	[HighValueID] [int] NULL,
	[RevaluationOpeningBalance] [decimal](18, 8) NULL,
	[MovementInRevaluationReserve] [decimal](18, 8) NULL,
	[DepreciationOffset] [decimal](18, 8) NULL,
	[DeemedCost] [nvarchar](100) NULL,
	[RevaluationImpairmentOpeningBalance] [decimal](18, 8) NULL,
	[TransferFromAmount] [decimal](18, 8) NULL,
	[TransferToAmount] [decimal](18, 8) NULL,
	[Diameter] [nvarchar](100) NULL,
	[Capacity] [nvarchar](100) NULL,
	[Refurb_DT] [decimal](18, 8) NULL,
	[Refurb_CT] [decimal](18, 8) NULL,
	[Refurb_Depreciation] [decimal](18, 8) NULL,
	[Refurb_Revaluation] [decimal](18, 8) NULL,
PRIMARY KEY CLUSTERED 
(
	[AssetRegisterItem_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 93, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



