CREATE TABLE [dbo].[Asset_SCMTransfer](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AssetClass_ID] [int] NULL,
	[AssetCategory_ID] [int] NULL,
	[ProjectItem_ID] [int] NULL,
	[Custodian_ID] [int] NULL,
	[CustodianIdNumber] [nvarchar](50) NULL,
	[Department] [int] NULL,
	[Description] [nvarchar](4000) NULL,
	[ParentAssetRegisterItem_ID] [int] NULL,
	[Quantity] [decimal](18, 2) NULL,
	[ScoaVote] [nvarchar](50) NULL,
	[FundingSource] [nvarchar](100) NULL,
	[Donated_ID] [int] NULL,
	[MarketValue] [money] NULL,
	[ReadyForUse] [date] NULL,
	[DateCaptured] [datetime] NULL,
	[Capturer_ID] [int] NULL,
	[DateModified] [datetime] NULL,
	[Modifier_ID] [int] NULL,
	[CurrentAmount] [decimal](18, 2) NULL,
	[AssetStatus_ID] [int] NULL,
	[AssetCondition_ID] [int] NULL,
	[AssetType_ID] [int] NULL,
	[GRN_ID] [int] NULL,
	[CarryingAmountClosingBalance] [decimal](18, 2) NULL,
	[Barcode] [nvarchar](50) NULL,
	[AssetOwnership_ID] [int] NULL,
	[GIS_ID] [int] NULL,
	[GisFeature] [nvarchar](200) NULL,
	[GPSCoordinates] [nvarchar](50) NULL,
	[Town_ID] [int] NULL,
	[SiteNumber] [nvarchar](50) NULL,
	[Street_ID] [int] NULL,
	[StreetAddress] [nvarchar](100) NULL,
	[Building_ID] [int] NULL,
	[Ward_ID] [int] NULL,
	[Room_ID] [int] NULL,
	[SGNumberChange_ID] [int] NULL,
	[Zoning_ID] [int] NULL,
	[Prod_Key_ID] [bigint] NULL,
	[ErfNumber] [nvarchar](50) NULL,
	[Make] [nvarchar](50) NULL,
	[Model] [nvarchar](50) NULL,
	[Year] [int] NULL,
	[RoomNumber] [nvarchar](50) NULL,
	[ErfSizeM2] [decimal](18, 2) NULL,
	[DeedNumber] [nvarchar](50) NULL,
	[RegistrationNumber] [nvarchar](50) NULL,
	[SerialNumber] [nvarchar](50) NULL,
	[QuantityCaption] [nvarchar](50) NULL,
	[MunicipalDepartment_ID] [int] NULL,
	[ScoaFunction_ID] [int] NULL,
	[ScoaProject_ID] [int] NULL,
	[ScoaFunds_ID] [int] NULL,
	[ScoaRegion_ID] [int] NULL,
	[Image] [varbinary](max) NULL,
	[OriginalCostClosingBalance] [decimal](18, 2) NULL,
	[IsAwaitingApproval] [bit] NULL,
	[CommodityType_ID] [int] NULL,
	[CostFormula_ID] [int] NULL,
	[TakeOnType_ID] [int] NULL,
	[SubIdentification] [int] NULL,
	[DateOfTakeOnBalancesImported] [date] NULL,
	[SCOARepairsAndMaintenance] [int] NULL,
	[Decommissioning] [bit] NULL,
	[RestorationAndSimilarLiabilitiesAmount] [decimal](18, 2) NULL,
	[AccumulatedDepreciationClosingBalance] [decimal](18, 2) NULL,
	[AccumulatedDepreciationOtherChanges] [decimal](18, 2) NULL,
	[AccumulatedDepreciationCurrentYear] [decimal](18, 2) NULL,
	[AccumulatedDepreciationDisposal] [decimal](18, 2) NULL,
	[AccumulatedDepreciationTransfer] [decimal](18, 2) NULL,
	[AccumulatedImpairmentClosingBalance] [decimal](18, 2) NULL,
	[OrderNumber] [nvarchar](max) NULL,
	[InvoiceDate] [date] NULL,
	[SupplierName] [nvarchar](100) NULL,
	[SupplierCode] [nvarchar](100) NULL,
	[InvoiceNumber] [nvarchar](100) NULL,
	[EFTReferenceNumber] [nvarchar](100) NULL,
	[ContributedAssets] [decimal](18, 2) NULL,
	[ReplacementOrNew] [nvarchar](50) NULL,
	[ConditionCheckDate] [date] NULL,
	[ConditionAssessmentDoneBy] [nvarchar](100) NULL,
	[UsefulLifeYearComponent] [int] NULL,
	[UsefulLifeMonthComponent] [int] NULL,
	[CorrectionOfErrorAmount] [decimal](18, 2) NULL,
	[ChangeInAccountingPolicyAmount] [decimal](18, 2) NULL,
	[ResidualValueAmountChangeInAccountingEstimate] [decimal](18, 2) NULL,
	[ReversalImpairmentInFull] [bit] NULL,
	[ReversalImpairmentIfNotInFullAmountToBeReversed] [decimal](18, 2) NULL,
	[ReasonForImpairment] [nvarchar](200) NULL,
	[ImpairmentAmountCurrentYear] [decimal](18, 2) NULL,
	[ReversalOfImpairmentAmount] [decimal](18, 2) NULL,
	[ImpairmentsReferenceToCouncilResolution] [nvarchar](100) NULL,
	[RevaluationDoneBy] [int] NULL,
	[LastRevaluationDate] [date] NULL,
	[RevaluationAmount] [decimal](18, 2) NULL,
	[AccumulatedRevaluationAmountInSurplusOrDeficit] [decimal](18, 2) NULL,
	[NetGainsLossesFromFairAmountAdjustments] [decimal](18, 2) NULL,
	[PerformedBy] [nvarchar](100) NULL,
	[MultiOrSingleYear] [int] NULL,
	[WorkInProgressAmount] [decimal](18, 2) NULL,
	[CrossReferenceOfUnbundledProject] [nvarchar](100) NULL,
	[ProjectUnbundledAmount] [decimal](18, 2) NULL,
	[MethodOfTransferTo] [nvarchar](100) NULL,
	[TransferToAssetType] [nvarchar](100) NULL,
	[TransferToGRAPAndAFSCLASS] [nvarchar](100) NULL,
	[TransferToCostCentre] [nvarchar](100) NULL,
	[DateOfTransfer] [date] NULL,
	[ReplacedAssetsReferenceNumber] [int] NULL,
	[TransferTo] [nvarchar](100) NULL,
	[TransferFrom] [nvarchar](100) NULL,
	[DateOfDisposal] [date] NULL,
	[MethodOfDisposal] [nvarchar](100) NULL,
	[DisposalProceeds] [decimal](18, 2) NULL,
	[DisposalAmountCost] [decimal](18, 2) NULL,
	[DisposalImpairmentAmount] [decimal](18, 2) NULL,
	[ProfitOrLossOnDisposal] [decimal](18, 2) NULL,
	[InsuredAmountInsuredBy] [decimal](18, 2) NULL,
	[InsuranceNumberReference] [nvarchar](100) NULL,
	[WarrenteesReference] [nvarchar](100) NULL,
	[Verified] [bit] NULL,
	[VerificationDate] [date] NULL,
	[VerificationDoneBy] [nvarchar](100) NULL,
	[NERSA_ID] [int] NULL,
	[PurchaseAmount] [decimal](18, 2) NULL,
	[Suburb] [nvarchar](100) NULL,
	[MeasurementModel_ID] [int] NULL,
	[AssetCalculationType_ID] [int] NULL,
	[Scoa_ID] [int] NULL,
	[RevaluationDate] [date] NULL,
	[RevaluationModel_ID] [int] NULL,
	[Asset_SubCategory_ID] [int] NULL,
	[Asset_SubCategory_Group_ID] [int] NULL,
	[Asset_SubCategory_Group_Type_ID] [int] NULL,
	[Asset_Component_Type_ID] [int] NULL,
	[UoM] [int] NULL,
	[Dim1] [int] NULL,
	[Dim2] [int] NULL,
	[Dim3] [int] NULL,
	[WIP_Opening_Balance] [decimal](18, 0) NULL,
	[WIP_Closing_Balance] [decimal](18, 0) NULL,
	[WIP_Current_Year] [decimal](18, 0) NULL,
	[Cash_Generating_Asset_Indicator] [int] NULL,
	[Recoverable_Amount] [decimal](18, 0) NULL,
	[Replacement_Value] [decimal](18, 0) NULL,
	[Donor_ID] [nvarchar](100) NULL,
	[Donor_Name] [nvarchar](100) NULL,
	[Date_Donated] [date] NULL,
	[Scoa_Cost_ID] [int] NULL,
	[DimensionQuantity] [int] NULL,
	[Comments] [nvarchar](500) NULL,
	[Scoa_Acquistion_ID] [int] NULL,
	[Scoa_Contributing_ID] [int] NULL,
	[AssetFlags_ID] [int] NULL,
	[ResidualValue] [decimal](18, 2) NULL,
	[RevisedResidualValue] [decimal](18, 2) NULL,
	[AdditionalCost] [decimal](18, 2) NULL,
	[RevisedUsefulLife] [int] NULL,
	[RemainingUsefulLife] [int] NULL,
	[AccumulatedDepreciationOpeningBalance] [decimal](18, 2) NULL,
	[AccumulatedImpairmentOpeningBalance] [decimal](18, 2) NULL,
	[ExpectedDepreciationRate] [decimal](18, 2) NULL,
	[AmortisationValue] [decimal](18, 2) NULL,
	[ExpectedAmortisationRate] [decimal](18, 2) NULL,
	[EvidenceDocument] [varbinary](max) NULL,
	[ActualUnitProducedThisYear] [int] NULL,
	[ExpectedUnitsOfProduction] [int] NULL,
	[Supplier_ID] [int] NULL,
	[DisposalReason] [nvarchar](250) NULL,
	[OldBarCode] [nvarchar](50) NULL,
	[RemainingPeriod] [bit] NULL,
	[Leased] [bit] NULL,
	[Cost_Centre] [nvarchar](max) NULL,
	[Cost_Centre_Code] [nvarchar](max) NULL,
	[AssetLevel] [int] NULL,
	[RejectReason] [int] NULL,
	[AssetRegisterItem_ID] [int] NULL,
	[SCMItem_ID] [int] NULL,
	[CheckType] [varchar](1000) NULL,
	[Approval_ID] [int] NULL,
	[Approval_Date] [datetime] NULL,
	[SundryPaymentId] [int] NULL,
 CONSTRAINT [PK_Asset_SCMTransfer] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 93, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


