CREATE TABLE [dbo].[Asset_Transaction_Summary](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[AssetRegisterItemID] [int] NULL,
	[FinancialYear] [nvarchar](10) NULL,
	[FinancialPeriod] [int] NULL,
	[CurrentValue] [decimal](18, 2) NULL,
	[RemainingUsefulLife] [decimal](18, 8) NULL,
	[AccumulatedDepreciationOpeningBalance] [decimal](18, 2) NULL,
	[DepreciationValue] [decimal](18, 2) NULL,
	[AccumulatedDepreciationClosingBalance] [decimal](18, 2) NULL,
	[AccumulatedImpairmentOpeningBalance] [decimal](18, 2) NULL,
	[ImpairmentValue] [decimal](18, 2) NULL,
	[AccumulatedImpairmentClosingBalance] [decimal](18, 2) NULL,
	[AccumulatedFairValueOpeningBalance] [decimal](18, 2) NULL,
	[FairValue] [decimal](18, 2) NULL,
	[AccumulatedFairValueClosingBalance] [decimal](18, 2) NULL,
	[AccumulatedRevaluationOpeningBalance] [decimal](18, 2) NULL,
	[RevaluationValue] [decimal](18, 2) NULL,
	[AccumulatedRevaluationClosingBalance] [decimal](18, 2) NULL,
	[AccumulatedImpairmentReversalOpeningBalance] [decimal](18, 2) NULL,
	[ImpairmentReversalValue] [decimal](18, 2) NULL,
	[AccumulatedImpairmentReversalClosingBalance] [decimal](18, 2) NULL,
	[DisposalOpeningBalance] [decimal](18, 2) NULL,
	[DisposalValue] [decimal](18, 2) NULL,
	[DisposalLossValue] [decimal](18, 2) NULL,
	[DisposalTotalValue] [decimal](18, 2) NULL,
	[DisposalClosingBalance] [decimal](18, 2) NULL,
	[WorkInProgressOpeningBalance] [decimal](18, 2) NULL,
	[WorkInProgressValue] [decimal](18, 2) NULL,
	[WorkInProgressClosingBalance] [decimal](18, 2) NULL,
	[AmortisationOpeningBalance] [decimal](18, 2) NULL,
	[AmortisationValue] [decimal](18, 2) NULL,
	[AmortisationClosingBalance] [decimal](18, 2) NULL,
	[CorrectionOfErrorOpeningBalance] [decimal](18, 2) NULL,
	[CorrectionOfErrorValue] [decimal](18, 2) NULL,
	[CorrectOfErrorClosingBalance] [decimal](18, 2) NULL,
	[AdditionalCostOpeningBalance] [decimal](18, 2) NULL,
	[AdditionalCostValue] [decimal](18, 2) NULL,
	[AdditionalCostClosingBalance] [decimal](18, 2) NULL,
	[AdditionOpeningBalance] [decimal](18, 2) NULL,
	[AdditionVaue] [decimal](18, 2) NULL,
	[AdditionClosingBalance] [decimal](18, 2) NULL,
	[MovementInRevaluationReserve] [decimal](18, 2) NULL,
	[DepreciationOffsetOpeningBalance] [decimal](18, 2) NULL,
	[DepreciationOffset] [decimal](18, 2) NULL,
	[DepreciationOffsetClosingBalance] [decimal](18, 2) NULL,
	[ImpairmentSurplus] [decimal](18, 2) NULL,
	[RevaluationReserveImpairmentOpeningBalance] [decimal](18, 8) NULL,
	[RevaluationReserveImpairment] [decimal](18, 8) NULL,
	[RevaluationReserveImpairmentReversal] [decimal](18, 8) NULL,
	[RevaluationReserveImpairmentClosingBalance] [decimal](18, 8) NULL,
	[RevaluationReserveRevaluation] [decimal](18, 8) NULL,
	[RevaluationReserveDisposal] [decimal](18, 8) NULL,
	[DepreciationAdjustment] [decimal](18, 8) NULL,
	[TransferFromValue] [decimal](18, 8) NULL,
	[TransferToValue] [decimal](18, 8) NULL,
	[CostOpeningBalance] [decimal](18, 8) NULL,
	[CostClosingBalance] [decimal](18, 8) NULL,
	[RefurbDTValue] [decimal](18, 8) NULL,
	[RefurbCTValue] [decimal](18, 8) NULL,
	[RefurbDepreciationValue] [decimal](18, 8) NULL,
	[RefurbRevaluationValue] [decimal](18, 8) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 93, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


