--
-- PostgreSQL database dump
--

\restrict 54GaOfQwZb3SMbwQeiTTb9mJFcem0GCZUbwl3Qe3Q5R4loX4L5HIXrGIDjUFT8N

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: idp_audit_logs_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.idp_audit_logs_ef (
    "Id" integer NOT NULL,
    "EntityType" character varying(100) NOT NULL,
    "EntityId" integer NOT NULL,
    "Action" character varying(100) NOT NULL,
    "OldValue" text,
    "NewValue" text,
    "PerformedBy" integer,
    "PerformedDate" timestamp with time zone NOT NULL,
    "IpAddress" character varying(50),
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL,
    "Status" character varying(50) NOT NULL
);


--
-- Name: idp_audit_logs_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.idp_audit_logs_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."idp_audit_logs_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: idp_comment_responses_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.idp_comment_responses_ef (
    "Id" integer NOT NULL,
    "CommentId" integer NOT NULL,
    "ResponseText" text NOT NULL,
    "ResponsibleOfficial" character varying(200),
    "ResponseDate" timestamp with time zone,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL
);


--
-- Name: idp_comment_responses_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.idp_comment_responses_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."idp_comment_responses_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: idp_cycles_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.idp_cycles_ef (
    "Id" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "StartYear" integer NOT NULL,
    "EndYear" integer NOT NULL,
    "Status" character varying(50) NOT NULL,
    "RevisionNumber" integer NOT NULL,
    "MunicipalityName" character varying(300) NOT NULL,
    "Description" text,
    "IsLocked" boolean NOT NULL,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL
);


--
-- Name: idp_cycles_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.idp_cycles_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."idp_cycles_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: idp_document_versions_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.idp_document_versions_ef (
    "Id" integer NOT NULL,
    "CycleId" integer NOT NULL,
    "VersionNumber" integer NOT NULL,
    "VersionType" character varying(50) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "ContentJson" text,
    "ResolutionNumber" text,
    "ResolutionDate" timestamp with time zone,
    "CouncilMeetingRef" text,
    "IsLocked" boolean NOT NULL,
    "LockedDate" timestamp with time zone,
    "LockedBy" integer,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL
);


--
-- Name: idp_document_versions_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.idp_document_versions_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."idp_document_versions_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: idp_milestones_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.idp_milestones_ef (
    "Id" integer NOT NULL,
    "PhaseId" integer NOT NULL,
    "CycleId" integer NOT NULL,
    "Title" character varying(300) NOT NULL,
    "Description" text,
    "AssignedTo" character varying(200),
    "DueDate" timestamp with time zone,
    "Status" character varying(50) NOT NULL,
    "Progress" integer NOT NULL,
    "IsMandatory" boolean NOT NULL,
    "EvidenceUrl" text,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL
);


--
-- Name: idp_milestones_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.idp_milestones_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."idp_milestones_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: idp_process_phases_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.idp_process_phases_ef (
    "Id" integer NOT NULL,
    "CycleId" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" text,
    "OrderIndex" integer NOT NULL,
    "Owner" character varying(200),
    "StartDate" timestamp with time zone,
    "EndDate" timestamp with time zone,
    "Progress" integer NOT NULL,
    "Status" character varying(50) NOT NULL,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL
);


--
-- Name: idp_process_phases_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.idp_process_phases_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."idp_process_phases_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: idp_project_indicators_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.idp_project_indicators_ef (
    "Id" integer NOT NULL,
    "ProjectId" integer NOT NULL,
    "Name" character varying(300) NOT NULL,
    "Baseline" character varying(200),
    "TargetY1" character varying(200),
    "TargetY2" character varying(200),
    "TargetY3" character varying(200),
    "TargetY4" character varying(200),
    "TargetY5" character varying(200),
    "ResponsibleOfficial" character varying(200),
    "EvidenceLink" text,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL,
    "Status" character varying(50) NOT NULL
);


--
-- Name: idp_project_indicators_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.idp_project_indicators_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."idp_project_indicators_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: idp_projects_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.idp_projects_ef (
    "Id" integer NOT NULL,
    "CycleId" integer NOT NULL,
    "ObjectiveId" integer,
    "Name" character varying(300) NOT NULL,
    "Description" text,
    "Classification" character varying(50) NOT NULL,
    "Department" character varying(200) NOT NULL,
    "Ward" character varying(100),
    "Region" character varying(200),
    "Priority" character varying(50) NOT NULL,
    "PriorityRanking" integer NOT NULL,
    "OverrideRank" integer,
    "BudgetAmount" numeric(15,2),
    "FundingSource" character varying(200),
    "FundingSourceSummary" text,
    "MscoaProjectSegment" character varying(100),
    "MscoaFundSegment" character varying(100),
    "MscoaRegionSegment" character varying(100),
    "StartDate" timestamp with time zone,
    "EndDate" timestamp with time zone,
    "Latitude" double precision,
    "Longitude" double precision,
    "Status" character varying(50) NOT NULL,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL
);


--
-- Name: idp_projects_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.idp_projects_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."idp_projects_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: idp_public_comments_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.idp_public_comments_ef (
    "Id" integer NOT NULL,
    "CycleId" integer NOT NULL,
    "SourceChannel" character varying(100) NOT NULL,
    "Ward" character varying(100),
    "Region" character varying(200),
    "Category" character varying(100),
    "CommentText" text NOT NULL,
    "LinkedProjectId" integer,
    "LinkedObjectiveId" integer,
    "SubmitterName" character varying(200),
    "SubmissionDate" timestamp with time zone,
    "Status" character varying(50) NOT NULL,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL
);


--
-- Name: idp_public_comments_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.idp_public_comments_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."idp_public_comments_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: idp_strategic_objectives_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.idp_strategic_objectives_ef (
    "Id" integer NOT NULL,
    "CycleId" integer NOT NULL,
    "Code" character varying(50) NOT NULL,
    "Description" text NOT NULL,
    "AlignmentTags" text,
    "NdpAlignment" text,
    "ProvincialAlignment" text,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL,
    "Status" character varying(50) NOT NULL
);


--
-- Name: idp_strategic_objectives_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.idp_strategic_objectives_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."idp_strategic_objectives_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: idp_submission_logs_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.idp_submission_logs_ef (
    "Id" integer NOT NULL,
    "CycleId" integer NOT NULL,
    "DocumentVersionId" integer,
    "SubmissionType" character varying(100) NOT NULL,
    "ReferenceNumber" character varying(200),
    "SubmissionDate" timestamp with time zone,
    "ValidationStatus" character varying(50) NOT NULL,
    "ValidationFeedback" text,
    "AdoptedIdpFileName" text,
    "CouncilResolutionFileName" text,
    "MinutesFileName" text,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL,
    "Status" character varying(50) NOT NULL
);


--
-- Name: idp_submission_logs_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.idp_submission_logs_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."idp_submission_logs_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: idp_workflow_tasks_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.idp_workflow_tasks_ef (
    "Id" integer NOT NULL,
    "CycleId" integer NOT NULL,
    "DocumentVersionId" integer,
    "TaskType" character varying(100) NOT NULL,
    "AssignedRole" character varying(100),
    "AssignedTo" character varying(200),
    "Status" character varying(50) NOT NULL,
    "Comments" text,
    "Sequence" integer NOT NULL,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "CompletedBy" integer,
    "CompletedDate" timestamp with time zone,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL
);


--
-- Name: idp_workflow_tasks_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.idp_workflow_tasks_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."idp_workflow_tasks_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mscoa_segments_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mscoa_segments_ef (
    "Id" integer NOT NULL,
    "SegmentType" character varying(50) NOT NULL,
    "Code" character varying(50) NOT NULL,
    "Description" character varying(300) NOT NULL,
    "Level" integer NOT NULL,
    "ParentCode" character varying(50),
    "IsPostingLevel" boolean NOT NULL,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL,
    "Status" character varying(50) NOT NULL
);


--
-- Name: mscoa_segments_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mscoa_segments_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."mscoa_segments_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: priority_criteria_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.priority_criteria_ef (
    "Id" integer NOT NULL,
    "FrameworkId" integer NOT NULL,
    "Code" character varying(100) NOT NULL,
    "Name" character varying(300) NOT NULL,
    "Description" text,
    "Category" character varying(100) NOT NULL,
    "Weight" numeric(5,2) NOT NULL,
    "IsActive" boolean NOT NULL,
    "SortOrder" integer NOT NULL,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL
);


--
-- Name: priority_criteria_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.priority_criteria_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."priority_criteria_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: priority_framework_audits_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.priority_framework_audits_ef (
    "Id" integer NOT NULL,
    "FrameworkId" integer NOT NULL,
    "ChangeType" character varying(100) NOT NULL,
    "FieldName" character varying(200),
    "OldValue" text,
    "NewValue" text,
    "ChangedBy" integer,
    "ChangedDate" timestamp with time zone NOT NULL,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL
);


--
-- Name: priority_framework_audits_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.priority_framework_audits_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."priority_framework_audits_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: priority_frameworks_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.priority_frameworks_ef (
    "Id" integer NOT NULL,
    "Name" character varying(300) NOT NULL,
    "Version" integer NOT NULL,
    "CycleId" integer,
    "Status" character varying(50) NOT NULL,
    "HumanWeight" numeric(5,2) NOT NULL,
    "AiWeight" numeric(5,2) NOT NULL,
    "AiMode" character varying(50) NOT NULL,
    "ScaleMin" integer NOT NULL,
    "ScaleMax" integer NOT NULL,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL
);


--
-- Name: priority_frameworks_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.priority_frameworks_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."priority_frameworks_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: priority_project_scores_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.priority_project_scores_ef (
    "Id" integer NOT NULL,
    "FrameworkId" integer NOT NULL,
    "ProjectId" integer NOT NULL,
    "CriteriaId" integer NOT NULL,
    "HumanScore" integer,
    "AiScore" integer,
    "BlendedScore" numeric(7,2) NOT NULL,
    "Comments" text,
    "ScoredBy" integer,
    "ScoredDate" timestamp with time zone,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL
);


--
-- Name: priority_project_scores_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.priority_project_scores_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."priority_project_scores_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: priority_scoring_scales_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.priority_scoring_scales_ef (
    "Id" integer NOT NULL,
    "FrameworkId" integer NOT NULL,
    "ScoreValue" integer NOT NULL,
    "Label" character varying(200) NOT NULL,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL
);


--
-- Name: priority_scoring_scales_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.priority_scoring_scales_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."priority_scoring_scales_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_objective_links_ef; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_objective_links_ef (
    "Id" integer NOT NULL,
    "ProjectId" integer NOT NULL,
    "ObjectiveId" integer NOT NULL,
    "Percentage" numeric(5,2) NOT NULL,
    "CreatedBy" integer,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedBy" integer,
    "ModifiedDate" timestamp with time zone NOT NULL,
    "VersionNo" integer NOT NULL
);


--
-- Name: project_objective_links_ef_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project_objective_links_ef ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."project_objective_links_ef_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: idp_audit_logs_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.idp_audit_logs_ef ("Id", "EntityType", "EntityId", "Action", "OldValue", "NewValue", "PerformedBy", "PerformedDate", "IpAddress", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo", "Status") FROM stdin;
\.


--
-- Data for Name: idp_comment_responses_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.idp_comment_responses_ef ("Id", "CommentId", "ResponseText", "ResponsibleOfficial", "ResponseDate", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo") FROM stdin;
\.


--
-- Data for Name: idp_cycles_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.idp_cycles_ef ("Id", "Name", "StartYear", "EndYear", "Status", "RevisionNumber", "MunicipalityName", "Description", "IsLocked", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo") FROM stdin;
\.


--
-- Data for Name: idp_document_versions_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.idp_document_versions_ef ("Id", "CycleId", "VersionNumber", "VersionType", "Status", "ContentJson", "ResolutionNumber", "ResolutionDate", "CouncilMeetingRef", "IsLocked", "LockedDate", "LockedBy", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo") FROM stdin;
\.


--
-- Data for Name: idp_milestones_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.idp_milestones_ef ("Id", "PhaseId", "CycleId", "Title", "Description", "AssignedTo", "DueDate", "Status", "Progress", "IsMandatory", "EvidenceUrl", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo") FROM stdin;
\.


--
-- Data for Name: idp_process_phases_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.idp_process_phases_ef ("Id", "CycleId", "Name", "Description", "OrderIndex", "Owner", "StartDate", "EndDate", "Progress", "Status", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo") FROM stdin;
\.


--
-- Data for Name: idp_project_indicators_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.idp_project_indicators_ef ("Id", "ProjectId", "Name", "Baseline", "TargetY1", "TargetY2", "TargetY3", "TargetY4", "TargetY5", "ResponsibleOfficial", "EvidenceLink", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo", "Status") FROM stdin;
\.


--
-- Data for Name: idp_projects_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.idp_projects_ef ("Id", "CycleId", "ObjectiveId", "Name", "Description", "Classification", "Department", "Ward", "Region", "Priority", "PriorityRanking", "OverrideRank", "BudgetAmount", "FundingSource", "FundingSourceSummary", "MscoaProjectSegment", "MscoaFundSegment", "MscoaRegionSegment", "StartDate", "EndDate", "Latitude", "Longitude", "Status", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo") FROM stdin;
\.


--
-- Data for Name: idp_public_comments_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.idp_public_comments_ef ("Id", "CycleId", "SourceChannel", "Ward", "Region", "Category", "CommentText", "LinkedProjectId", "LinkedObjectiveId", "SubmitterName", "SubmissionDate", "Status", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo") FROM stdin;
\.


--
-- Data for Name: idp_strategic_objectives_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.idp_strategic_objectives_ef ("Id", "CycleId", "Code", "Description", "AlignmentTags", "NdpAlignment", "ProvincialAlignment", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo", "Status") FROM stdin;
\.


--
-- Data for Name: idp_submission_logs_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.idp_submission_logs_ef ("Id", "CycleId", "DocumentVersionId", "SubmissionType", "ReferenceNumber", "SubmissionDate", "ValidationStatus", "ValidationFeedback", "AdoptedIdpFileName", "CouncilResolutionFileName", "MinutesFileName", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo", "Status") FROM stdin;
\.


--
-- Data for Name: idp_workflow_tasks_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.idp_workflow_tasks_ef ("Id", "CycleId", "DocumentVersionId", "TaskType", "AssignedRole", "AssignedTo", "Status", "Comments", "Sequence", "CreatedBy", "CreatedDate", "CompletedBy", "CompletedDate", "ModifiedBy", "ModifiedDate", "VersionNo") FROM stdin;
\.


--
-- Data for Name: mscoa_segments_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.mscoa_segments_ef ("Id", "SegmentType", "Code", "Description", "Level", "ParentCode", "IsPostingLevel", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo", "Status") FROM stdin;
\.


--
-- Data for Name: priority_criteria_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.priority_criteria_ef ("Id", "FrameworkId", "Code", "Name", "Description", "Category", "Weight", "IsActive", "SortOrder", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo") FROM stdin;
\.


--
-- Data for Name: priority_framework_audits_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.priority_framework_audits_ef ("Id", "FrameworkId", "ChangeType", "FieldName", "OldValue", "NewValue", "ChangedBy", "ChangedDate", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo") FROM stdin;
\.


--
-- Data for Name: priority_frameworks_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.priority_frameworks_ef ("Id", "Name", "Version", "CycleId", "Status", "HumanWeight", "AiWeight", "AiMode", "ScaleMin", "ScaleMax", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo") FROM stdin;
\.


--
-- Data for Name: priority_project_scores_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.priority_project_scores_ef ("Id", "FrameworkId", "ProjectId", "CriteriaId", "HumanScore", "AiScore", "BlendedScore", "Comments", "ScoredBy", "ScoredDate", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo") FROM stdin;
\.


--
-- Data for Name: priority_scoring_scales_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.priority_scoring_scales_ef ("Id", "FrameworkId", "ScoreValue", "Label", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo") FROM stdin;
\.


--
-- Data for Name: project_objective_links_ef; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.project_objective_links_ef ("Id", "ProjectId", "ObjectiveId", "Percentage", "CreatedBy", "CreatedDate", "ModifiedBy", "ModifiedDate", "VersionNo") FROM stdin;
\.


--
-- Name: idp_audit_logs_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."idp_audit_logs_ef_Id_seq"', 1, false);


--
-- Name: idp_comment_responses_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."idp_comment_responses_ef_Id_seq"', 1, false);


--
-- Name: idp_cycles_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."idp_cycles_ef_Id_seq"', 1, false);


--
-- Name: idp_document_versions_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."idp_document_versions_ef_Id_seq"', 1, false);


--
-- Name: idp_milestones_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."idp_milestones_ef_Id_seq"', 1, false);


--
-- Name: idp_process_phases_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."idp_process_phases_ef_Id_seq"', 1, false);


--
-- Name: idp_project_indicators_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."idp_project_indicators_ef_Id_seq"', 1, false);


--
-- Name: idp_projects_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."idp_projects_ef_Id_seq"', 1, false);


--
-- Name: idp_public_comments_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."idp_public_comments_ef_Id_seq"', 1, false);


--
-- Name: idp_strategic_objectives_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."idp_strategic_objectives_ef_Id_seq"', 1, false);


--
-- Name: idp_submission_logs_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."idp_submission_logs_ef_Id_seq"', 1, false);


--
-- Name: idp_workflow_tasks_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."idp_workflow_tasks_ef_Id_seq"', 1, false);


--
-- Name: mscoa_segments_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."mscoa_segments_ef_Id_seq"', 1, false);


--
-- Name: priority_criteria_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."priority_criteria_ef_Id_seq"', 1, false);


--
-- Name: priority_framework_audits_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."priority_framework_audits_ef_Id_seq"', 1, false);


--
-- Name: priority_frameworks_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."priority_frameworks_ef_Id_seq"', 1, false);


--
-- Name: priority_project_scores_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."priority_project_scores_ef_Id_seq"', 1, false);


--
-- Name: priority_scoring_scales_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."priority_scoring_scales_ef_Id_seq"', 1, false);


--
-- Name: project_objective_links_ef_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."project_objective_links_ef_Id_seq"', 1, false);


--
-- Name: idp_audit_logs_ef PK_idp_audit_logs_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_audit_logs_ef
    ADD CONSTRAINT "PK_idp_audit_logs_ef" PRIMARY KEY ("Id");


--
-- Name: idp_comment_responses_ef PK_idp_comment_responses_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_comment_responses_ef
    ADD CONSTRAINT "PK_idp_comment_responses_ef" PRIMARY KEY ("Id");


--
-- Name: idp_cycles_ef PK_idp_cycles_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_cycles_ef
    ADD CONSTRAINT "PK_idp_cycles_ef" PRIMARY KEY ("Id");


--
-- Name: idp_document_versions_ef PK_idp_document_versions_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_document_versions_ef
    ADD CONSTRAINT "PK_idp_document_versions_ef" PRIMARY KEY ("Id");


--
-- Name: idp_milestones_ef PK_idp_milestones_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_milestones_ef
    ADD CONSTRAINT "PK_idp_milestones_ef" PRIMARY KEY ("Id");


--
-- Name: idp_process_phases_ef PK_idp_process_phases_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_process_phases_ef
    ADD CONSTRAINT "PK_idp_process_phases_ef" PRIMARY KEY ("Id");


--
-- Name: idp_project_indicators_ef PK_idp_project_indicators_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_project_indicators_ef
    ADD CONSTRAINT "PK_idp_project_indicators_ef" PRIMARY KEY ("Id");


--
-- Name: idp_projects_ef PK_idp_projects_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_projects_ef
    ADD CONSTRAINT "PK_idp_projects_ef" PRIMARY KEY ("Id");


--
-- Name: idp_public_comments_ef PK_idp_public_comments_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_public_comments_ef
    ADD CONSTRAINT "PK_idp_public_comments_ef" PRIMARY KEY ("Id");


--
-- Name: idp_strategic_objectives_ef PK_idp_strategic_objectives_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_strategic_objectives_ef
    ADD CONSTRAINT "PK_idp_strategic_objectives_ef" PRIMARY KEY ("Id");


--
-- Name: idp_submission_logs_ef PK_idp_submission_logs_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_submission_logs_ef
    ADD CONSTRAINT "PK_idp_submission_logs_ef" PRIMARY KEY ("Id");


--
-- Name: idp_workflow_tasks_ef PK_idp_workflow_tasks_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_workflow_tasks_ef
    ADD CONSTRAINT "PK_idp_workflow_tasks_ef" PRIMARY KEY ("Id");


--
-- Name: mscoa_segments_ef PK_mscoa_segments_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mscoa_segments_ef
    ADD CONSTRAINT "PK_mscoa_segments_ef" PRIMARY KEY ("Id");


--
-- Name: priority_criteria_ef PK_priority_criteria_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.priority_criteria_ef
    ADD CONSTRAINT "PK_priority_criteria_ef" PRIMARY KEY ("Id");


--
-- Name: priority_framework_audits_ef PK_priority_framework_audits_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.priority_framework_audits_ef
    ADD CONSTRAINT "PK_priority_framework_audits_ef" PRIMARY KEY ("Id");


--
-- Name: priority_frameworks_ef PK_priority_frameworks_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.priority_frameworks_ef
    ADD CONSTRAINT "PK_priority_frameworks_ef" PRIMARY KEY ("Id");


--
-- Name: priority_project_scores_ef PK_priority_project_scores_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.priority_project_scores_ef
    ADD CONSTRAINT "PK_priority_project_scores_ef" PRIMARY KEY ("Id");


--
-- Name: priority_scoring_scales_ef PK_priority_scoring_scales_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.priority_scoring_scales_ef
    ADD CONSTRAINT "PK_priority_scoring_scales_ef" PRIMARY KEY ("Id");


--
-- Name: project_objective_links_ef PK_project_objective_links_ef; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_objective_links_ef
    ADD CONSTRAINT "PK_project_objective_links_ef" PRIMARY KEY ("Id");


--
-- Name: IX_idp_comment_responses_ef_CommentId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_idp_comment_responses_ef_CommentId" ON public.idp_comment_responses_ef USING btree ("CommentId");


--
-- Name: IX_idp_document_versions_ef_CycleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_idp_document_versions_ef_CycleId" ON public.idp_document_versions_ef USING btree ("CycleId");


--
-- Name: IX_idp_milestones_ef_PhaseId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_idp_milestones_ef_PhaseId" ON public.idp_milestones_ef USING btree ("PhaseId");


--
-- Name: IX_idp_process_phases_ef_CycleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_idp_process_phases_ef_CycleId" ON public.idp_process_phases_ef USING btree ("CycleId");


--
-- Name: IX_idp_project_indicators_ef_ProjectId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_idp_project_indicators_ef_ProjectId" ON public.idp_project_indicators_ef USING btree ("ProjectId");


--
-- Name: IX_idp_projects_ef_CycleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_idp_projects_ef_CycleId" ON public.idp_projects_ef USING btree ("CycleId");


--
-- Name: IX_idp_projects_ef_ObjectiveId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_idp_projects_ef_ObjectiveId" ON public.idp_projects_ef USING btree ("ObjectiveId");


--
-- Name: IX_idp_public_comments_ef_CycleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_idp_public_comments_ef_CycleId" ON public.idp_public_comments_ef USING btree ("CycleId");


--
-- Name: IX_idp_strategic_objectives_ef_CycleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_idp_strategic_objectives_ef_CycleId" ON public.idp_strategic_objectives_ef USING btree ("CycleId");


--
-- Name: IX_idp_submission_logs_ef_CycleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_idp_submission_logs_ef_CycleId" ON public.idp_submission_logs_ef USING btree ("CycleId");


--
-- Name: IX_idp_submission_logs_ef_DocumentVersionId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_idp_submission_logs_ef_DocumentVersionId" ON public.idp_submission_logs_ef USING btree ("DocumentVersionId");


--
-- Name: IX_idp_workflow_tasks_ef_DocumentVersionId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_idp_workflow_tasks_ef_DocumentVersionId" ON public.idp_workflow_tasks_ef USING btree ("DocumentVersionId");


--
-- Name: IX_priority_criteria_ef_FrameworkId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_priority_criteria_ef_FrameworkId" ON public.priority_criteria_ef USING btree ("FrameworkId");


--
-- Name: IX_priority_framework_audits_ef_FrameworkId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_priority_framework_audits_ef_FrameworkId" ON public.priority_framework_audits_ef USING btree ("FrameworkId");


--
-- Name: IX_priority_frameworks_ef_CycleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_priority_frameworks_ef_CycleId" ON public.priority_frameworks_ef USING btree ("CycleId");


--
-- Name: IX_priority_project_scores_ef_CriteriaId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_priority_project_scores_ef_CriteriaId" ON public.priority_project_scores_ef USING btree ("CriteriaId");


--
-- Name: IX_priority_project_scores_ef_FrameworkId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_priority_project_scores_ef_FrameworkId" ON public.priority_project_scores_ef USING btree ("FrameworkId");


--
-- Name: IX_priority_project_scores_ef_ProjectId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_priority_project_scores_ef_ProjectId" ON public.priority_project_scores_ef USING btree ("ProjectId");


--
-- Name: IX_priority_scoring_scales_ef_FrameworkId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_priority_scoring_scales_ef_FrameworkId" ON public.priority_scoring_scales_ef USING btree ("FrameworkId");


--
-- Name: IX_project_objective_links_ef_ObjectiveId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_project_objective_links_ef_ObjectiveId" ON public.project_objective_links_ef USING btree ("ObjectiveId");


--
-- Name: IX_project_objective_links_ef_ProjectId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_project_objective_links_ef_ProjectId" ON public.project_objective_links_ef USING btree ("ProjectId");


--
-- Name: idp_comment_responses_ef FK_idp_comment_responses_ef_idp_public_comments_ef_CommentId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_comment_responses_ef
    ADD CONSTRAINT "FK_idp_comment_responses_ef_idp_public_comments_ef_CommentId" FOREIGN KEY ("CommentId") REFERENCES public.idp_public_comments_ef("Id") ON DELETE CASCADE;


--
-- Name: idp_document_versions_ef FK_idp_document_versions_ef_idp_cycles_ef_CycleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_document_versions_ef
    ADD CONSTRAINT "FK_idp_document_versions_ef_idp_cycles_ef_CycleId" FOREIGN KEY ("CycleId") REFERENCES public.idp_cycles_ef("Id") ON DELETE CASCADE;


--
-- Name: idp_milestones_ef FK_idp_milestones_ef_idp_process_phases_ef_PhaseId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_milestones_ef
    ADD CONSTRAINT "FK_idp_milestones_ef_idp_process_phases_ef_PhaseId" FOREIGN KEY ("PhaseId") REFERENCES public.idp_process_phases_ef("Id") ON DELETE CASCADE;


--
-- Name: idp_process_phases_ef FK_idp_process_phases_ef_idp_cycles_ef_CycleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_process_phases_ef
    ADD CONSTRAINT "FK_idp_process_phases_ef_idp_cycles_ef_CycleId" FOREIGN KEY ("CycleId") REFERENCES public.idp_cycles_ef("Id") ON DELETE CASCADE;


--
-- Name: idp_project_indicators_ef FK_idp_project_indicators_ef_idp_projects_ef_ProjectId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_project_indicators_ef
    ADD CONSTRAINT "FK_idp_project_indicators_ef_idp_projects_ef_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES public.idp_projects_ef("Id") ON DELETE CASCADE;


--
-- Name: idp_projects_ef FK_idp_projects_ef_idp_cycles_ef_CycleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_projects_ef
    ADD CONSTRAINT "FK_idp_projects_ef_idp_cycles_ef_CycleId" FOREIGN KEY ("CycleId") REFERENCES public.idp_cycles_ef("Id") ON DELETE CASCADE;


--
-- Name: idp_projects_ef FK_idp_projects_ef_idp_strategic_objectives_ef_ObjectiveId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_projects_ef
    ADD CONSTRAINT "FK_idp_projects_ef_idp_strategic_objectives_ef_ObjectiveId" FOREIGN KEY ("ObjectiveId") REFERENCES public.idp_strategic_objectives_ef("Id") ON DELETE SET NULL;


--
-- Name: idp_public_comments_ef FK_idp_public_comments_ef_idp_cycles_ef_CycleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_public_comments_ef
    ADD CONSTRAINT "FK_idp_public_comments_ef_idp_cycles_ef_CycleId" FOREIGN KEY ("CycleId") REFERENCES public.idp_cycles_ef("Id") ON DELETE CASCADE;


--
-- Name: idp_strategic_objectives_ef FK_idp_strategic_objectives_ef_idp_cycles_ef_CycleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_strategic_objectives_ef
    ADD CONSTRAINT "FK_idp_strategic_objectives_ef_idp_cycles_ef_CycleId" FOREIGN KEY ("CycleId") REFERENCES public.idp_cycles_ef("Id") ON DELETE CASCADE;


--
-- Name: idp_submission_logs_ef FK_idp_submission_logs_ef_idp_cycles_ef_CycleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_submission_logs_ef
    ADD CONSTRAINT "FK_idp_submission_logs_ef_idp_cycles_ef_CycleId" FOREIGN KEY ("CycleId") REFERENCES public.idp_cycles_ef("Id") ON DELETE CASCADE;


--
-- Name: idp_submission_logs_ef FK_idp_submission_logs_ef_idp_document_versions_ef_DocumentVer~; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_submission_logs_ef
    ADD CONSTRAINT "FK_idp_submission_logs_ef_idp_document_versions_ef_DocumentVer~" FOREIGN KEY ("DocumentVersionId") REFERENCES public.idp_document_versions_ef("Id");


--
-- Name: idp_workflow_tasks_ef FK_idp_workflow_tasks_ef_idp_document_versions_ef_DocumentVers~; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idp_workflow_tasks_ef
    ADD CONSTRAINT "FK_idp_workflow_tasks_ef_idp_document_versions_ef_DocumentVers~" FOREIGN KEY ("DocumentVersionId") REFERENCES public.idp_document_versions_ef("Id") ON DELETE CASCADE;


--
-- Name: priority_criteria_ef FK_priority_criteria_ef_priority_frameworks_ef_FrameworkId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.priority_criteria_ef
    ADD CONSTRAINT "FK_priority_criteria_ef_priority_frameworks_ef_FrameworkId" FOREIGN KEY ("FrameworkId") REFERENCES public.priority_frameworks_ef("Id") ON DELETE CASCADE;


--
-- Name: priority_framework_audits_ef FK_priority_framework_audits_ef_priority_frameworks_ef_Framewo~; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.priority_framework_audits_ef
    ADD CONSTRAINT "FK_priority_framework_audits_ef_priority_frameworks_ef_Framewo~" FOREIGN KEY ("FrameworkId") REFERENCES public.priority_frameworks_ef("Id") ON DELETE CASCADE;


--
-- Name: priority_frameworks_ef FK_priority_frameworks_ef_idp_cycles_ef_CycleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.priority_frameworks_ef
    ADD CONSTRAINT "FK_priority_frameworks_ef_idp_cycles_ef_CycleId" FOREIGN KEY ("CycleId") REFERENCES public.idp_cycles_ef("Id") ON DELETE SET NULL;


--
-- Name: priority_project_scores_ef FK_priority_project_scores_ef_idp_projects_ef_ProjectId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.priority_project_scores_ef
    ADD CONSTRAINT "FK_priority_project_scores_ef_idp_projects_ef_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES public.idp_projects_ef("Id") ON DELETE CASCADE;


--
-- Name: priority_project_scores_ef FK_priority_project_scores_ef_priority_criteria_ef_CriteriaId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.priority_project_scores_ef
    ADD CONSTRAINT "FK_priority_project_scores_ef_priority_criteria_ef_CriteriaId" FOREIGN KEY ("CriteriaId") REFERENCES public.priority_criteria_ef("Id") ON DELETE CASCADE;


--
-- Name: priority_project_scores_ef FK_priority_project_scores_ef_priority_frameworks_ef_Framework~; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.priority_project_scores_ef
    ADD CONSTRAINT "FK_priority_project_scores_ef_priority_frameworks_ef_Framework~" FOREIGN KEY ("FrameworkId") REFERENCES public.priority_frameworks_ef("Id") ON DELETE CASCADE;


--
-- Name: priority_scoring_scales_ef FK_priority_scoring_scales_ef_priority_frameworks_ef_Framework~; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.priority_scoring_scales_ef
    ADD CONSTRAINT "FK_priority_scoring_scales_ef_priority_frameworks_ef_Framework~" FOREIGN KEY ("FrameworkId") REFERENCES public.priority_frameworks_ef("Id") ON DELETE CASCADE;


--
-- Name: project_objective_links_ef FK_project_objective_links_ef_idp_projects_ef_ProjectId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_objective_links_ef
    ADD CONSTRAINT "FK_project_objective_links_ef_idp_projects_ef_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES public.idp_projects_ef("Id") ON DELETE CASCADE;


--
-- Name: project_objective_links_ef FK_project_objective_links_ef_idp_strategic_objectives_ef_Obje~; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_objective_links_ef
    ADD CONSTRAINT "FK_project_objective_links_ef_idp_strategic_objectives_ef_Obje~" FOREIGN KEY ("ObjectiveId") REFERENCES public.idp_strategic_objectives_ef("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 54GaOfQwZb3SMbwQeiTTb9mJFcem0GCZUbwl3Qe3Q5R4loX4L5HIXrGIDjUFT8N

