CREATE TABLE [dbo].[Inven_Inventory](
	[Inventory_ID] [int] IDENTITY(1,1) NOT NULL,
	[StoreID] [int] NOT NULL,
	[CommodityID] [int] NULL,
	[BinLocation] [nvarchar](250) NULL,
	[UnitPrice] [decimal](16, 2) NULL,
	[SellingPrice] [decimal](16, 2) NULL,
	[MinimumLevel] [decimal](14, 4) NULL,
	[MaximumLevel] [decimal](14, 4) NULL,
	[ReorderLevel] [decimal](14, 4) NULL,
	[ReorderQuantity] [decimal](14, 4) NULL,
	[SlowMovingInventory] [bit] NULL,
	[InventoryTurnover] [decimal](16, 2) NULL,
	[CapturerID] [int] NOT NULL,
	[DateCaptured] [datetime] NOT NULL,
	[ModifierID] [int] NULL,
	[DateModified] [datetime] NULL,
	[StockLevelsRequired] [bit] NOT NULL,
	[SlowMovingReason] [nvarchar](500) NULL,
	[OverwrittenSellingPrice] [decimal](16, 2) NULL,
	[OverwrittenBy] [int] NULL,
	[OverwrittenDate] [datetime] NULL,
	[PriceIndicated] [decimal](16, 2) NULL,
	[Quantity] [decimal](18, 0) NOT NULL,
	[Vat] [decimal](18, 0) NOT NULL,
	[FinYear] [varchar](9) NULL,
	[PreferredVendor] [int] NULL,
	[BinNumber] [int] NULL,
	[BinStatusID] [int] NULL,
	[GrnDetailID] [int] NULL,
	[ScoaItemID] [int] NULL,
	[SCOAFunction] [int] NULL,
	[SCOARegion] [int] NULL,
	[SCOACosting] [int] NULL,
	[SCOAFund] [int] NULL,
	[SCOAProject] [int] NULL,
	[RunningTotal] [numeric](16, 2) NULL,
	[CommodityTotalQty] [numeric](18, 0) NULL,
	[CommodityWeightedAvg] [numeric](16, 2) NULL,
	[CommodityWAVGchange] [int] NULL,
	[RequisitionGrnTranNr] [varchar](30) NULL,
	[DocumentNr] [int] NULL,
	[FIFOUnitTotal] [numeric](16, 2) NULL,
	[FIFOValueTotal] [numeric](16, 2) NULL,
	[FIFOTotalAmount] [numeric](18, 2) NULL,
	[FIFODateCaptured] [datetime] NULL,
	[InventoryGRNDetailsID] [int] NULL,
	[BinCode] [varchar](50) NULL,
	[Department] [int] NULL,
	[Division] [int] NULL,
	[AvgPrice] [decimal](18, 2) NULL,
	[ProjectId] [int] NULL,
	[ProjectItemId] [int] NULL,
 CONSTRAINT [PK_Inven_Inventory] PRIMARY KEY CLUSTERED 
(
	[Inventory_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 93, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [storeCommodityUnique] UNIQUE NONCLUSTERED 



