CREATE TABLE [dbo].[Led_GeneralLedger](
	[GenLedger_ID] [int] IDENTITY(1,1) NOT NULL,
	[PostingDate] [datetime] NOT NULL,
	[ProcessingMonth] [int] NOT NULL,
	[VoteID] [int] NULL,
	[FinYear] [varchar](12) NOT NULL,
	[TransactionTypeID] [int] NULL,
	[TransactionDetails] [nvarchar](235) NULL,
	[DocumentNumber] [nvarchar](50) NULL,
	[CashbookTransactionID] [int] NULL,
	[Debit] [decimal](16, 2) NULL,
	[Credit] [decimal](16, 2) NULL,
	[Balance] [decimal](16, 2) NULL,
	[DateCaptured] [datetime] NULL,
	[CapturerID] [int] NULL,
	[DateModified] [datetime] NULL,
	[ModifierID] [int] NULL,
	[MatchTranGuid] [uniqueidentifier] NULL,
	[NormalJournalID] [int] NULL,
	[JournalTransactionTypeID] [int] NULL,
	[MultipleJournalID] [int] NULL,
	[PayrollLinkID] [int] NULL,
	[AssetLinkID] [int] NULL,
	[BillingLinkID] [int] NULL,
	[ExtraLinkID_1] [int] NULL,
	[ExtraLinkID_2] [int] NULL,
	[ExtraLinkID_3] [int] NULL,
	[ExtraLinkDesc] [nvarchar](200) NULL,
	[BillingNormalJournalID] [int] NULL,
	[BillingTransferJournalID] [int] NULL,
	[InvenLinkID] [int] NULL,
	[SCOAFundsID] [int] NULL,
	[SCOARegionID] [int] NULL,
	[SCOACostingID] [int] NULL,
	[SCOAProjectID] [int] NULL,
	[SCOAFunctionID] [int] NULL,
	[SCOAItemID] [int] NOT NULL,
	[DivisionID] [int] NULL,
	[SundryDebtorsJournalID] [int] NULL,
	[ProjectID] [int] NULL,
	[PlanProjectItemID] [int] NULL,
	[VATRate] [decimal](5, 2) NULL,
	[VATRateID] [int] NULL,
	[VATReconControlID] [int] NULL,
	[IsVATReconciled] [bit] NULL,
	[VATReconciledByID] [int] NULL,
	[VATReconciledDate] [datetime] NULL,
	[VATComment] [varchar](50) NULL,
	[PettyCashRegisterLineItemID] [int] NULL,
 CONSTRAINT [PK_Led_GeneralLedger] PRIMARY KEY CLUSTERED 
(
	[GenLedger_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 93, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
