CREATE TABLE [dbo].[Payroll_Employee](
	[Employee_ID] [int] IDENTITY(1,1) NOT NULL,
	[EmpCode] [nvarchar](50) NULL,
	[IdNo] [nvarchar](50) NOT NULL,
	[TitleID] [int] NULL,
	[Initials] [nvarchar](50) NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[SecondName] [nvarchar](50) NULL,
	[Surname] [nvarchar](50) NOT NULL,
	[KnownAsName] [nvarchar](50) NULL,
	[DateOfBirth] [datetime] NOT NULL,
	[GenderID] [int] NOT NULL,
	[LanguageID] [int] NULL,
	[MarriedID] [int] NULL,
	[Dependants] [int] NULL,
	[PassportNumber] [nvarchar](50) NULL,
	[PassportCountryID] [int] NULL,
	[EmailAddress] [nvarchar](100) NULL,
	[HomeNumber] [nvarchar](100) NULL,
	[WorkNumber] [nvarchar](100) NULL,
	[CellNumber] [nvarchar](100) NULL,
	[FaxNumber] [nvarchar](100) NULL,
	[JoiningDate] [datetime] NULL,
	[EndDate] [datetime] NULL,
	[WorkDuration]  AS ([dbo].[GetDateDifferenceInYearsMonthsDays]([JoiningDate],case when [EndDate] IS NULL OR [EndDate]>getdate() then getdate() else [EndDate] end)),
	[WorkOutside] [bit] NULL,
	[IncomeTaxNumber] [nvarchar](100) NULL,
	[ExcludeUIF] [bit] NULL,
	[ExcludeSDL] [bit] NULL,
	[PhysicalAddress1] [nvarchar](100) NULL,
	[PhysicalAddress2] [nvarchar](100) NULL,
	[PhysicalPostalCode] [nvarchar](100) NULL,
	[PhysicalCountryID] [int] NULL,
	[PhysicalProvinceID] [int] NULL,
	[PhysicalTownID] [int] NULL,
	[PostalSameAsPhysical] [bit] NULL,
	[PostalAddress1] [nvarchar](100) NULL,
	[PostalAddress2] [nvarchar](100) NULL,
	[PostalPostalCode] [nvarchar](50) NULL,
	[PostalCountryID] [int] NULL,
	[PostalProvinceID] [int] NULL,
	[PostalTownID] [int] NULL,
	[WorkSameAsPhysical] [bit] NULL,
	[WorkSameAsCompany] [bit] NULL,
	[WorkAddress1] [nvarchar](100) NULL,
	[WorkAddress2] [nvarchar](100) NULL,
	[WorkPostalCode] [nvarchar](50) NULL,
	[WorkCountryID] [int] NULL,
	[WorkProvinceID] [int] NULL,
	[WorkTownID] [int] NULL,
	[PaymentTypeID] [int] NULL,
	[AccountTypeID] [int] NULL,
	[AccountHolderName] [nvarchar](100) NULL,
	[AccountHolderRelationshipID] [int] NULL,
	[AccountNumber] [nvarchar](50) NULL,
	[BankID] [int] NULL,
	[BranchID] [int] NULL,
	[WHPD_Other] [decimal](18, 2) NULL,
	[WDPW_Other] [decimal](18, 2) NULL,
	[RPD_Other] [decimal](18, 2) NULL,
	[RPH_Other] [decimal](18, 2) NULL,
	[RPW_Other] [decimal](18, 2) NULL,
	[WHPM_Monthly] [decimal](18, 2) NULL,
	[WDPM_Monthly] [decimal](18, 2) NULL,
	[WHPD_Monthly] [decimal](18, 2) NULL,
	[RPD_Monthly] [decimal](18, 2) NULL,
	[RPH_Monthly] [decimal](18, 2) NULL,
	[AnnualSalary] [decimal](18, 2) NULL,
	[FixedSalary] [decimal](18, 2) NULL,
	[Enabled] [bit] NULL,
	[CapturerID] [int] NOT NULL,
	[DateCaptured] [datetime] NOT NULL,
	[ModifierID] [int] NULL,
	[DateModified] [datetime] NULL,
	[IsDummy] [bit] NOT NULL,
	[LeaveBased] [int] NULL,
	[Monday] [bit] NULL,
	[Tuesday] [bit] NULL,
	[Wednesday] [bit] NULL,
	[Thursday] [bit] NULL,
	[Friday] [bit] NULL,
	[Saturday] [bit] NULL,
	[Sunday] [bit] NULL,
	[ShiftID] [int] NULL,
	[AllowOverTime] [bit] NULL,
	[MunicipalityID] [int] NULL,
	[CycleID] [int] NULL,
	[PayrollDefinitionGroupID] [int] NULL,
	[EthnicGroupID] [int] NULL,
	[IsMarried] [int] NULL,
	[IsYough] [bit] NULL,
	[ImagePath] [nvarchar](500) NULL,
	[MarriedIdNo] [nvarchar](50) NULL,
	[MarriedDateOfBirth] [datetime] NULL,
	[MarriedGenderID] [int] NULL,
	[MarriedTitleID] [int] NULL,
	[MarriedInitials] [nvarchar](50) NULL,
	[MarriedFirstName] [nvarchar](50) NULL,
	[MarriedSecondName] [nvarchar](50) NULL,
	[MarriedSurname] [nvarchar](50) NULL,
	[MarriedKnownAsName] [nvarchar](50) NULL,
	[MarriedPassportCountryID] [int] NULL,
	[MarriedPassportNumber] [nvarchar](50) NULL,
	[KinContactRelationshipID] [int] NULL,
	[KinContactName] [nvarchar](50) NULL,
	[KinContactNo] [nvarchar](50) NULL,
	[JobProfileID] [int] NULL,
	[TerminationReasonID] [int] NULL,
	[LeaveSchemeID] [int] NULL,
	[ConditionOfServiceID] [int] NULL,
	[Isforeigner] [bit] NULL,
	[HowthePersonMarried] [nvarchar](100) NULL,
	[MethodofCommunication] [int] NULL,
	[MaidenName] [nvarchar](50) NULL,
	[EquityDisabled] [bit] NULL,
	[NotchId] [int] NULL,
	[TaxCalculationType] [int] NULL,
	[BonusCalculation] [int] NULL,
	[IsTemporary] [bit] NULL,
	[NatureOfPersonID] [int] NULL,
	[PhysicalAddressTypeID] [int] NULL,
	[PostalAddressTypeID] [int] NULL,
	[PhysicalPOBoxNo] [nvarchar](50) NULL,
	[PostalPOBoxNo] [nvarchar](50) NULL,
	[PhysicalPostOffice] [nvarchar](50) NULL,
	[PostalPostOffice] [nvarchar](50) NULL,
	[QualificationID] [int] NULL,
	[NewLabour] [bit] NULL,
	[Learners] [bit] NULL,
	[IsContractor] [bit] NULL,
	[BonusAmount] [decimal](18, 2) NULL,
	[KinContactFullName] [nvarchar](50) NULL,
	[PhysicalSuburbID] [int] NULL,
	[PostalSuburbID] [int] NULL,
	[WorkSuburbID] [int] NULL,
	[KinTownID] [int] NULL,
	[KinSuburbID] [int] NULL,
	[KinStreetID] [int] NULL,
	[KinStreetNumber] [nvarchar](200) NULL,
	[KinTelephoneHome] [nvarchar](50) NULL,
	[PhysicalStreetID] [int] NULL,
	[PhysicalComplexName] [nvarchar](200) NULL,
	[PhysicalFlatUnitSuiteNo] [nvarchar](200) NULL,
	[PostalStreetID] [int] NULL,
	[PostalComplexName] [nvarchar](200) NULL,
	[PostalFlatUnitSuiteNo] [nvarchar](200) NULL,
	[ERSID] [int] NULL,
	[ERSFingerPrintCount] [int] NULL,
	[ERSStatusID] [int] NULL,
	[ExcludeUIFNonContributorReasonID] [int] NULL,
	[PackageAmount] [float] NULL,
	[PackageOverriden] [bit] NULL,
	[DisabilityTypeID] [int] NULL,
	[EmailAddressSecondary] [nvarchar](100) NULL,
	[FarmId] [int] NULL,
	[PostalAddress3] [nvarchar](200) NULL,
	[PostalAddress4] [nvarchar](200) NULL,
	[AddressIndicator] [int] NULL,
	[CareOfIntermediary] [nvarchar](21) NULL,
	[AlternateIDNumber] [nvarchar](30) NULL,
	[AlternateIDType] [int] NULL,
	[PhyWorkUnit] [nvarchar](8) NULL,
	[PhyWorkComplex] [nvarchar](200) NULL,
	[PhyWorkStreetNo] [nvarchar](8) NULL,
	[PhyWorkStreetId] [int] NULL,
	[PhyWorkSuburbId] [int] NULL,
	[PhyWorkCountryId] [int] NULL,
	[PhysicalStreetNo] [nvarchar](8) NULL,
	[PostalAddressNo] [nvarchar](8) NULL,
	[PostalStreetName] [nvarchar](100) NULL,
	[IsCareOfPostalAddress] [bit] NULL,
	[PostalAddressIndId] [int] NULL,
	[PoSpecialService] [nvarchar](21) NULL,
	[PostalAddressUnitNumber] [nvarchar](21) NULL,
	[PositionID] [int] NULL,
	[EmployeeTypeID] [int] NULL,
	[EmployeeSubtypeID] [int] NULL,
	[PhysicalAddress3] [nvarchar](35) NULL,
	[PhysicalAddress4] [nvarchar](35) NULL,
	[ShiftRotationID] [int] NULL,
	[BonusValueMOCID] [int] NULL,
	[BonusPaymentDateID] [int] NULL,
	[BonusMonth] [int] NULL,
	[PhyAddressComplex] [nvarchar](200) NULL,
	[PhyAddressUnit] [nvarchar](8) NULL,
	[MarritalStatusDate] [datetime] NULL,
	[Years]  AS (floor(datediff(day,[JoiningDate],case when [EndDate] IS NULL OR [EndDate]>getdate() then getdate() else [EndDate] end)/(365.242199))),
	[Months]  AS (floor(datediff(day,[JoiningDate],case when [EndDate] IS NULL OR [EndDate]>getdate() then getdate() else [EndDate] end)/(30.4375))),
	[Days]  AS (floor(datediff(day,[JoiningDate],case when [EndDate] IS NULL OR [EndDate]>getdate() then getdate() else [EndDate] end))),
	[PayPointID] [int] NULL,
	[RotationID] [int] NULL,
	[ReasonID] [int] NULL,
	[JointAccountEmployeeId] [int] NULL,
	[HasMuncipalAssets] [bit] NULL,
	[AssetReturnDate] [datetime] NULL,
	[NotchChangeReason] [nvarchar](200) NULL,
	[StartDays] [tinyint] NOT NULL,
	[UntilDays] [tinyint] NOT NULL,
	[SalaryBasedOn] [int] NULL,
	[Rate] [decimal](18, 2) NULL,
	[PrevSalary] [decimal](18, 2) NULL,
 CONSTRAINT [PK_Payroll_Employee] PRIMARY KEY CLUSTERED 
(
	[Employee_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 93, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
