CREATE TABLE [dbo].[Plan_Project](
	[Project_ID] [int] IDENTITY(1,1) NOT NULL,
	[ProjectName] [nvarchar](500) NOT NULL,
	[ProjectDesc] [nvarchar](500) NOT NULL,
	[ProjectManagerID] [int] NULL,
	[SupplyChainOfficialID] [int] NULL,
	[CapitalOperation] [int] NULL,
	[CostEstimate] [decimal](16, 2) NOT NULL,
	[ScoaProjectID] [int] NOT NULL,
	[EstimatedStartDate] [datetime] NULL,
	[EstimatedEndDate] [datetime] NULL,
	[ProjectStatus] [int] NOT NULL,
	[CommencementDate] [datetime] NULL,
	[CapturerID] [int] NOT NULL,
	[DateCaptured] [datetime] NOT NULL,
	[ModifierID] [int] NULL,
	[DateModified] [datetime] NULL,
	[FinYear] [nvarchar](9) NULL,
	[ProjectDetailDesc] [nvarchar](500) NULL,
	[ProjectCategoryID] [int] NULL,
	[ProjectImplementAgentID] [int] NULL,
	[Longitude] [nvarchar](200) NULL,
	[Latitude] [nvarchar](200) NULL,
	[ProgrammeManagerID] [int] NULL,
	[FinancialControllerID] [int] NULL,
	[ProjectTypeID] [int] NULL,
	[EstimatedDuration] [int] NULL,
	[ProjectDistinctionID] [int] NULL,
	[IsDeleted] [bit] NULL,
	[HistoricalProjectCode] [nvarchar](100) NULL,
	[ProjectParentID] [int] NULL,
	[SingleMultiYear] [varchar](5) NULL,
	[PreviousReferenceId] [int] NULL,
	[ProjectCode] [int] NULL,
	[CostingProject] [bit] NULL,
 CONSTRAINT [PK_Plan_Project] PRIMARY KEY CLUSTERED 
(
	[Project_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 93, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
