CREATE TABLE [dbo].[SCM_InvoiceDetail](
	[InvoiceDetail_ID] [int] IDENTITY(1,1) NOT NULL,
	[InvoiceID] [int] NULL,
	[ItemDescription] [nvarchar](max) NULL,
	[UnitPrice] [decimal](18, 2) NULL,
	[QuantityOrder] [decimal](16, 4) NULL,
	[QuantityReceived] [decimal](16, 4) NULL,
	[VatInclude] [bit] NULL,
	[Amount] [decimal](30, 2) NULL,
	[ReceivedUnitPrice] [decimal](18, 2) NULL,
	[VatAmount] [decimal](18, 2) NULL,
	[TotalAmount] [decimal](18, 2) NULL,
	[StatusID] [int] NULL,
	[ApprovedBy] [int] NULL,
	[ApprovedDate] [datetime] NULL,
	[CancelReason] [nvarchar](500) NULL,
	[EmployeeID] [int] NULL,
	[SCOAFunctionID] [int] NOT NULL,
	[SCOAItemID] [int] NOT NULL,
	[SCOARegionID] [int] NOT NULL,
	[SCOACostingID] [int] NOT NULL,
	[SCOAProjectID] [int] NOT NULL,
	[Enabled] [bit] NOT NULL,
	[DateCaptured] [datetime] NOT NULL,
	[CapturerID] [int] NOT NULL,
	[DateModified] [datetime] NULL,
	[ModifierID] [int] NULL,
	[VoteId] [int] NULL,
	[OrderDetailID] [int] NULL,
	[IsVoid] [bit] NULL,
	[VoidedDate] [datetime] NULL,
	[VoidedReason] [nvarchar](1000) NULL,
	[VoidedBy] [int] NULL,
	[GRRDetailID] [int] NULL,
	[ServiceInvoiceDetailID] [int] NULL,
	[isDiscounted] [bit] NULL,
	[DiscountRate] [decimal](18, 4) NULL,
	[DiscountAmount] [decimal](18, 2) NULL,
	[DiscountedAmount] [decimal](18, 2) NULL,
	[IsVatExemption] [bit] NULL,
	[ContractDetailItemsID] [int] NULL,
	[DivisionId] [int] NULL,
	[VATApportionmentPercentage] [decimal](12, 2) NULL,
	[VATApportionmentAmount] [decimal](18, 2) NULL,
	[PlanProjectItemID] [int] NULL,
	[ContractServiceRequestDetailsId] [int] NULL,
	[TakeOnContractDetailId] [int] NULL,
	[LinkedInvoiceDetailId] [int] NULL,
 CONSTRAINT [PK_SCM_InvoiceDetail] PRIMARY KEY CLUSTERED 
(
	[InvoiceDetail_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 93, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
