CREATE TABLE [dbo].[SCM_Invoice](
	[Invoice_ID] [int] IDENTITY(1,1) NOT NULL,
	[OrderID] [int] NULL,
	[GRNID] [int] NULL,
	[VendorInvoiceNumber] [nvarchar](50) NULL,
	[InvoiceDate] [datetime] NULL,
	[Enabled] [bit] NOT NULL,
	[DateCaptured] [datetime] NOT NULL,
	[CapturerID] [int] NOT NULL,
	[DateModified] [datetime] NULL,
	[ModifierID] [int] NULL,
	[StatusID] [int] NULL,
	[FinancialYear] [nvarchar](50) NULL,
	[ApprovedBy] [int] NULL,
	[ApprovedDate] [datetime] NULL,
	[CancelReason] [nvarchar](500) NULL,
	[Comments] [nvarchar](500) NULL,
	[VoteSectionID] [int] NULL,
	[VendorCreditorID] [int] NULL,
	[PayrollPeriodID] [int] NULL,
	[AccountID] [int] NULL,
	[VendorInvoiceNumberCustom] [nvarchar](50) NULL,
	[ServiceInvoiceID] [int] NULL,
	[DocNumber] [nvarchar](20) NULL,
	[Calculated_Invoice_Amount] [decimal](16, 2) NULL,
	[Retention_Amount] [decimal](16, 2) NULL,
	[DocumentStatus] [varchar](5) NULL,
	[RemittanceAdviceID] [int] NULL,
	[ContractID] [int] NULL,
	[InvoicingVendorID] [int] NULL,
	[EFTGeneratedDate] [datetime] NULL,
	[IsEFTApproved] [int] NULL,
	[IsEFTGenerated] [int] NULL,
	[EFTApprovedDate] [datetime] NULL,
	[EFTApprovedBy] [int] NULL,
	[EFTDeclineReason] [varchar](50) NULL,
	[OldInvoiceNumber] [nvarchar](500) NULL,
	[PaymentReference] [nvarchar](500) NULL,
	[GRNDetailID] [int] NULL,
	[Discount] [bit] NULL,
	[VolumeDiscount] [bit] NULL,
	[DiscountToAll] [bit] NULL,
	[DiscountRate] [decimal](18, 2) NULL,
	[DiscountAmount] [decimal](18, 2) NULL,
	[InvoiceReceivedDate] [datetime] NULL,
	[FinalApprovedBy] [int] NULL,
	[FinalApprovedDate] [datetime] NULL,
	[PaymentCertificateId] [int] NULL,
	[CashbookId] [int] NULL,
	[Guarantee_Amount] [decimal](10, 2) NULL,
	[SocialResp_Amount] [decimal](10, 2) NULL,
	[RetentionReleased] [decimal](18, 2) NULL,
	[GuaranteeReleased] [decimal](18, 2) NULL,
	[ContractServiceRequestId] [int] NULL,
	[TakeOnContractId] [int] NULL,
	[ProcessingMonth] [int] NULL,
	[IsTransferredToLongTermLiability] [bit] NULL,
	[LongTermAgreementDate] [datetime] NULL,
	[TransferredDate] [datetime] NULL,
	[TransferredSCOAItemId] [int] NULL,
	[VoidProcessingMonth] [int] NULL,
	[RetentionWithholding] [decimal](18, 2) NULL,
	[GuaranteeWithholding] [decimal](18, 2) NULL,
	[WithholdingDate] [datetime] NULL,
	[WithholdingComments] [nvarchar](500) NULL,
 CONSTRAINT [PK_SCM_Invoice] PRIMARY KEY CLUSTERED 
(
	[Invoice_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 93, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
