import { Routes } from '@angular/router';
import { authGuard } from './core/guards/auth.guard';

export const routes: Routes = [
  { path: 'login', loadComponent: () => import('./features/auth/login.component').then(m => m.LoginComponent) },
  { path: 'change-password', loadComponent: () => import('./features/auth/change-password.component').then(m => m.ChangePasswordComponent), canActivate: [authGuard] },
  { path: 'compilations/:id/preview', loadComponent: () => import('./features/compilations/afs-preview.component').then(m => m.AfsPreviewComponent), canActivate: [authGuard] },
  { path: 'compilations/:id/index', loadComponent: () => import('./features/compilations/afs-index.component').then(m => m.AfsIndexComponent), canActivate: [authGuard] },
  { path: 'review/:token', loadComponent: () => import('./features/review/external-review.component').then(m => m.ExternalReviewComponent) },
  { path: 'mappings/fullscreen', loadComponent: () => import('./features/mappings/mappings.component').then(m => m.MappingsComponent), canActivate: [authGuard], data: { fullscreen: true } },
  { path: 'mapping-studio', loadComponent: () => import('./features/mapping-workbench/mapping-studio-fullscreen.component').then(m => m.MappingStudioFullscreenComponent), canActivate: [authGuard] },
  {
    path: '',
    loadComponent: () => import('./layout/shell.component').then(m => m.ShellComponent),
    canActivate: [authGuard],
    children: [
      { path: 'dashboard', loadComponent: () => import('./features/dashboards/dashboard-container.component').then(m => m.DashboardContainerComponent) },
      { path: 'dashboards/cfo-executive', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'dashboards/afs-control', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'dashboards/audit-management', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'dashboards/rfi-management', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'dashboards/audit-findings', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'dashboards/financial-ratios', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'templates', loadComponent: () => import('./features/templates/templates.component').then(m => m.TemplatesComponent) },
      { path: 'templates/:id', loadComponent: () => import('./features/templates/template-detail.component').then(m => m.TemplateDetailComponent) },
      { path: 'templates/:id/style', loadComponent: () => import('./features/templates/template-style-editor.component').then(m => m.TemplateStyleEditorComponent) },
      { path: 'mappings', loadComponent: () => import('./features/mappings/mappings.component').then(m => m.MappingsComponent) },
      { path: 'compilations', loadComponent: () => import('./features/compilations/compilations.component').then(m => m.CompilationsComponent) },
      { path: 'compilations/:id', loadComponent: () => import('./features/compilations/compilation-detail.component').then(m => m.CompilationDetailComponent) },
      { path: 'working-papers', loadComponent: () => import('./features/working-papers/working-papers.component').then(m => m.WorkingPapersComponent) },
      { path: 'rfis', loadComponent: () => import('./features/rfis/rfis.component').then(m => m.RfisComponent) },
      { path: 'findings', loadComponent: () => import('./features/findings/findings.component').then(m => m.FindingsComponent) },
      { path: 'documents', loadComponent: () => import('./features/document-management/document-management.component').then(m => m.DocumentManagementComponent) },
      { path: 'evidence', redirectTo: 'documents', pathMatch: 'full' },
      { path: 'adjustments', loadComponent: () => import('./features/adjustments/adjustments.component').then(m => m.AdjustmentsComponent) },
      { path: 'exports', loadComponent: () => import('./features/exports/exports.component').then(m => m.ExportsComponent) },
      { path: 'reports', loadComponent: () => import('./features/reports/reports.component').then(m => m.ReportsComponent) },
      { path: 'admin', loadComponent: () => import('./features/admin/admin.component').then(m => m.AdminComponent) },
      { path: 'admin/validation-rules', loadComponent: () => import('./features/admin/validation-rules.component').then(m => m.ValidationRulesComponent) },
      { path: 'mscoa', loadComponent: () => import('./features/mscoa/mscoa.component').then(m => m.MscoaComponent) },
      { path: 'abbreviations', redirectTo: 'general-information', pathMatch: 'full' },
      { path: 'general-information', loadComponent: () => import('./features/general-information/general-information.component').then(m => m.GeneralInformationComponent) },
      { path: 'accounting-policies', loadComponent: () => import('./features/accounting-policies/accounting-policies.component').then(m => m.AccountingPoliciesComponent) },
      { path: 'integrity', loadComponent: () => import('./features/dashboard/integrity-checks.component').then(m => m.IntegrityChecksComponent) },
      { path: 'tb-import-workbench', loadComponent: () => import('./features/tb-import-workbench/tb-import-workbench.component').then(m => m.TbImportWorkbenchComponent) },
      { path: 'opening-balance-control', loadComponent: () => import('./features/opening-balance-control/opening-balance-control.component').then(m => m.OpeningBalanceControlComponent) },
      { path: 'mapping-workbench', loadComponent: () => import('./features/mapping-workbench/mapping-workbench.component').then(m => m.MappingWorkbenchComponent) },
      { path: 'afs-versions', loadComponent: () => import('./features/afs-versions/afs-versions.component').then(m => m.AfsVersionsComponent) },
      { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
    ],
  },
  { path: '**', redirectTo: 'login' },
];
