namespace PlatinumBudget.Api.DTOs;

public record CreateVirementDto(
    int BudgetVersionId,
    string BudgetType,
    int FromScoaItemId,
    int FromScoaFundId,
    int FromScoaFunctionId,
    int FromScoaProjectId,
    int FromScoaRegionId,
    int FromScoaCostingId,
    int FromScoaMscId,
    int ToScoaItemId,
    int ToScoaFundId,
    int ToScoaFunctionId,
    int ToScoaProjectId,
    int ToScoaRegionId,
    int ToScoaCostingId,
    int ToScoaMscId,
    decimal Amount,
    string Motivation,
    string? PolicyReference
);

public record VirementListDto(
    int Id,
    string VirementNumber,
    int BudgetVersionId,
    string BudgetVersionName,
    string Status,
    string BudgetType,
    int CurrentApprovalLevel,
    bool RequiresCouncilApproval,
    string FromSegmentString,
    string ToSegmentString,
    decimal Amount,
    string Motivation,
    bool ThresholdExceeded,
    decimal? ThresholdPercentage,
    string CreatedBy,
    DateTime CreatedOn,
    string? ApprovedBy,
    DateTime? ApprovedOn,
    string? RejectedBy,
    DateTime? RejectedOn,
    string? RejectionReason,
    List<ApprovalDto> Approvals
);

public record VirementDetailDto(
    int Id,
    string VirementNumber,
    int BudgetVersionId,
    string BudgetVersionName,
    string Status,
    string BudgetType,
    int CurrentApprovalLevel,
    bool RequiresCouncilApproval,
    int FromScoaItemId,
    string FromItemCode,
    string FromItemDesc,
    int FromScoaFundId,
    string FromFundCode,
    string FromFundDesc,
    int FromScoaFunctionId,
    string FromFunctionCode,
    string FromFunctionDesc,
    int FromScoaProjectId,
    string FromProjectCode,
    string FromProjectDesc,
    int FromScoaRegionId,
    string FromRegionCode,
    string FromRegionDesc,
    int FromScoaCostingId,
    string FromCostingCode,
    string FromCostingDesc,
    int FromScoaMscId,
    string FromMscCode,
    string FromMscDesc,
    int ToScoaItemId,
    string ToItemCode,
    string ToItemDesc,
    int ToScoaFundId,
    string ToFundCode,
    string ToFundDesc,
    int ToScoaFunctionId,
    string ToFunctionCode,
    string ToFunctionDesc,
    int ToScoaProjectId,
    string ToProjectCode,
    string ToProjectDesc,
    int ToScoaRegionId,
    string ToRegionCode,
    string ToRegionDesc,
    int ToScoaCostingId,
    string ToCostingCode,
    string ToCostingDesc,
    int ToScoaMscId,
    string ToMscCode,
    string ToMscDesc,
    decimal Amount,
    string Motivation,
    string? PolicyReference,
    decimal? ThresholdPercentage,
    bool ThresholdExceeded,
    BudgetSummaryDto FromBudgetSummary,
    BudgetSummaryDto ToBudgetSummary,
    string CreatedBy,
    DateTime CreatedOn,
    string? ApprovedBy,
    DateTime? ApprovedOn,
    string? RejectedBy,
    DateTime? RejectedOn,
    string? RejectionReason,
    List<ApprovalDto> Approvals
);

public record BudgetSummaryDto(
    decimal OriginalBudget,
    decimal PriorVirements,
    decimal Adjustments,
    decimal CurrentBudget,
    decimal Reserved,
    decimal Committed,
    decimal Actual,
    decimal AvailableBudget,
    decimal NewAvailableBudget
);

public record VirementApprovalChainDto(
    List<VirementApprovalStepDto> Steps
);

public record VirementApprovalStepDto(
    int Step,
    string LevelName,
    string Status,
    string? ApprovedBy,
    DateTime? ApprovedOn,
    string? Comment,
    bool IsCurrent
);
