import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
  { path: 'dashboard', loadComponent: () => import('./pages/dashboard/dashboard.page').then(m => m.DashboardPage) },
  { path: 'budget-versions', loadComponent: () => import('./pages/budget-versions/version-list.page').then(m => m.VersionListPage) },
  { path: 'budget-versions/:id', loadComponent: () => import('./pages/budget-versions/version-detail.page').then(m => m.VersionDetailPage) },
  { path: 'budget-strings', loadComponent: () => import('./pages/budget-strings/strings-list.page').then(m => m.StringsListPage) },
  { path: 'projects/capture', loadComponent: () => import('./pages/projects/capture/project-capture.page').then(m => m.ProjectCapturePage) },
  { path: 'projects/capture/:id', loadComponent: () => import('./pages/projects/capture/project-capture.page').then(m => m.ProjectCapturePage) },
  { path: 'projects/export-original-budget', loadComponent: () => import('./pages/projects/placeholder/projects-placeholder.page').then(m => m.ProjectsPlaceholderPage), data: { title: 'Export Original Budget' } },
  { path: 'projects/export-adjustment-budget', loadComponent: () => import('./pages/projects/placeholder/projects-placeholder.page').then(m => m.ProjectsPlaceholderPage), data: { title: 'Export Adjustment Budget' } },
  { path: 'projects/import', loadComponent: () => import('./pages/projects/placeholder/projects-placeholder.page').then(m => m.ProjectsPlaceholderPage), data: { title: 'Import Projects' } },
  { path: 'projects/register', loadComponent: () => import('./pages/projects/placeholder/projects-placeholder.page').then(m => m.ProjectsPlaceholderPage), data: { title: 'Register Projects / Exception List' } },
  { path: 'projects/zero-budget', loadComponent: () => import('./pages/projects/placeholder/projects-placeholder.page').then(m => m.ProjectsPlaceholderPage), data: { title: 'Add Zero Budget Items to Current Budget' } },
  { path: 'projects/cp3-sync', loadComponent: () => import('./pages/projects/placeholder/projects-placeholder.page').then(m => m.ProjectsPlaceholderPage), data: { title: 'CP3 Project Sync' } },
  { path: 'projects', loadComponent: () => import('./pages/projects/projects-list.page').then(m => m.ProjectsListPage) },
  { path: 'budget-approval/approve-draft', loadComponent: () => import('./pages/projects/placeholder/projects-placeholder.page').then(m => m.ProjectsPlaceholderPage), data: { title: 'Approve Draft' } },
  { path: 'budget-approval/approve-final', loadComponent: () => import('./pages/projects/placeholder/projects-placeholder.page').then(m => m.ProjectsPlaceholderPage), data: { title: 'Approve Final' } },
  { path: 'virements', loadComponent: () => import('./pages/virements/virements-list.page').then(m => m.VirementsListPage) },
  { path: 'virement-policy', loadComponent: () => import('./pages/virement-policy/virement-policy.page').then(m => m.VirementPolicyPage) },
  { path: 'validation', loadComponent: () => import('./pages/validation/validation-dashboard.page').then(m => m.ValidationDashboardPage) },
  { path: 'reports', loadComponent: () => import('./pages/reports/reports.page').then(m => m.ReportsPage) },
  { path: 'analytics', loadComponent: () => import('./pages/analytics/analytics.page').then(m => m.AnalyticsPage) },
  { path: 'billing/tariffs', loadComponent: () => import('./pages/billing/tariffs/tariffs.page').then(m => m.TariffsPage) },
  { path: 'billing/scenarios', loadComponent: () => import('./pages/billing/scenarios/scenarios.page').then(m => m.ScenariosPage) },
  { path: 'billing/consumers', loadComponent: () => import('./pages/billing/consumers/consumers.page').then(m => m.ConsumersPage) },
  { path: 'billing/revenue', loadComponent: () => import('./pages/billing/revenue/revenue.page').then(m => m.RevenuePage) },
  { path: 'billing/rebates', loadComponent: () => import('./pages/billing/rebates/rebates.page').then(m => m.RebatesPage) },
  { path: 'billing/draft-budget', loadComponent: () => import('./pages/billing/draft-budget/draft-budget.page').then(m => m.DraftBudgetPage) },
  { path: 'creditors/expenditure', loadComponent: () => import('./pages/creditors/expenditure/expenditure.page').then(m => m.ExpenditurePage) },
  { path: 'creditors/scenarios', loadComponent: () => import('./pages/creditors/scenarios/scenarios.page').then(m => m.CreditorscenariosPage) },
  { path: 'creditors/categories', loadComponent: () => import('./pages/creditors/categories/categories.page').then(m => m.CreditorCategoriesPage) },
  { path: 'creditors/projections', loadComponent: () => import('./pages/creditors/projections/projections.page').then(m => m.CreditorProjectionsPage) },
  { path: 'creditors/liabilities', loadComponent: () => import('./pages/creditors/liabilities/liabilities.page').then(m => m.CreditorLiabilitiesPage) },
  { path: 'creditors/draft-budget', loadComponent: () => import('./pages/creditors/draft-budget/draft-budget.page').then(m => m.CreditorDraftBudgetPage) },
  { path: 'hr-payroll/post-establishment', loadComponent: () => import('./pages/hr-payroll/post-establishment/post-establishment.page').then(m => m.PostEstablishmentPage) },
  { path: 'hr-payroll/salary-calculations', loadComponent: () => import('./pages/hr-payroll/salary-calculations/salary-calculations.page').then(m => m.SalaryCalculationsPage) },
  { path: 'hr-payroll/variable-benefits', loadComponent: () => import('./pages/hr-payroll/variable-benefits/variable-benefits.page').then(m => m.VariableBenefitsPage) },
  { path: 'hr-payroll/statutory-deductions', loadComponent: () => import('./pages/hr-payroll/statutory-deductions/statutory-deductions.page').then(m => m.StatutoryDeductionsPage) },
  { path: 'hr-payroll/benefit-obligations', loadComponent: () => import('./pages/hr-payroll/benefit-obligations/benefit-obligations.page').then(m => m.BenefitObligationsPage) },
  { path: 'hr-payroll/draft-budget', loadComponent: () => import('./pages/hr-payroll/draft-budget/draft-budget.page').then(m => m.HrDraftBudgetPage) },
];
